### ISSUE TITLE
in folders, after creating a new office, the user cant assign the folder to the new office

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1004]
the expected result should show an office named " test" but it doesnt show anything

![image](https://user-images.githubusercontent.com/38312178/41592956-06fb7fae-73c7-11e8-9034-d9ddf13efcc1.png)

**Comment by nevos** [comment]
I can see this hapenning in 203

**Comment by nevos** [comment]
problem:
![image](https://user-images.githubusercontent.com/1281931/41977045-1c1233c2-7a27-11e8-8eb4-80e5495838ab.png)
folders in office presents a wrong list of entites - not folders.

**Comment by nevos** [comment]
this also happens in templatedocs

**Comment by nevos** [comment]
@manmorc in addition - the office is not being saved after selection
