### ISSUE TITLE
document sending bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1006]
in documents, after sending a document, the other person recieves it, but cant accept it, in addition, the document is listed as accepted on his screen but the sender cant see that the document got accepted, and can only see the accepting screen 

![image](https://user-images.githubusercontent.com/38312178/41593506-f6eb4e76-73c8-11e8-9829-355118ba1f31.png)

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/41651881-56d9b9d2-748a-11e8-940f-95040ec2d7be.png)
@manmorc there is a slider ui problem

**Comment by nevos** [comment]
flow to recreate: 
1. create officeDoc
2. send it to another user (status changed so you need to set filter for officDoc list to "all")
3. log in as other user (from chrome). click on yellow "distribution" button to get the popup.
4. the slider begins in the left, and should begin on the right.

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/41652295-4dbcc528-748b-11e8-890c-8f909597f310.png)

**Comment by manmorc** [comment]
@nevos the button distributed is active even after slider activates, is it a right behavior ?                             
https://github.com/linnovate/root/issues/1006

**Comment by nevos** [comment]
@manmorc no after sliding the slider should disable
