### ISSUE TITLE
Document upload form templateDoc bug 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1012]
Open new document .
Pick a folder.
Click on choose from template.
Expected result: open a new window with the all templates that connected to the folder.
Actual result: open a new window to delete the all missions that connected to the item.
![bug](https://user-images.githubusercontent.com/31100069/41647323-b238a3f8-747e-11e8-845b-3ee67f001838.PNG)

**Comment by nevos** [comment]
this should be the popup:
![image](https://user-images.githubusercontent.com/1281931/41714114-f11af132-7557-11e8-9ef3-1f6a3f2fe0a4.png)

**Comment by nevos** [comment]
and it shows after selecting an office and creating a template doc
![image](https://user-images.githubusercontent.com/1281931/41714184-2ac75790-7558-11e8-83d9-cc576dda003a.png)

**Comment by chensabag** [comment]
I tried to upload from template and the bug didn't fix.

![image](https://user-images.githubusercontent.com/25196313/42133168-d1dc7d30-7d2d-11e8-9d46-2825c08655e1.png)
