### ISSUE TITLE
tasks status visual bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1015]
in the tasks template, below the status tab there's a waiting for confirmation button that changes the task's status to waiting for confirmation

![image](https://user-images.githubusercontent.com/38312178/41647887-2c16f05c-7480-11e8-862b-82aa18921c6e.png)

![image](https://user-images.githubusercontent.com/38312178/41647911-37dc6afc-7480-11e8-8a8a-c820a63d92a3.png)

**Comment by nevos** [comment]
@yaronmir works as before? works as planned?
