### ISSUE TITLE
searching bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1017]
searching for a task/ project/ folder/ office doesnt show the result in the list or in the show results tab and the show results tab gets stuck after finding an entity

![image](https://user-images.githubusercontent.com/38312178/41652509-f0dd84d6-748b-11e8-936b-f535c7889e4c.png)

**Comment by nevos** [comment]
@yaronmir probably due to server lagging. retest when you see search is generally finding results and page response time is reasonable
