### ISSUE TITLE
permissions bug 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1019]
changing the partners permission still allows him to change things but doesnt save it after refreshing

**Comment by nevos** [comment]
@yaronmir unclear. please provide better explanation.

**Comment by yaronmir** [comment]
@nevos changing the partner's permission doesnt update until he refreshes the page, he can still do things according to his previous permissions, even thought the changes aren't saved after he refreshes the page

**Comment by nevos** [comment]
@manmorc basically I understand that the change works server not client. pls test.

**Comment by manmorc** [comment]
@nevos nope, there was no server api for getting users permissions, all permissions are located in permissions service, client side.

**Comment by nevos** [comment]
@yaronmir - when you change another user permission, it will not update on client side, until refresh.
2) their permissions are updated on server side, so the behaviour you describe is exactly how the feature is supposed to work.
marking as closed.
