### ISSUE TITLE
Number in search not the same

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1037]
In the search, after click on deleted items, the numbers in the sidebar change
But it's not the same as the number in the list/the num of "results found"

![image](https://user-images.githubusercontent.com/17906421/41819183-774b22e0-77c4-11e8-97ce-3c147b5040bb.png)

**Comment by manmorc** [comment]
@nevos now the count of issues in submenu shows all found entities, **including recycled**. it is needed to show only normal / recycled results there?

**Comment by nevos** [comment]
if the ?recycled=true is on in the url show only recycled.
if not - show only not recycled sums
