### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1038]
In every entity: the tab activities:
![image](https://user-images.githubusercontent.com/17906421/41819194-c1e3c6f4-77c4-11e8-96ad-8f42cb75065f.png)

Needs tobe: "קבצים"
![image](https://user-images.githubusercontent.com/17906421/41819198-ddb6b8f0-77c4-11e8-905b-0a8b04d61e2c.png)

**Comment by nevos** [comment]
translations:
activities => עדכונים
מסמכים => קבצים
