### ISSUE TITLE
Remove UI of entity "User"

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1039]
In the system there is entity "User" - so in the futre we will work on that.
Until then, we need to make it unseen in the UI of the system:
![image](https://user-images.githubusercontent.com/17906421/41819220-57dc9096-77c5-11e8-8995-e44ec0033d12.png)

![image](https://user-images.githubusercontent.com/17906421/41819226-66d49b16-77c5-11e8-8bd4-73d756187964.png)

And in every other entity in the system

**Comment by nevos** [comment]
please go over tasks and projects, and remove (visually) tasks assigned/belong to secion in submenu.
