### ISSUE TITLE
restoring an entity

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1061]
after clicking on search, show deleted items, then clicking on a deleted entity, and clicking on restore entity, the restored entity still shows up on the deleted list until refrshing the page 

![image](https://user-images.githubusercontent.com/38312178/42131857-758f5f70-7d14-11e8-93a8-86521be37de4.png)

in the pic above i restored the "ewewewe" discussion

**Comment by nevos** [comment]
the server may tak time to process the search results. The behavior is as expected as long as in 1-2 seconds the task is not showing in a subsequent refresh/new search.
In case this is not the case, report in comment.
