### ISSUE TITLE
Folders: can't open more than two tags.

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1067]
After open two tags the plus button disappear..
![image](https://user-images.githubusercontent.com/31100069/42133358-60bede82-7d31-11e8-95e5-a66cc8ad3b91.png)

**Comment by nevos** [comment]
@manmorc 
1) office tags are not saved
2) after adding 2 tags - (+) sign disapears

**Comment by nevos** [comment]
merged by hotfix/1067
