### ISSUE TITLE
officeDocument attachments not saved

### ISSUE THREAD

**Issue by nevos** [linnovate/root#1076]

**Comment by nevos** [comment]
**https://github.com/linnovate/root/pull/1077
does not resolve the issue.**
-- issue/928 changed officeDocuments to officeDocument in multiple locations.
this is where the change occured - when fixing i think the popup.
-- change all to officeDocuments
and test all attachment operation in documents.
pr to master, then merge back to develop.

**Comment by manmorc** [comment]
issue/928 changed 'officeDocument' in opening modal, not in flow saving items

**Comment by manmorc** [comment]
can't find any problems with uploading document
