### ISSUE TITLE
Can't create officedocument from folder

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1107]
Can't open new officedocument from folder:

![image](https://user-images.githubusercontent.com/17906421/42582855-c3db63be-8538-11e8-9e2b-08c128b4fcf7.png)

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/42616677-ce247304-85b7-11e8-98b5-6ec744362417.png)
problem is 1c4cebee7f1dfc2fe9006b479d805b0585949d17 by @srayaAvraham after 204 tag

**Comment by nevos** [comment]
@ohadetsion see comment above

**Comment by ohadetsion** [comment]
fixed
