### ISSUE TITLE
Can't see more then 25 folders in list

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1108]
Can't see more then 25 folders in  all folder list:

![image](https://user-images.githubusercontent.com/17906421/42583451-a45a853c-8539-11e8-9b0e-6792efbb249e.png)

Also not in folders from office:
![image](https://user-images.githubusercontent.com/17906421/42583538-d163a202-8539-11e8-8c2c-5944bfd74e10.png)

**Comment by nevos** [comment]
http://root.204.projects.linnovate.net/folders/by-office/
also 
http://root.204.projects.linnovate.net/folders/all
