### ISSUE TITLE
Can't see folders in tab

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1109]
Also related to #1108 , in details-pane, in the tab "folders" when you from an office, you can't see any folders:

![image](https://user-images.githubusercontent.com/17906421/42583786-60110062-853a-11e8-8666-80d7b52b35ea.png)

But they exists:

![image](https://user-images.githubusercontent.com/17906421/42583812-6eba7f80-853a-11e8-8b59-c1608b48c65e.png)

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/42618052-7f6eb634-85bc-11e8-8d6d-1bdf2d90b4a9.png)
the list of folders is missing under folders tab
see for example http://root.203.projects.linnovate.net/offices/all/5b2a1a9a0ecbb70013214dcd/folders of how it should work

**Comment by manmorc** [comment]
i see these lists are not seen everywhere, for example in projects

**Comment by nevos** [comment]
resolved in https://github.com/linnovate/root/pull/1118
