### ISSUE TITLE
opening a new sub project or sub task doesnt save them in the sub projects/tasks list but as independent entities

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1113]
opening a new task in the "sub projects" tab doesnt save them in the sub projects list but as independent projects 

![image](https://user-images.githubusercontent.com/38312178/42618820-e42fba8a-85be-11e8-9368-fef9ff1bbafb.png)
 expected result : the 2-4 sub projects i just created will show up in the project's list of sub projects 

![image](https://user-images.githubusercontent.com/38312178/42618885-f7f89e4c-85be-11e8-9fe6-01fab2173b26.png)
 
instead they just appear as seperate projects in the projects tab and get deleted from the sub projects list after re-entering it through the project

this also happens for sub tasks

**Comment by nevos** [comment]
@chensabag bad description. AFYI, works as planned.
