### ISSUE TITLE
visual bug when selecting a past date in tasks and projects

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1134]
the error message isn't visible 

![image](https://user-images.githubusercontent.com/38312178/42759893-2d5a16b0-8911-11e8-96ad-9ed91bb4c2f5.png)

**Comment by nevos** [comment]
@chensabag please provide priority minor/medium/critical

**Comment by chensabag** [comment]
minor 
@nevos

**Comment by nevos** [comment]
@manmorc for 205/dev

**Comment by manmorc** [comment]
@nevos @chensabag  need a behavior to reproduce

**Comment by manmorc** [comment]
fixed develop/master
