### ISSUE TITLE
Unable to restore a deleted task 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1136]
after deleting a task, going to show deleted items, searching for the deleted task, and pressing on restore task, it isnt restored, and is still in the deleted list

**Comment by nevos** [comment]
Exception on
    function addToParent(entity) {
        return new Promise(function (resolve) {
            if (entity.parent) {
                getById(entity.parent).then(function (parent) {
                    parent.subTasks.push(entity);
                    update(parent);
                    return resolve();
                });
            } else {
                return resolve();
            }
        });
