### ISSUE TITLE
Open new folder from favorite didn't save the changes.

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1137]
Open a new folder form favorite folders.
Enter name and description.
Back to the all folders.
The changes didn't save.

**Comment by nevos** [comment]
@AviramAshkenazi not sure i understand or can reproduce.

**Comment by AviramAshkenazi** [comment]
if you open folder from folder filter by favorites and back to the all folders the changes didn't save and it's look like a empty folder.
