### ISSUE TITLE
Open new folder from office didn't save

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1138]
open a new office.
click on manage folder.
open a new folder.
enter name.
back to the all folders the didn't show up.
back to the office click on folders the name of the folder show up but by clicking on the manage folders the folder didn't show up.

**Comment by nevos** [comment]
@manmorc please test

**Comment by nevos** [comment]
@AviramAshkenazi the description is not clear.
"back to the all folders the didn't show up." ?
also - could not see any behavior problem.
cc @Dolevco closing as not reproducible.
