### ISSUE TITLE
Title does not show "tasks from projectname" when showing tasks from sub project

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#1143]
To reproduce.

1.  Create project
2. Create under it a subproject
3. Go to "manage tasks"
4.  The title should be "tasks from project XXX" and XXX does not show

<img width="1220" alt="icu" src="https://user-images.githubusercontent.com/245027/42778960-7f8b7344-8947-11e8-8421-a222829cbf6e.png">

**Comment by nevos** [comment]
@liorkesos not reproducible on master / http://root.204.projects.linnovate.net
closing
