### ISSUE TITLE
search - selected item disapears

### ISSUE THREAD

**Issue by nevos** [linnovate/root#1177]
1) when i search, and click on list pane item  - the is a display issue.
2)  when i'm not on a different menu item and use the search box to search, the item selection is not changing the url, and item isnt visible on detailspane

**Comment by manmorc** [comment]
@nevos it is related to dumped with removed entities elastic too, or not, but it helped to me

**Comment by nevos** [comment]
still seeing this happen when clicking on search result item / details pane

**Comment by nevos** [comment]
resolution on release/205

**Comment by manmorc** [comment]
https://github.com/linnovate/root/commit/958250e31feb9ee9d2f1735acd8b115c5a621bfe
