### ISSUE TITLE
"task from" translation

### ISSUE THREAD

**Issue by nevos** [linnovate/root#1180]
![image](https://user-images.githubusercontent.com/1281931/43251842-afbdaf8a-90c9-11e8-8524-ee50ac8e32c2.png)
translation in hebrew missing in 
"tasks from project"  <project name>
"tasks from discussion" <discussion name>..
"Discussions from Project" ....
"Projects from Discussion" ...

**Comment by manmorc** [comment]
@nevos none-reproducible,
on your screenshot there is 'eng' language active - it means that language was changed without restarting server
