### ISSUE TITLE
bulk translations

### ISSUE THREAD

**Issue by nevos** [linnovate/root#1182]
**Tooltip** 

bulk status:
עדכון סטטוס
bulk assignee:
עדכון אחראי
bulk due:
עדכון תאריך יעד
bulk tags:
עדכון תגיות
bulk delete:
מחיקה

**modal strings**

status dropdown input string should be like title:
בחר אחראי

assignTo:
should be 
title - "Assign" 
under it - 1 tasks
and in hebrew: 
title - בחר אחראי
and below below the number and entity type.

"Delete 1 tasks" should be 
title - Delete
below - 1 tasks
title - מחק
below the number and entity type.

**Comment by nevos** [comment]
Items selected (corner) - פריטים נבחרו
Select status (select dropdown) - בחר סטטוס 
Delete (modal)

**Comment by nevos** [comment]
templateDocs - translate entity name modal

**Comment by manmorc** [comment]
https://github.com/linnovate/root/commit/912b4cd18f0a1e3cbb668f19787afab1bf1d271f
