### ISSUE TITLE
client delete option send to wrong api

### ISSUE THREAD

**Issue by nevos** [linnovate/root#1186]
when using the delete option in templatedocs, office, folder - it deltes from mongo, instead of calling recycle api

**Comment by manmorc** [comment]
i see it is exactly coming to "recycled", but in models of folder, office, tempDoc there was no parameter as recycled, so it was problem to multiple update parameter that was no existed

**Comment by nevos** [comment]
still - calling this from details menu causes mongo delete (not recycle).
also - no unrecycle option for emplatedocs, office, folder

**Comment by nevos** [comment]
@manmorc fix in release branch 205

**Comment by manmorc** [comment]
https://github.com/linnovate/root/commit/4cab1cd89622e4e32ee3fd08ff383bcc4963f285
