### ISSUE TITLE
Not see ant entity of Active

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1196]
***Happens in every entity**
If the first 50 items are Non-Active. and the 51 item and so is Active, we will Not see it in filter of All -> Status Active :
![image](https://user-images.githubusercontent.com/17906421/43365130-95369938-9330-11e8-97a1-58fbba40d574.png)

But if we select filter status All we will see it after the first 50 items:
![image](https://user-images.githubusercontent.com/17906421/43365165-2428bee6-9331-11e8-9bfd-6ee6716e0c63.png)

**Comment by nevos** [comment]
@ohadetsion  - this bug appears in 203 - it is in production systems for a number of 3-4 month now
![image](https://user-images.githubusercontent.com/1281931/43366844-93b5cf40-934c-11e8-9e2d-de8868c30f13.png)
