### ISSUE TITLE
Multiple Select. tags didn't work

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1217]
@abrahamos 
in every entity open a few tasks/projects/discussions.
choose them by multiple select.
choose the tag.
fill the filed.
click on update.
the tags didn't add.

**Comment by abrahamos** [comment]
Currently filling a new tag field doesn't insert it to update, until you press `ENTER`.

This behavior needs to be changed, a user expects insert the tag by any `focusout`.

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/commit/1176e19e9b85d194c7bf103e478cc894853d9942
