### ISSUE TITLE
Document: can't upload a file from template until refresh.

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1229]
@abrahamos 
open a document.
choose office.
choose on create from template.
choose one file.
click on upload him.
the file didn't load until you refresh the site.
![temp](https://user-images.githubusercontent.com/31100069/44713710-62070180-aabc-11e8-96c6-0bb6a8ef8383.PNG)

**Comment by ohadetsion** [comment]
Not relevant
