### ISSUE TITLE
Document: can't upload file from choose file.

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1230]
@abrahamos 
open a document.
click on choose file.
choose a file.
the status bar stay on 100% and nothing happened.
if use refresh the page back to be a new document page.
![temp](https://user-images.githubusercontent.com/31100069/44713887-b9a56d00-aabc-11e8-91f7-37f3ee985da0.PNG)

**Comment by abrahamos** [comment]
I think that problem is caused by `ftp` module, the app is trying to connect to port 21 (ftp port).

@srayaAvraham, please check if you can help here.

Thanks
Avraham

**Comment by ohadetsion** [comment]
Not relevant
