### ISSUE TITLE
Document: filtering by favorite not working

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1233]
@abrahamos 
open a few documents. 
set one of them as a favorite.
click on filtering by favorite.
all the  documents still there.
![temp](https://user-images.githubusercontent.com/31100069/44717880-fece9c80-aac6-11e8-9911-e1002cf0cb29.PNG)

**Comment by abrahamos** [comment]
It actually doesn't **filter** by favorite, but **sort**, and it works as expected.
![sort_by_favorite](https://user-images.githubusercontent.com/17452685/44785543-ef6c5380-ab99-11e8-80d8-efa30ae64e28.png)

**Comment by ohadetsion** [comment]
@abrahamos It's not true... Until now the favorite was **filtering** and not **sorting**, in every entity.

**Comment by manmorc** [comment]
none-reproducible in master
