### ISSUE TITLE
Documents: filtering by  side bar status not working.

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1234]
@abrahamos 
open a new document.
filter by the side bar to some other status.
the document always there even though the status is new. 
![temp](https://user-images.githubusercontent.com/31100069/44719358-bcf42500-aacb-11e8-9e3e-5870dde7156a.PNG)

**Comment by chensabag** [comment]
@AviramAshkenazi cheak if this bug like bug  #1211

**Comment by AviramAshkenazi** [comment]
same as #1211
