### ISSUE TITLE
Documents: folder change after Filing.

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1236]
@abrahamos 
open a new document.
upload a doc.
click on fille.
the name of the folder disappear.
![temp](https://user-images.githubusercontent.com/31100069/44723343-5f1a0a00-aad8-11e8-9ee2-a7e31f4a6013.PNG)

**Comment by manmorc** [comment]
@AviramAshkenazi can't reproduce,
can you tell some more detail steps to reproduce this

**Comment by AviramAshkenazi** [comment]
@manmorc 
open a new document.
choose a folder with templateDoc.
choose one of the template.
after the template upload click on "File".
the name of the folder you added in the begin will disappear.
