### ISSUE TITLE
Discussions : status action button not working

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1242]
@abrahamos 
open new discussion.
fill the fields.
click on "Schedule discussion"/ "Send Summary" / "Archive Discussion" / "Cancel Discussion".
nothing happened.
![temp](https://user-images.githubusercontent.com/31100069/44771437-9ee1ff80-ab73-11e8-9d1f-f9a157582299.PNG)

**Comment by manmorc** [comment]
@AviramAshkenazi none-reproducible in master,
possibly fixed in https://github.com/linnovate/root/commit/b68fb383277c7ba2f23d943f05d039696731ac03
