### ISSUE TITLE
Tasks from Discussion: filtering by favorite not working

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1244]
@abrahamos 
open new discussion.
fill the fields.
go to tasks.
open a few tasks.
set one of them as favorite.
click on filtering by favorite.
all the tasks still there.
![temp](https://user-images.githubusercontent.com/31100069/44773505-70ffb980-ab79-11e8-82f7-a33f0a5793f0.PNG)

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/commit/e614a962898eb13389a4d3fe58ab728a27cfc548
