### ISSUE TITLE
 Tasks from Project: filtering by favorite not working

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1245]
@abrahamos
open new project.
fill the fields.
go to tasks.
open a few tasks.
set one of them as favorite.
click on filtering by favorite.
all the tasks still there.
![temp](https://user-images.githubusercontent.com/31100069/44773737-fe430e00-ab79-11e8-956d-63b135a7e8e2.PNG)

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/commit/e614a962898eb13389a4d3fe58ab728a27cfc548
