### ISSUE TITLE
Offices: promises bug

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1257]
@abrahamos 
open new office.
fill the fields.
set your friend as viewer/commenter.
connect as your friend.
go to folders.
1)you can manage folders.
go to signatures.
2)you can manage signatures.

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/commit/dbe5a3d9fe85912ecc1455e8e6ce72dc65bb3029
