### ISSUE TITLE
Filtering by favorite in task from discussions not working 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1264]
@abrahamos 
open new discussion.
fill the fields.
 go to tasks fill.
click on manage tasks.
open some task.
click on favorite.
the all tasks still show up.
![temp](https://user-images.githubusercontent.com/31100069/45020501-d51df400-b037-11e8-8fb7-380ab6ba4d1b.PNG)

**Comment by abrahamos** [comment]
The favorite button **sorts** items, but doesn't **filter** out items not favorite.
