### ISSUE TITLE
Protect file from being deleted by a user without permission

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1265]
### File protections
|Permission|Upload file|Delete self-uploaded file|Delete file|
|:--       |:--        |:--                      |:--        |
|Viewer    |X          |X                        |X          |
|Commenter |V          |V                        |X          |
|Editor    |V          |V                        |V          |

### Log event
In addition to the protection feature, make sure to log an event every time a file is deleted.

**Comment by abrahamos** [comment]
Server side checks are required too.

**Comment by manmorc** [comment]
added in https://github.com/linnovate/root/commit/b4c8a21c6a31d190fee7c70dddc36002aa94cd4c
