### ISSUE TITLE
After deleting a document, the document isnt deleted until changing to another tab (updates/tasks/etc) 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1272]
@abrahamos, after deleting the document, it still stays until changing the tab or refreshing the page 

the document that i had just deleted is still there, and is still interactable
![image](https://user-images.githubusercontent.com/38312178/45090995-9738d280-b100-11e8-95c1-77dd9b9409c8.png)

**Comment by yaronmir** [comment]
re- opened cause this bug still exists @abrahamos

**Comment by manmorc** [comment]
@yaronmir i cant reproduce it, please write your steps
