### ISSUE TITLE
INBOX - new feature

### ISSUE THREAD

**Issue by abrahamos** [linnovate/root#1283]
### Client side implementation
See [design](https://projects.invisionapp.com/d/main#/console/4253876/306377340/preview).

### Subscription
A user will be able to subscribe/unsubscribe from being notified of events per entity - this will be done by a new array of subscribed watchers per entity.

### Events
List of events types to be included in INBOX:
1. Watcher was added/removed - **Don't notify for permission changes**
1. Due date / deadline was set/changed
1. Assignee set/changed/removed
1. Comment was added / edited
1. Attached / deleted a file (attachment)
1. Entity was deleted
1. Status was changed
1. Location set/removed/changed - _Only relevant on discussion_

> **NOTE**: There is already a `updates` collection for updates displayed in entity details pane, use it for inbox too.

**Comment by manmorc** [comment]
in master
