### ISSUE TITLE
OfficeDocuments don't load until the end in folders

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1293]
In OfficeDocuments from folder, it's not load after the first 25 items:

![image](https://user-images.githubusercontent.com/17906421/45817745-5f2cb480-bce8-11e8-8d29-19f7be533614.png)

But after i click on "create new item" the list load the next item one at the time:
![image](https://user-images.githubusercontent.com/17906421/45817907-d104fe00-bce8-11e8-91d8-c2cab49739a6.png)

**Comment by manmorc** [comment]
@ohadetsion  none-reproducible in current master version

**Comment by ohadetsion** [comment]
@manmorc  Did you notice that all the items are not active ?

**Comment by manmorc** [comment]
@ohadetsion right! i see this now, thank you.
