### ISSUE TITLE
Create new document from button NOT works

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#1300]
If i click on the plus button on the header, and click on new document, it's not work....

![image](https://user-images.githubusercontent.com/17906421/46580063-fb172980-ca25-11e8-9e65-5dfbd98f6c8c.png)

**Comment by manmorc** [comment]
@abrahamos none-reproducible in master

**Comment by ohadetsion** [comment]
@manmorc Did you try with more then 25 officedocuments and then click on this button ?

**Comment by manmorc** [comment]
@ohadetsion yes, new document creates in the bottom of the list

**Comment by ohadetsion** [comment]
@manmorc Yes, you right.
I mean that the focus (the detailspane) isn't on the new one, if you check that "task" button it's work fine (the focus is on the new task)
