### ISSUE TITLE
when in tasks, projects, discussions or folders tab, after changing the first entity's status on the list to one that will make it inactive, after refreshing the page, the entity's template is still on the inactive entity

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1306]
@abrahamos, in one of the entities listed in the title, if you change the status of the first entity on the list to a status that will make it inactive, after refreshing the page, the archived entity's template would still show in the left side of the screen, even though its not on the list anymore in the default "active" filter 

Whats expected to happen instead is that after refreshing the page, the entity template part will be empty, until you click on another entity that's on the list

**Comment by abrahamos** [comment]
@yaronmir, The title/description are not clear at all!
You mentioned that after changing it to be "inactive", it's still "inactive", what is unexpected here???
I signed a task as `rejected`, and it was moved to "archived" list. even after refreshing the page.
I signed the same task back with `new` status, and it moved back to "active" list.

You have to describe your issues clear enough for a stupid man like me to understand, and please provide a title and description appropriately.
A title is not for the entire description, and shouldn't expand multiple lines.

**Comment by yaronmir** [comment]
@abrahamos, in one of the entities listed in the title, if you change the status of the first entity on the list to a status that will make it inactive, after refreshing the page, the archived entity's template would still show in the left side of the screen, even though its not on the list anymore.

Whats expected to happen instead is that after refreshing the page, the entity template part will be empty, until you click on another entity
