### ISSUE TITLE
Tasks property inheritance

### ISSUE THREAD

**Issue by abrahamos** [linnovate/root#1307]
When a user creates a task from a project, automatically inherit the following properties from the parent project:
- `watchers`
- `permissions`

**Comment by abrahamos** [comment]
First, currently this is not working when you create a new task from "Tasks from Project" filter.

Second, we need this feature also when a user set a project for a previously created task.
By setting a project, the task watchers/permissions will be overwritten with the project watchers/permissions.

**Comment by artem123456123** [comment]
made "create task" from details tab and dropdown menu work  5615e99   
working on second part

**Comment by artem123456123** [comment]
@abrahamos  added watchers and permissions when a user set a project for a previously created task.  
then i go to 'projects'  
![screenshot from 2018-12-03 13-15-46](https://user-images.githubusercontent.com/43031140/49367683-d1b10c00-f6fd-11e8-81cc-b6fad6fe6c03.png)  
add watcher  
![screenshot from 2018-12-03 13-16-40](https://user-images.githubusercontent.com/43031140/49367706-decdfb00-f6fd-11e8-9aa0-cc04c82a82e0.png)  
go to tasks again - watchers are the same as before. shoud watchers be updated for this case ?

**Comment by abrahamos** [comment]
Good question.
No. You shouldn't update the task.
