### ISSUE TITLE
delete tags that related to deleted folder

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1322]
press on settings
crate a new folder and call it 101 
press on documents
crate a new item and call it TEST_101 
press on "choose folder" and select 101 folder
(the document is connected to 101 folder )
 press on settings again 
delete the the 101 folder 
it shows that the document still connected to deleted folder (101)

**Comment by manmorc** [comment]
Hello @YehudaMorad , thank you for Hebrew message!

**Comment by YehudaMorad** [comment]
Hi @manmorc I hope it's OK now.

**Comment by abrahamos** [comment]
We need an exact expectation for such a case.
This is not a bug, but some undefined case which was not designed.

**Comment by chensabag** [comment]
This case also repeats itself in the connection between tasks and projects.

**Comment by chensabag** [comment]
@abrahamos 
show at prd 206 section 6

**Comment by chensabag** [comment]
When you delete entities - all their relationships will be deleted.
Only the relationships will be erased, not the entities themselves.
For example:
When a project is linked to tasks, and we delete the project, the tasks associated to that project aren't deleted. Only the relationship itself was deleted.

**Comment by abrahamos** [comment]
Fixed by 0db861eb900c5b70b210e08368100db026c5ba6e

**Comment by AviramAshkenazi** [comment]
fix
