### ISSUE TITLE
documents, projects,tasks update field bug when updating an assignee

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1324]
when choosing yourself as an assignee, and then choosing someone else instead the following update is written in the updates field : 

אחראי קודם שייך את אחראי חדש במקום לישות

**Comment by manmorc** [comment]
@yaronmir need little bit more description what should be and additional good English translation for the message

**Comment by yaronmir** [comment]
Instead of "new assignee" was assigned by "user" it says, "user" was assigned by "new assignee"
