### ISSUE TITLE
update field text bug in every entity

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1328]
- [x] when changing an entity's color(projects, folders and offices) it writes the colors as their RGB code
![image](https://user-images.githubusercontent.com/38312178/48672271-95e24800-eb3c-11e8-9971-0e39b54eab93.png)

- [x] when selecting the "no  select " option when un-assigning a user to an entity it describes it like so: 
![image](https://user-images.githubusercontent.com/38312178/49871559-3d425a00-fe1f-11e8-9a26-c59f738ed122.png)
when it should be "user" unassigned this"

**Comment by yaronmir** [comment]
the issues still exist @manmorc

**Comment by AviramAshkenazi** [comment]
still happens

**Comment by AvrahamO** [comment]
Need to remove all color activities
See https://github.com/linnovate/root/commit/6f75f2f44c19eaa2f3453c55528c59e09b162605#diff-6e3d661f02bd80d01d74a4951b4ef027

**Comment by AviramAshkenazi** [comment]
fix only the color update.

**Comment by manmorc** [comment]
@yaronmir now message is: "(someone) unassigned (someone)",
example: "user1@mail.ru unassigned user2@mail.ru",
need more description what is wrong

**Comment by AviramAshkenazi** [comment]
fix
