### ISSUE TITLE
multiple selection assignee & viewer bug in every entity

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1329]
when adding an assignee or a viewer to an entity with the multiple selection there's an extra blank assignee on the list that can be selected: 
![image](https://user-images.githubusercontent.com/38312178/48672500-59fcb200-eb3f-11e8-996a-c73d7b511e3c.png)

**Comment by abrahamos** [comment]
Couldn't reproduce

**Comment by yaronmir** [comment]
still exists
