### ISSUE TITLE
Incorrect presentation of connected folder

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1331]
![image](https://user-images.githubusercontent.com/40392773/48673714-042f0680-eb4d-11e8-9873-353bb805ce0d.png)
**related to bag #1328**  
 press on settings 
create a new folder and call it 100
go to left bar and double click on title.
press on one  or many of the edit option. 
press on documents and create a new document.
click on choose folder and select the 100 folder 
the 100 folder appear at line document incorrectly

**Comment by manmorc** [comment]
@YehudaMorad ready for testing again!
