### ISSUE TITLE
The serial button doesn't work 

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1332]
press on documents and create a new document
go to the left bar and click on serial
the button doesnt work.

**Comment by manmorc** [comment]
@YehudaMorad to see results we must create an office, add office into folder, and then choose office, then choose folder, and we will see the "officeDocuments" that related

**Comment by YehudaMorad** [comment]
![image](https://user-images.githubusercontent.com/40392773/48709183-6e0ee500-ec0d-11e8-8227-9bf6f9154353.png)
I meant the button that was marked

**Comment by chensabag** [comment]
@YehudaMorad  Did you upload a file?

**Comment by abrahamos** [comment]
This issue is involved with SharePoint connection.
We cannot solve that without having the right environment.

**Comment by AviramAshkenazi** [comment]
share point problem
