### ISSUE TITLE
results still appear in search resulrts Even though the words were erased 

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1338]
press on documents and open a new document and call it "100"
go to search and search the keyword "100"
1 result should be appear 
delete the keyword 
the results still appear
![image](https://user-images.githubusercontent.com/40392773/48713498-1b3b2a80-ec19-11e8-9320-b696e7a81722.png)

**Comment by abrahamos** [comment]
Fixed, please test again

**Comment by yaronmir** [comment]
Still happening
