### ISSUE TITLE
deleted documents still appear 

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1339]
press on documents and create new documents 
go to the left bar and click on the button with 3 points.
click on delete doc 
the document still appear/
you need to refresh the site to see that the doc is deleted.

**Comment by abrahamos** [comment]
Similar to #1336
Cannot reproduce. Documents is deleted form the list as expected.

**Comment by chensabag** [comment]
like #1336 the items deleted from the list just after refresh the page
