### ISSUE TITLE
plus menu, creating a project 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1342]
when trying to create a project using the plus menu, instead of creating a project at the end of the list, it instead jumps to the first project on the list

**Comment by abrahamos** [comment]
I cannot reproduce it.
I Opened a project as described, and it opens a new one right in the bottom of the list, as expected.
Please test against latest master branch.

**Comment by chensabag** [comment]
![image](https://user-images.githubusercontent.com/25196313/49373231-ebeee800-f705-11e8-8d55-325b3269cde7.png)
when your project's list longer then your screen the new project created and at the left side of the screen you can make change but you can't see the new project at the list

**Comment by manmorc** [comment]
@chensabag sure, it's still in development

**Comment by manmorc** [comment]
@chensabag its ready for testing!

**Comment by AviramAshkenazi** [comment]
still happened.
and also in Document.

**Comment by manmorc** [comment]
@AviramAshkenazi @abrahamos  not reproducible in current master branch

**Comment by AviramAshkenazi** [comment]
still happens every entity:
in tasks:
![image](https://user-images.githubusercontent.com/31100069/50475134-452bfd80-09cc-11e9-8b81-6a1e39f68a9f.png)
in projects:
![image](https://user-images.githubusercontent.com/31100069/50475206-86bca880-09cc-11e9-8983-8fa2593e9733.png)
in meetings:
![image](https://user-images.githubusercontent.com/31100069/50475305-ef0b8a00-09cc-11e9-8472-08ac78be3b60.png)
in documents:
![image](https://user-images.githubusercontent.com/31100069/50475260-c1264580-09cc-11e9-8ee3-c880850e171d.png)
