### ISSUE TITLE
in documents, the updates field disappears when changing tabs from it 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1343]
in documents, after changing tabs from the updates field to the documents or tasks tab, or when favoriting the document, the updates disappear
![image](https://user-images.githubusercontent.com/38312178/48778158-25bef800-ecdd-11e8-85b3-98a319516149.png)

**Comment by abrahamos** [comment]
I see the updates are reloaded, but don't disappear.
Please test again

**Comment by chensabag** [comment]
I cheaked it again, the updates indeed disappear
