### ISSUE TITLE
in documents, when adding a file to the document or when updating the doc, the update box disappears

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1344]
in documents, when adding a file to the document or when updating the doc, the update box goes down and disappears bit by bit 
![image](https://user-images.githubusercontent.com/38312178/48778331-91a16080-ecdd-11e8-81a9-42bb6d969bee.png)

**Comment by chensabag** [comment]
you need to refresh the page to see it

**Comment by yaronmir** [comment]
when adding a file to a document, you cant access its preview or download it,and after changng to a different document or entity or after refreshing the page, the entire updates tab dissappears

before refresh: 
![image](https://user-images.githubusercontent.com/38312178/49731114-f0298100-fc82-11e8-9a8a-463593b64d58.png)

after refresh:
![image](https://user-images.githubusercontent.com/38312178/49731130-033c5100-fc83-11e8-980f-12673d85a5cd.png)
