### ISSUE TITLE
plus menu document creation bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1346]
when creating a document using the plus menu, the tab on the right stays on the last tab it was in instead of going to the documents tab (visual bug )

For example here it stays in the task tab instead of going to the document test 
![image](https://user-images.githubusercontent.com/38312178/48778901-117bfa80-ecdf-11e8-8e4e-30323bad26d3.png)

**Comment by abrahamos** [comment]
Fixed, please test again

**Comment by yaronmir** [comment]
its still happening
