### ISSUE TITLE
when inspecting a file, it doesnt fit the screen

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1348]
when inspecting a file(preview), it doesnt fit the screen
![image](https://user-images.githubusercontent.com/38312178/48780556-e1cef180-ece2-11e8-9c3d-a032457c29f0.png)

**Comment by abrahamos** [comment]
What is expected?

**Comment by AviramAshkenazi** [comment]
@abrahamos 
expected to see the preview of the document.

**Comment by abrahamos** [comment]
I encounter some `ftp` errors.
@ohadetsion, please provide us with the ftp configuration or any other environment which we have to establish in order to share the same environment as the production
