### ISSUE TITLE
Tasks-filters by date not working

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1352]
when I choose date for tasks and go to "my task" (home page).
Tasks for today/this week - not show.s
The date shown just in the tasks.
![image](https://user-images.githubusercontent.com/40392773/48782545-1a70ca00-ece7-11e8-9019-f268d9a6240f.png)

![image](https://user-images.githubusercontent.com/40392773/48782595-33797b00-ece7-11e8-8835-665ba52d732b.png)

**Comment by manmorc** [comment]
@YehudaMorad it seems to work for me, can you please write steps to reproduce,
notice, that to see tasks in "my tasks" you need to be assigned - for "tasks due today/this week/overdue"or watched to "watched tasks"

**Comment by yaronmir** [comment]
The steps  to reproduce are as follows : 
press on ICU 
press on "tasks that im currently following"
after pressing it should show no tasks in the list

**Comment by chensabag** [comment]
You're right
