### ISSUE TITLE
Delete marked object 

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1353]
the screenshot unnecessary

![image](https://user-images.githubusercontent.com/40392773/48783100-4a6c9d00-ece8-11e8-8f22-bb1c63b97cab.png)

**Comment by chensabag** [comment]
At the search show deleted Items, and under that existing names of discussions, folders and offices that related to results of the search.
The objects were not characterized, and in addition they aren't clickable.
Therefore they are unnecessary and should be deleted.

**Comment by yaronmir** [comment]
still exists 
![image](https://user-images.githubusercontent.com/38312178/49788382-e27f0480-fd31-11e8-989c-ab39a4fb7133.png)
