### ISSUE TITLE
Remove task parent of a document

### ISSUE THREAD

**Issue by abrahamos** [linnovate/root#1354]
Documents to tasks are a "many to many" relationship.
Therefore, we don't need the button of "parent task" in document details pane.

In the following screenshot, the right connection is marked by a circle, (already implemented), remove the X.
![screenshot from 2018-11-21 13-12-29](https://user-images.githubusercontent.com/17452685/48837981-a0e0e680-ed8f-11e8-9074-24f631978408.png)

For more details, see #1261

**Comment by yaronmir** [comment]
still exists 
![image](https://user-images.githubusercontent.com/38312178/49788462-178b5700-fd32-11e8-917d-27d33c85c53c.png)
