### ISSUE TITLE
push notifications dont work 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1358]
in a task that i was assigned to, a user changed something in it while i was in another tab, and i didnt see any notification pop up about the change

**Comment by abrahamos** [comment]
Try the following:
1. Make sure notifications are allowed - open chrome://settings/content and search "Nofitications" settings.
Also, notice that notifications are not allowed in incognito mode.
1. Notifications will popup only for the following changes: status, due date, comment or assignee (the new assignee will get the notification), so try to make changes for this specific fields.

**Comment by chensabag** [comment]
I'm allowed notification and them pop up
