### ISSUE TITLE
'/login' route doesn't work the same as '/' - cant login

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1362]
try to navigate to login page by url.
end the roue with /login.
fill the fields.
click on login.
nothing happens.

**Comment by manmorc** [comment]
@AviramAshkenazi can't reproduce, do you have any console errors? what is your cookie?

**Comment by AviramAshkenazi** [comment]
@manmorc 
console log:
![image](https://user-images.githubusercontent.com/31100069/49065991-60b6b380-f228-11e8-94ea-315ff7062aff.png)
without cookies.

**Comment by manmorc** [comment]
@AviramAshkenazi this may be a local issue, can you show me in appear.in?
http://www.appear.in/root

**Comment by abrahamos** [comment]
This bug is caused by automation testing via cypress.
Please provide the code that caused this problem in order to let us fix that.

**Comment by AviramAshkenazi** [comment]
`const email = "QA@email.com";
const password = "password";

/**
 *Login function to connect to Root
 * @param {string} email the user`s email
 * @param {string} password the user`s password
 */
function login(email,password){
    
    cy.get(':nth-child(2) > .form-control').type(email)
    cy.get(':nth-child(3) > .form-control').type(password)

    cy.get('button.btn').click()
}

describe("Login User",()=>{
    it("Go to root site",()=>{
        cy.visit('/login');
    })
    
})`
that's only part of the code.
with only writing: cy.visit('/');
it works fine.

**Comment by AviramAshkenazi** [comment]
work fine.
