### ISSUE TITLE
strip html tags

### ISSUE THREAD

**Issue by artem123456123** [linnovate/root#1381]
convert "div>{{ variable_name }}</div"  
to  
"div ng-bind-html="variable_name"></div"
  
list of files  https://docs.google.com/spreadsheets/d/1-EeyOKK9vfBBD9a_jqhwFpUnLXcBKnuDSQdLz87rCWI/edit?usp=sharing

**Comment by abrahamos** [comment]
HTML tags may appear only in a entity `title` or `description`, so there is no need to change everything else.

Also note that not all the problem can be solved by `ng-bind-html`.
Consider the tooltip text in the following screenshot
![screenshot from 2018-12-11 12-33-48](https://user-images.githubusercontent.com/17452685/49794834-304f3900-fd41-11e8-99cf-cfff829fa1ec.png)

**Comment by abrahamos** [comment]
Done by c70a17e245e3df82b04dd4665dd7d68b6f143151
