### ISSUE TITLE
Multiple select design

### ISSUE THREAD

**Issue by abrahamos** [linnovate/root#1386]
See [Designer comments](https://www.figma.com/file/WAzV0Oq760o2fo2g0NAuWZAw/ICU?node-id=4679%3A13109) on multiple select modals

**Comment by YehuditGrinwald** [comment]
The lines background seems like the design.

**Comment by abrahamos** [comment]
This line is regarding the **checkbox** background
![image](https://user-images.githubusercontent.com/17452685/50548027-83385400-0c4e-11e9-838f-a397bd00a6e5.png)
Please fix this too.

**Comment by abrahamos** [comment]
Fixed by #1440
