### ISSUE TITLE
in a task or project that is assigned to a different user, when trying to open a sub entity for the first time, it opens it so creating a sub entity is impossible 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1389]
in a task or project that is assigned to a different user, when trying to open a sub entity for the first time, it opens it so creating a sub entity is impossible 
![image](https://user-images.githubusercontent.com/38312178/49727234-62e12f00-fc78-11e8-810d-b5d9167cdbe7.png)

**Comment by abrahamos** [comment]
I don't understand.
I tested sub entity for tasks/projects assigned to another user, I don't see any problem.
