### ISSUE TITLE
updates field moves downwards when adding a couple of sub tasks/projects

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1392]
after adding some sub task\projects, the updates filed gets shoved down to the point where the document adding button  and the add button, as well as the updates field itself is unusable

![image](https://user-images.githubusercontent.com/38312178/49728645-0253f100-fc7c-11e8-8f2c-6617a4b83706.png)

**Comment by yaronmir** [comment]
@abrahamos @LiorHaim why did you remove the 2.0.6 tag if the bug still happens?

**Comment by israelfrank** [comment]
@AvrahamO happened also in meetings
