### ISSUE TITLE
muliple select in search when selecting everything, it says that only one is chosen

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1396]
muliple select in search when selecting everything, it says that only one is chosen, and when you try to update something like a status it only updates it for the first entity that you uses to go into multiple selection with 
![image](https://user-images.githubusercontent.com/38312178/49734400-d2611980-fc8c-11e8-9538-1f35c660f37e.png)

**Comment by manmorc** [comment]
the same as https://github.com/linnovate/root/issues/1425 ,
fixed in https://github.com/linnovate/root/pull/1449
