### ISSUE TITLE
deleted entities multiple select bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1397]
when selecting the all option in multiple select mode, it selects only the one that was used to enter the mode in the first place and after uncheking one of the deleted items, the item gets deleted from the list until refreshing the page.
in addition, you cant add watchers in select all mode.

like #1396 

![image](https://user-images.githubusercontent.com/38312178/50156437-8428c780-02d7-11e9-8dd9-5fab29cc9c6b.png)

**Comment by yaronmir** [comment]
updated to fit the current version

**Comment by yaronmir** [comment]
like #1260

**Comment by manmorc** [comment]
the same as #1425
