### ISSUE TITLE
doc templates updates field 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1400]
no updates field is shown

- [ ] updates field isnt updated after changing something in the doc template(title, adding a document, description...)
example: added a title to the doc template
![image](https://user-images.githubusercontent.com/38312178/54362337-6cac7100-4671-11e9-91c7-94425d545641.png)

- [ ] add button doesnt work so you cant add comments to the doc template

**Comment by yaronmir** [comment]
@LiorHaim @liorkesos

**Comment by yaronmir** [comment]
@AvrahamO edited the issue description to be more understandable

**Comment by AviramAshkenazi** [comment]
update only from update field.

**Comment by AvrahamO** [comment]
Updates regarding any changes didn't work even in 2.0.5, so it will not be fixed in the current cycle.
