### ISSUE TITLE
Remove unimportant activities

### ISSUE THREAD

**Issue by AvrahamO** [linnovate/root#1407]
Prevent the following activities
1. Updates for html tags changes in title / description
1. Updates for color changes

Also, make sure that something has been changed before creating an update

**Comment by yaronmir** [comment]
LIKE #1328

**Comment by abrahamos** [comment]
It's not the same at all

**Comment by manmorc** [comment]
@abrahamos fixed in https://github.com/linnovate/root/pull/1446

**Comment by AviramAshkenazi** [comment]
still happens.
the tooltip is with html tags.
