### ISSUE TITLE
search results of tasks don't appear 

### ISSUE THREAD

**Issue by chensabag** [linnovate/root#1410]
I wrote the same name in each of the options (tasks, projects, discussions and documents).
All entities except the tasks appeared in the search results.

![image](https://user-images.githubusercontent.com/25196313/49858927-ec226e00-fdfe-11e8-8e81-9da42c26277c.png)

**Comment by yaronmir** [comment]
@AvrahamO this issue where you can find any entity except for tasks in search happens again
