### ISSUE TITLE
documents tab, office documents from tasks bugs

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1412]
when theres an office document in a task and you try to access it through the documents tab -> office documents from tasks tab it shows the document for a split second and then disappears
when you dont have an office document in a task, it just doesnt show a list of documents you can create 
![image](https://user-images.githubusercontent.com/38312178/49867332-d74fd580-fe12-11e8-99f5-102456b38dcf.png)

but when you access the tab using tasks-> documents->manage documents its shows it just fine

in addition, when you  click on a document from task from the list it shows the previous document that you used before clicking this one
in this example i clicked on "rerewsrewsrs" before clicking on "dagfdshgdsh"
![image](https://user-images.githubusercontent.com/38312178/49867491-60670c80-fe13-11e8-9fd1-f392b9a99249.png)

**Comment by manmorc** [comment]
related to many-to-many tasks-officeDocuments relations,
fixed in https://github.com/linnovate/root/pull/1455

**Comment by yaronmir** [comment]
still happens
