### ISSUE TITLE
documents signatures dont get saved when selected 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1413]
when you go to a document, and select a signature from the ones on the list, and press the pen button, 
after switching tabs , refreshing the page or going to another document and back, the signature doesnt get saved  
before refresh 
![image](https://user-images.githubusercontent.com/38312178/49869828-47158e80-fe1a-11e8-9e21-4fd953fca0ba.png)
 after refresh 
![image](https://user-images.githubusercontent.com/38312178/49869855-5bf22200-fe1a-11e8-8210-ba7b51c4565b.png)

**Comment by chensabag** [comment]
![image](https://user-images.githubusercontent.com/25196313/50217933-e98dbe80-0392-11e9-888a-6dc820a68d06.png)
