### ISSUE TITLE
my tasks visual bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1421]
when clicking on "my tasks" the title of the list shows up as tasks from my instead of my tasks as tasks from my instead of my tasks 
![image](https://user-images.githubusercontent.com/38312178/49920802-33b70180-feb4-11e8-93bc-bea9eb5860c9.png)

**Comment by AviramAshkenazi** [comment]
@AvrahamO

**Comment by oronbh** [comment]
Was in 2.0.5 - Please remove 2.0.6 label
Its up to you to decide if you want it in 2.0.7 @AviramAshkenazi 
@yaronmir
