### ISSUE TITLE
multiple selection in every entity select everything bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1425]
when you press "select everything" in an entity, and try to update , it selects only the first entity in the list, and only updates that one
![image](https://user-images.githubusercontent.com/38312178/49934509-3b3bd200-fed7-11e8-9c03-4f8e035a466f.png)

after opening atleast 60 entities, it only selects a few out of the list instead of all of them
![image](https://user-images.githubusercontent.com/38312178/49934533-4ee73880-fed7-11e8-8ddd-0e82c5a5727a.png)

**Comment by abrahamos** [comment]
Around same area of #1397

**Comment by yaronmir** [comment]
still happens
