### ISSUE TITLE
Add support for server side sorting

### ISSUE THREAD

**Issue by AvrahamO** [linnovate/root#1430]
**Currently**
When you toggle the sort button asc/desc arrow, it only toggles the already loaded entities
**Expected**
Toggle the arrow will cause a reload of entities
![screenshot from 2018-12-17 10-27-06](https://user-images.githubusercontent.com/17452685/50075036-70e9ff00-01e6-11e9-93d1-7d7933d0ae3b.png)

**Comment by artem123456123** [comment]
@abrahamos now filters support sort on server side, but now items change direction after every action with filter: both press on arrow and select. Continue working
