### ISSUE TITLE
office documents from tasks bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1435]
after creating a task, and then going to the documents tab, clicking on manage documents

create new item doesnt update the list, and after editing the document it isnt saved after refreshing the page

![image](https://user-images.githubusercontent.com/38312178/50145494-65680800-02ba-11e9-96ac-36338e64ced9.png)

**Comment by abrahamos** [comment]
Around same area of #1412

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/pull/1455

**Comment by yaronmir** [comment]
still happens
