### ISSUE TITLE
partners permission bugs in different entities

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1436]
### tasks : after creating a sub task for a task that has a partner other than the creator and an assignee, setting the partner in the main task to editor/commentor, the role isnt saved in the sub task and instead shows the partner as a viewer .

in the main task
![image](https://user-images.githubusercontent.com/38312178/50145821-15d60c00-02bb-11e9-809c-51ce267bc6e2.png)

in the sub task:
![image](https://user-images.githubusercontent.com/38312178/50145790-fd65f180-02ba-11e9-9f3f-66a1b4e6317a.png)

### **projects:** in the sub tasks after adding a partner to the main project, the partner doesnt show up in the sub task.
in the main project in a task from the tasks sub tab, the partner doesnt show up as well.

in the main project
![image](https://user-images.githubusercontent.com/38312178/50146252-01deda00-02bc-11e9-9850-a1c91c1eb0af.png)

in the tasks tab/ sub projects 
![image](https://user-images.githubusercontent.com/38312178/50146208-ebd11980-02bb-11e9-9825-608589d45ae7.png)

### **offices**: after adding a partner with commenter or editor roles to the office and then entering the folders tab from manage folders, the partners added are shown in the folder but with viewer roles

**Comment by AviramAshkenazi** [comment]
bug only in offices
