### ISSUE TITLE
can't see document that upload from templatedoc

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1439]
upload new document in templateDoc.
select a folder.
open new document.
select the folder you add to the templateDoc.
choose the templateDoc you uploaded.
click on the doc.
get error that the file isn't exist.
also try to open the file in the templateDoc.
get error that the file isn't exist.

**Comment by AviramAshkenazi** [comment]
![image](https://user-images.githubusercontent.com/31100069/50288652-35ae3100-046f-11e9-9b0c-236b5559ec43.png)

**Comment by yaronmir** [comment]
@liorkesos @LiorHaim why did you remove the 2.0.6 if the bug still exists?

**Comment by AviramAshkenazi** [comment]
ftp error
