### ISSUE TITLE
HTML tags

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1444]
we see HTML tags when entering the printing screen.
![image](https://user-images.githubusercontent.com/38312178/50162233-7cbcea80-02e6-11e9-8c4a-8816133ec2b3.png)

also sometimes when hovering over a entity's name in every list
![image](https://user-images.githubusercontent.com/38312178/50162274-9bbb7c80-02e6-11e9-8066-45df4fcdef7a.png)

**Comment by AviramAshkenazi** [comment]
fix  2.0.7

**Comment by YehudaMorad** [comment]
it also happen when you change the name of the template document after upload file
![image](https://user-images.githubusercontent.com/40392773/52208160-53e9b800-2888-11e9-858a-016903e9bcf5.png)
