### ISSUE TITLE
Need to click twice to open the tasks filtering in my tasks page 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1448]
open a few tasks with different names. 
click on ICU.
click on some filter(tasks due today, tasks due this week. watched tasks or overdue tasks).
in the first time nothing shows up in the list.
in the second time the tasks show up.

**Comment by yaronmir** [comment]
![image](https://user-images.githubusercontent.com/38312178/50212141-f86c7500-0382-11e9-8104-a239054f2099.png)

**Comment by yaronmir** [comment]
the problem still exists in the "tasks due today, tasks due this week"

**Comment by AvrahamO** [comment]
Fixed again e6e470ebccf4cdf6e010651ac61f28e5cb634836
