### ISSUE TITLE
Main menu ICU button bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1458]
when entering the app for the first time or when moving to another tab and pressing on ICU once, instead of loading this screen : 
![image](https://user-images.githubusercontent.com/38312178/50382068-7f7d5e00-069f-11e9-97be-da2c564aeac5.png)
it instead loads the first tasks in the my tasks tab, until you press the ICU main menu button again:
![image](https://user-images.githubusercontent.com/38312178/50382081-b6537400-069f-11e9-9562-58050ebd6f58.png)

**Comment by chensabag** [comment]
![image](https://user-images.githubusercontent.com/25196313/50421354-ed17be80-0846-11e9-9975-0ddfff6ab3c7.png)

**Comment by abrahamos** [comment]
I managed to reproduce it on chromium 44, and it's now fixed by eece82636e6de57cf41293f6d0f6135ad02c2425
