### ISSUE TITLE
Multiple select problem loading in every entity  

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1459]
in every entity not all the items include in the multiple select. 
![image](https://user-images.githubusercontent.com/31100069/50382520-2830bb00-06aa-11e9-93b3-6b4895d30575.png)

**Comment by AviramAshkenazi** [comment]
when you use multiple select it's choose only the item's that are visible.
click on one item and select all item's.
it's select only the item's who visible and didn't load all item's.
before loading all item's:
![image](https://user-images.githubusercontent.com/31100069/50547448-41a1ac00-0c42-11e9-9ce6-8985a6e6dd8f.png)

after loading all item's:
![image](https://user-images.githubusercontent.com/31100069/50547456-6e55c380-0c42-11e9-8ad5-f0607fc23aa7.png)

**Comment by AviramAshkenazi** [comment]
@LiorHaim @liorkesos

**Comment by LiorHaim** [comment]
The bug still exists. The QA found it during the testing. Kesos why did you remove the 206 label and left it without any label?

**Comment by oronbh** [comment]
@LiorHaim @AviramAshkenazi @yaronmir 
Its exist already in 2.0.5 - please remove 2.0.6 label.
we can deal with it in 2.0.7 If needed , its up to you to prioritize. (if so please add the label 2.0.7)
