### ISSUE TITLE
Can't reset profile picture

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1460]
open the profile page.
click on replace.
pick some picture.
click on reset.
the picture still stay as the one you replace.
![image](https://user-images.githubusercontent.com/31100069/50400311-6f907780-078e-11e9-9f9b-501dd292811e.png)

**Comment by abrahamos** [comment]
Couldn't reproduce.
Successfully replaced twice my profile picture.

**Comment by chensabag** [comment]
![image](https://user-images.githubusercontent.com/25196313/50419498-bc7d5800-0839-11e9-8867-2da3cbf5159e.png)
