### ISSUE TITLE
in every entity, selcting no assignee update bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1464]
after creating a new entity, and selecting the no select option in the assigne bar , it shows this message in the update field 

![image](https://user-images.githubusercontent.com/38312178/50475712-4b22de00-09ce-11e9-848c-e4ddb005e21a.png)

**Comment by abrahamos** [comment]
Fixed by d5eca3e5a49ea482543118db4d37bf88e29566b0
