### ISSUE TITLE
show deleted items multiple selection bug 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1473]
go to search
click on show deleted items 
select an item from the list to enter multiple select mode 
select all 
after the first click on select all it shows this 
![image](https://user-images.githubusercontent.com/38312178/50559273-e46b3080-0cfd-11e9-8075-5efa0c296e39.png)
after trying to exit the mode by clicking the button again it shows this instead
![image](https://user-images.githubusercontent.com/38312178/50559306-3318ca80-0cfe-11e9-9a1d-7f8a996399b6.png)
after clicking it for the third time it enters the select all mode but actually selects only one item
![image](https://user-images.githubusercontent.com/38312178/50559320-4f1c6c00-0cfe-11e9-95e8-9041b556bb3e.png)

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/pull/1495
