### ISSUE TITLE
User profile page fixes

### ISSUE THREAD

**Issue by AvrahamO** [linnovate/root#1474]
1. Disable `Fullname`, `Email`, `Password` and `Change Password` fields for Active Directory login (as it's not relevant), leave only the `Profile picture` field.
2. Remove the Notifications tab.

**Comment by liorkesos** [comment]
To verify completion I think we should have a 2.0.7 candidate deployment configured to work with the Activedirectory

**Comment by artem123456123** [comment]
@abrahamos  can you please tell how can i get to "Active Directory login" page ? can't find it

**Comment by AvrahamO** [comment]
Resolved by bdab51293f0a2a3f63399368e45a1e60ed922469
