### ISSUE TITLE
select all in search shows and selects deleted items 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1478]
in search
enter multiple selection mode 
select everything
it selects even the deleted items that have the same name 
![image](https://user-images.githubusercontent.com/38312178/50589513-a0a83080-0e8f-11e9-92fe-86a1d4ba08e0.png)

**Comment by manmorc** [comment]
fixed in fixed in #1495

**Comment by AviramAshkenazi** [comment]
fix outside
