### ISSUE TITLE
Search: can't delete in multiple select just after refresh/go to other tab

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1479]
open a few items with name of test.
search in the search line : "test".
click on the multiple select and choose all items.
![image](https://user-images.githubusercontent.com/31100069/50589873-0cd76400-0e91-11e9-988a-8b036df23310.png)

click on delete.

![image](https://user-images.githubusercontent.com/31100069/50589885-1c56ad00-0e91-11e9-879d-a0b858af50dc.png)

the items didn't delete until you refresh or going to other tab.

**Comment by manmorc** [comment]
fixed in #1495

**Comment by AviramAshkenazi** [comment]
still happends

**Comment by AviramAshkenazi** [comment]
fix

**Comment by yaronmir** [comment]
@AvrahamO this bug happens again
