### ISSUE TITLE
Meetings: Can pick dates ending date that earlier than the starting date 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1481]
open new discussion.
fill the fields.
click on date.
pick starting date as today and ending date as yesterday.
it's show message but still saving the dates.
![image](https://user-images.githubusercontent.com/31100069/50591702-968b2f80-0e99-11e9-9c8d-3cb6f80b5f5d.png)

**Comment by ohadetsion** [comment]
Not a bug
