### ISSUE TITLE
search bugs

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1484]
- [x] tasks
- [x] projects
- [x] meetings

### tasks:
search for a task that is assigned to you
click on it when found
 the sub tasks dont show
also documents tab doesn't work
![image](https://user-images.githubusercontent.com/38312178/50595936-25ed0e80-0eab-11e9-9d35-ea5cc8bc365b.png)
after changing the task's name, it sometimes reverts it after the change to the pre-changed one

### projects
search for a project/meeting that is assigned to you
click on it 
sub projects dont appear
the first click on the result displays details of a different project
![image](https://user-images.githubusercontent.com/38312178/50596109-c17e7f00-0eab-11e9-8736-5a6e48bbac5f.png)

### meetings
search for a project/meeting that is assigned to you
click on it 
the first click on the result displays details of an empty meeting
![image](https://user-images.githubusercontent.com/38312178/50596125-da873000-0eab-11e9-875f-5bef7b423648.png)

the user isnt able to change anything in the project/meeting, and when you try to click on the title or a description, it disappears until you click again
![image](https://user-images.githubusercontent.com/38312178/50595784-921b4280-0eaa-11e9-8f60-996f3bfb9a56.png)

**Comment by AviramAshkenazi** [comment]
@abrahamos  fix or not?

**Comment by yaronmir** [comment]
Still don't know since we didn't git pull yet

**Comment by AvrahamO** [comment]
First click was fixed at 0f3727afb7543d8f873403e44149a4ba415c8255
The sub-projects bug wasn't fixed, as it was also in 2.0.5

**Comment by AvrahamO** [comment]
Tasks documents tab was fixed at b2b861caea8d50b1e0d0dcef406a6e3d228bf8ab
