### ISSUE TITLE
cant delete an office from a folder, and when you assign the folder to a document it crashes the app

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1499]
create an office
create a folder 
create a document 
assign the office to the folder
try to remove the office from the folder 
the office disappears but it's still assigned to the folder 
![image](https://user-images.githubusercontent.com/38312178/50821452-e6557500-1337-11e9-9bbb-3a97032abe7c.png)
the terminal writes this:
![image](https://user-images.githubusercontent.com/38312178/50821490-0127e980-1338-11e9-8b21-5d4a9114c303.png)
assign the folder to the document 
the app crashes with this message in the terminal:
![image](https://user-images.githubusercontent.com/38312178/50821602-49dfa280-1338-11e9-84ff-5cd1fbc03b24.png)

**Comment by manmorc** [comment]
@abrahamos not reproducible in current release branch, please retest

**Comment by chensabag** [comment]
@AviramAshkenazi

**Comment by abrahamos** [comment]
We couldn't reproduce the first bug (removing office from a folder)
Regarding the second bug (assigning folder to a document), it was fixed together with #1486 by 5a5cca95070043ef4eee55f1792d7c705c77a54e
