### ISSUE TITLE
if you assign a task to a project, you cant access it anymore

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1509]
if you assign a task to a proect using the select project function in the task template you cant access it anymore even if you have editor permissions in both the task and the project,  because it deletes every partner you had on the task

![image](https://user-images.githubusercontent.com/38312178/51471126-853d9080-1d7e-11e9-8664-22f5b097bcf8.png)

the changes arent saved after refreshing the page

**Comment by abrahamos** [comment]
Duplicate #1497
