### ISSUE TITLE
Search: attachments multiple select bug

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1514]
open new document.
fill the fields.
choose office.
create form template.
search after the document.
![image](https://user-images.githubusercontent.com/31100069/51479908-4b798380-1d98-11e9-9afb-ad6b01b05042.png)
can't select attachments in multiple select.

**Comment by yaronmir** [comment]
![image](https://user-images.githubusercontent.com/38312178/51519844-c4c1b680-1e2a-11e9-84cf-4eccb8a7eaa7.png)

**Comment by AvrahamO** [comment]
What is expected ?
Note that there is no actions for attachment - no tags/assignee/due/delete etc.
So what should be the behavior on selecting attachment?

**Comment by ohadetsion** [comment]
Not a bug
