### ISSUE TITLE
changing permissions isnt saved after refresh or after going to another tab

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1515]
in documents, changing permissions isnt saved after refresh or after going to another tab
for example, if you change a partner's permission from watcher to editor, the changes arent saved after refresh and the partner is still set on viewer permissions

**Comment by AvrahamO** [comment]
Reproducable on 5a5cca95070043ef4eee55f1792d7c705c77a54e
Assuming it was fixed somewhere in the recent commits
