### ISSUE TITLE
show deleted items multiple select bag

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1517]
- [x] not all the items selected
- [x] its choose more items than it's says
- [x] can't choose all items 
![image](https://user-images.githubusercontent.com/31100069/51538961-52b59580-1e5b-11e9-9dd2-95687ba0da66.png)
![image](https://user-images.githubusercontent.com/31100069/51538992-72e55480-1e5b-11e9-9198-11107587f31b.png)
![image](https://user-images.githubusercontent.com/31100069/51539011-8a244200-1e5b-11e9-8b40-5bd892b9f8c3.png)
![image](https://user-images.githubusercontent.com/31100069/51539058-acb65b00-1e5b-11e9-8f60-8a3d3282b543.png)

**Comment by AviramAshkenazi** [comment]
![image](https://user-images.githubusercontent.com/31100069/51539199-16366980-1e5c-11e9-8b95-31d41237890e.png)

**Comment by AviramAshkenazi** [comment]
it's happens because in the list you have attachment but it's still should choose all the items

**Comment by yaronmir** [comment]
fixed
