### ISSUE TITLE
duplicate task doesnt duplicate fully

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1519]
duplicate task doesnt duplicate the lables, sub tasks, files and related project& discussion that were in the original task.
original task:
![image](https://user-images.githubusercontent.com/38312178/51541205-eb024900-1e60-11e9-977d-225a407ecff9.png)

duplicated task:
![image](https://user-images.githubusercontent.com/38312178/51541264-12591600-1e61-11e9-8dd2-55e67c630bca.png)

**Comment by AvrahamO** [comment]
It works as exactly as designed in #1276

**Comment by oronbh** [comment]
This task was done exactly as specified - Please remove label 2.0.6
Needs new specifications if you want it in 2.0.7 for development. 
@yaronmir @AviramAshkenazi
