### ISSUE TITLE
in projects from meetings and tasks from meetings, the user can click between the selections of the projects/ tasks

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1530]
in projects from meetings and tasks from meetings, the user can click between the selections of the projects/ tasks, by clicking the gap between the tasks/ projects, a blank(without any relation to a meeting) tasks/projects from meetings tab opens in the main pane
![image](https://user-images.githubusercontent.com/38312178/51676770-4ad32e00-1fe0-11e9-9a43-7c6a16dfce88.png)

**Comment by AvrahamO** [comment]
This is a discussion without title.
When I set a title for that discussion, then it appear correctly.
