### ISSUE TITLE
multiple select in search bugs

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1555]
in search when there are a lot of results when entering multiple select mode, select all, there are the following bugs : 

- [x] it doesnt select everything 
![image](https://user-images.githubusercontent.com/38312178/52174637-89ff3d00-279f-11e9-9db3-b6077a5d7421.png)

- [x] when exiting the select all mode it still selects x-1 of the items that were selected when clicking on select all
![image](https://user-images.githubusercontent.com/38312178/52174645-b9ae4500-279f-11e9-86f4-74087cd08bc8.png)

- [x] when re-clicking the select all, it says that 1 items selected, and some of the editing options disappear
![image](https://user-images.githubusercontent.com/38312178/52174691-0db92980-27a0-11e9-88f0-340c8018fddc.png)

**Comment by manmorc** [comment]
@yaronmir edition options depends on selected items, if user will select entity without assign for example, you can not do bulk assign for selected list

**Comment by yaronmir** [comment]
@manmorc my bad, it just moved a little to the left (the status and viewer options)

**Comment by yaronmir** [comment]
@AvrahamO the "doesnt select everything when clicking on 'select all' happens again
