### ISSUE TITLE
Visual bug - Office Documents From Folder

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1558]
create new folder with long title (for example: "new folder1 - meiran")
select office
select documents 
select manage documents
create new item
the folder title will be bigger than expected
![image](https://user-images.githubusercontent.com/40392773/52177297-63ed9300-27c7-11e9-906f-7f2dbdf1051a.png)

**Comment by AvrahamO** [comment]
It's because of a `h1` applied to the folder title.
@manmorc please fix that.
