### ISSUE TITLE
Task from meeting, project and documents can't open document page  

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1559]
go to Meetings 
open new meeting 
fill the fields
click on Tasks field
click on Manage Tasks
open new task
fill the fields
click on document
The document page did not open.
this also happens when opning a task from projects or documents

![image](https://user-images.githubusercontent.com/31100069/52177421-24c04180-27c9-11e9-9112-928bcd3111ef.png)

logs:

![image](https://user-images.githubusercontent.com/31100069/52177435-546f4980-27c9-11e9-9de7-6a2d4e8c1b53.png)

**Comment by YehudaMorad** [comment]
@AvrahamO @manmorc  Take a look at the picture attached 
you need to go to task form discussion and pick a task from the list
press on documents button and you'll that it not responding.

**Comment by manmorc** [comment]
@YehudaMorad working fine in current version
