### ISSUE TITLE
inheritance process bug

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1560]
create new folder named: "new folder1 - meiran"
add user with specific permission
select document 
click manage documents
create new document
go back to settings 
press on "new folder1 - meiran" folder
change the permission of user
go to document that connected to "new folder1 - meiran" folder
check if the permission changed 
result: permission not changed

**Comment by AvrahamO** [comment]
Permissions are not supposed to be updated in that case.
See #1307

**Comment by YehudaMorad** [comment]
@AvrahamO ההרשאות אמורות לחלחל לכל מסמך שקשור לתיק. 
לדוגמה אם הוספתי משתמש לתיק עם הרשאות של מגיב, כל מסמך שקשור לתיק/ שייפתח מתוך התיק המשתמש יקבל גישה למסמכים אלו עם ההרשאות של מגיב.
