### ISSUE TITLE
deleted items bugs 2.0.6

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1563]
- [x] no permissions to change anything in a deleted item, in addition when accessing a document, it shows this screen, when clicking on something to try and edit it the due date jumps to 2027
![image](https://user-images.githubusercontent.com/38312178/52177907-656f8900-27d0-11e9-81c1-75c82bf90a8e.png)

- [x]  after clicking on select all, and unselecting some items, the number of selected items doesnt change:
![image](https://user-images.githubusercontent.com/38312178/52177028-fbe97d80-27c3-11e9-9184-eab1632e2636.png)

- [ ] after clicking on a deleted item and refreshing the page afterwards, (even though the show deleted items is not selected anymore, it still shows the deleted items) , clicking on a deleted item again loads a lot of items that werent loaded before:
![image](https://user-images.githubusercontent.com/38312178/52177936-e6c71b80-27d0-11e9-85f7-66ebf8190ef5.png)

**Comment by AvrahamO** [comment]
1. 1. Deleted documents cannot be edited, this is the behavior in 2.0.5.
   1. The screen of a document is a problem, we will fix that.
1. Select all problem - we will fix that.
1. Displaying all entities - this is the behavior on 2.0.5 too. You must click on the "CLEAR" button to uncheck the "Show deleted items". Refreshing the page doesn't make it.

**Comment by manmorc** [comment]
@AvrahamO ii. - Do you mean the broken UI of details or what?

**Comment by yaronmir** [comment]
fixed
