### ISSUE TITLE
In every entity sorting by bolded not working

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1565]
in every entity make sure you have bolded items.
try to filtering by bolded.
not working as well.
same as #1493.

**Comment by AvrahamO** [comment]
I tested on tasks, and on projects, everything works as expected

**Comment by manmorc** [comment]
@AviramAshkenazi , we have no filtering by bolded, only sorting, in release branch i see sorting works pretty good

**Comment by AviramAshkenazi** [comment]
Tasks:
![image](https://user-images.githubusercontent.com/31100069/52341490-5c262c80-2a1b-11e9-87fc-7960aed4cc20.png)
Projects:
![image](https://user-images.githubusercontent.com/31100069/52341531-811a9f80-2a1b-11e9-93e2-9f25cfa90f2b.png)
Documents:
![image](https://user-images.githubusercontent.com/31100069/52341582-a5767c00-2a1b-11e9-83f8-c4cbbeff9619.png)
Meetings:
![image](https://user-images.githubusercontent.com/31100069/52341842-5c72f780-2a1c-11e9-8f55-f44f78eaa507.png)
@manmorc @AvrahamO 
as you can see it's work fine only in meetings.

**Comment by AvrahamO** [comment]
@AviramAshkenazi, your empty entities might be bolded as well, but you cannot see that.
Try without empty titles.

**Comment by manmorc** [comment]
@AvrahamO @AviramAshkenazi entities without title can be bolded too, so it sorts it in right way
