### ISSUE TITLE
Manage documents(in tasks+folders)/tasks(in projects+meetings+documents)/folders(in offices) bugs

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1566]
- [x] manage folders
after 9+ folders are created, the user cant scroll down to see the rest in the manage folders list
after moving to the manage folders tab, the office still shows up on the right side of the screen and is editable, and the changes are saved
![image](https://user-images.githubusercontent.com/38312178/52201405-f9466100-2873-11e9-8327-6246d9a62ce8.png)

- [ ] manage tasks
1.  from documents, after assigning the task a project and returning to the parent document, the folder name disappears both in the manage tasks tab and in the task itself: 
![image](https://user-images.githubusercontent.com/38312178/52200319-27767180-2871-11e9-8076-6f41519338cc.png)
after 8 in a document (that doesnt have a file in it) or 7 (if it doesnt) the user cant scroll any lower to see the rest

2. [ ] from meetings 
after creating 10 tasks, the user cant move the list any lower 
![image](https://user-images.githubusercontent.com/38312178/52199052-a8336e80-286d-11e9-812e-e302dc361b4c.png)
the manage tasks list doesnt show the related projects the tasks are related to 

3. [x] from projects, after creating 10+ tasks, 2 manage tasks buttons appear 
![image](https://user-images.githubusercontent.com/38312178/52200970-c780ca80-2872-11e9-91a2-e8c2c8555938.png),
- [ ] visual bug when showing the related project the task is related to
![image](https://user-images.githubusercontent.com/38312178/52201165-64dbfe80-2873-11e9-9167-fcc3b6789680.png)

- [ ] manage documents
go to settings
create new folder
go to documents - manage documents
create new document
delete the document you just create 
deleted document appear at the list of Documents of the folder
this also happens when you access manage documents in tasks

![image](https://user-images.githubusercontent.com/40392773/52196508-c052c000-2864-11e9-8a34-ec83dbf51acc.png)
![image](https://user-images.githubusercontent.com/40392773/52196570-014ad480-2865-11e9-9e0b-b8fb1dfec71e.png)

- [ ] after creating 10 entities, the user cant move the list any lower 
![image](https://user-images.githubusercontent.com/38312178/52199052-a8336e80-286d-11e9-812e-e302dc361b4c.png)

**Comment by meiranhadad** [comment]
I Marked off what amended
