### ISSUE TITLE
open new task from + button

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#1570]
press on the plus button and create a new task.
it's take about 10 sec to open it.

**Comment by AvrahamO** [comment]
I couldn't reproduce this issue on Azure test environment.
Please provide more details.

**Comment by yaronmir** [comment]
@AvrahamO when openin a task in the tasks tab using the plus button, the app takes a while to create it 
when opening a task in a different tab(projects, discussions, etc...) it marks the task list in blue : 
![image](https://user-images.githubusercontent.com/38312178/52641395-68116300-2ee1-11e9-90bd-8a6550bc43f6.png)

**Comment by AvrahamO** [comment]
We see this problem on the commit where the test env is (5184f27cc14ee8dfdf29164e02533571a1d67a4c), but in the latest version it works good.
So I assume this was fixed during work on other issues.
