### ISSUE TITLE
Multiple choice - assignee change

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1578]
according to system characterization, the assignee need to add as a commenter
which doesn't happen in multiple choices.
![image](https://user-images.githubusercontent.com/40392773/52207275-a1185a80-2885-11e9-8c0f-bbf4e767ac3b.png)

**Comment by AvrahamO** [comment]
Same as #1577

**Comment by YehudaMorad** [comment]
@AvrahamO לאיזה באג זה דומה?
