### ISSUE TITLE
Multiple Choice - Search - visual bug

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1579]
once there is a lot of results, the icons are disappear

![image](https://user-images.githubusercontent.com/40392773/52210555-10934780-2890-11e9-92d1-a7cb4e3c3b4f.png)

**Comment by manmorc** [comment]
@YehudaMorad icons of bulk operations?

**Comment by AvrahamO** [comment]
@manmorc yep
It should be sticky, like in other entities
