### ISSUE TITLE
Documents filtering by folder

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1580]
go to setting - Folders
create new folder
select office 
![image](https://user-images.githubusercontent.com/45143091/52212188-97e2ba00-2894-11e9-907c-b91872b57d04.png)
go to Documents
create new document
select folder that you created
![image](https://user-images.githubusercontent.com/45143091/52212344-e728ea80-2894-11e9-9bb5-494a94aa23d8.png)
go to side bar - Folders
choose your folder
the folder is not exist 
![image](https://user-images.githubusercontent.com/45143091/52212394-0c1d5d80-2895-11e9-98ee-f9dc37d65bf9.png)

**Comment by AvrahamO** [comment]
You typed a folder name instead of office.
This input is to filter the folder list by their parent office.
Set a parent office to your folder, then you will be able to see your folder in the side bar.
This behavior is same as of 2.0.5
