### ISSUE TITLE
search bug - shuld to display results after 3 Letters

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1581]
According to Characterization System, the results should display after 3 letters from the beginning of the word.
![image](https://user-images.githubusercontent.com/40392773/52212789-fceadf80-2895-11e9-9634-c46e3f4200a9.png)

![image](https://user-images.githubusercontent.com/40392773/52212816-0d02bf00-2896-11e9-8a71-b115228a558d.png)

**Comment by AvrahamO** [comment]
Actually, the search function is called on the first letter you enter in the input.
In your case, make sure you have a entity with the word "tes" - as a whole word - in it's name.
The search doesn't match partial words, exactly like in 2.0.5, nothing was changed.

**Comment by YehudaMorad** [comment]
ok. maybe this a problem in  our elasticsearch
