### ISSUE TITLE
Document viewers do not passing into the task

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1583]
create new Document
add watchers
 
![image](https://user-images.githubusercontent.com/45143091/52215564-f6ac3180-289c-11e9-9751-2fde6a36ba0b.png)

go to Tasks -> Manage Tasks
create new task
the watchers from document not appears at the new task
![image](https://user-images.githubusercontent.com/45143091/52215499-d54b4580-289c-11e9-8041-9d91f22cda27.png)

**Comment by yaronmir** [comment]
@AvrahamO still exists
