### ISSUE TITLE
Document name stay after delete uploaded file 

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1584]
go to Documents 
create new document
upload file 
![image](https://user-images.githubusercontent.com/45143091/52216279-91594000-289e-11e9-9208-956b5bb9f619.png)
delete the file
the name of the document stay
![image](https://user-images.githubusercontent.com/45143091/52216405-c6659280-289e-11e9-85dd-802efdb7894b.png)

**Comment by AvrahamO** [comment]
What should happen?
Note that document's title is not actually connected to the file, but just initiated for the first time (you can update the title after that).

**Comment by meiranhadad** [comment]
after deleting file the name should be reset to empty name because there is no file uploaded there

**Comment by AvrahamO** [comment]
What if the name was edited and now it's not same as the file name?
Should it be deleted anyway?

**Comment by yaronmir** [comment]
still happens
