### ISSUE TITLE
Delete permissions after changing a folder

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1591]
go to settings and create a folder.
go to document and create a new document
connect the document to a folder that you don't have permissions.
reconnect the documents from this folder.
result: the permissions that you have as editor, (because you open this specific doc) were deleted
![image](https://user-images.githubusercontent.com/40392773/52340376-4cf1af80-2a18-11e9-9963-fca80a0f858b.png)

**Comment by israelfrank** [comment]
@AvrahamO  
get another user to add you as a viewer to a folder
create a new document
add the folder that you are a viewer in to the new document
after refreshing the page, your editor permissions in the document(that you had after creating it) are now only viewer permissions

**Comment by manmorc** [comment]
@YehudaMorad i can't see losing permissions on removing folder inheritance in a document,
@israelfrank on adding folder to office document all permissions and watchers are taking from parent folder, what behavior you think should be here?

**Comment by AvrahamO** [comment]
Fixed during work on #1592

**Comment by yaronmir** [comment]
@AvrahamO still happens, same for #1592

**Comment by YehudaMorad** [comment]
@AvrahamO 
to be more specific,
once I create a new document, I have the high permissions - editor
even the document is connected to a folder that I have lower permissions like a viewer, 
my permissions as editor are not replaced. I'm still supposed to be an editor. because I am the document owner.

**Comment by AvrahamO** [comment]
2 problems here:
1. Specific bug of losing all watchers & permissions when connecting to a folder and immediately disconnecting it.
1. Overriding high permissions by parent (tracked in #1615)

Please close this issue as it was fixed here.
The overriding permissions was described in #1615 and should be tracked there.

Thanks
