### ISSUE TITLE
plus button create new items bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1612]
- [ ] projects tab
when opening a task, it creates a task from project instead of a regular task
![image](https://user-images.githubusercontent.com/38312178/52910965-a0c98780-32a7-11e9-937a-3ee074abae8b.png)
- [ ] discussions tab
when opening a task it creates a task from discussion instead
![image](https://user-images.githubusercontent.com/38312178/52911080-d4a4ad00-32a7-11e9-9362-3668838d3958.png)

**Comment by manmorc** [comment]
@yaronmir as i know, this is normal behavior, @AvrahamO please confirm

**Comment by chensabag** [comment]
It happened in the past and was solved #1341

**Comment by manmorc** [comment]
@yaronmir @chensabag can be closed?

**Comment by manmorc** [comment]
@AvrahamO @yaronmir  i see in here an usual behavior creating task from current opened entity, i think this can be closed, or give some steps to reproduce unexpected behavior
