### ISSUE TITLE
The discussions below are also deleted

### ISSUE THREAD

**Issue by israelfrank** [linnovate/root#1614]
go to meeting
open some discussion
fill the fields
Select  discussion
Delete the selected discussion

result : all discussions under the selected discussion have been deleted
and come back after refresh

before : 
![image](https://user-images.githubusercontent.com/47353222/52911053-b939a200-32a7-11e9-9c56-fd9024946a2b.png)

after delete:
![image](https://user-images.githubusercontent.com/47353222/52911115-2d744580-32a8-11e9-9896-f506a90b4d4f.png)

afte refresh:
![image](https://user-images.githubusercontent.com/47353222/52911156-c3a86b80-32a8-11e9-82b3-cf8047d8c91c.png)

**Comment by manmorc** [comment]
@israelfrank cannot reproduce in current release branch, tryed both by regular recycling and by bulk operation

**Comment by YehudaMorad** [comment]
@manmorc can you be more specific, please?

**Comment by manmorc** [comment]
@YehudaMorad adding video link with tries to reproduce:
https://drive.google.com/file/d/1vizj6KXZllPIAJjzKu8vxXMb6NY22mmA/view

**Comment by manmorc** [comment]
i see just the same behavior in 2.0.5 version, changing issue labels
