### ISSUE TITLE
multiple choice in search - show deleted items

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1616]
go to the search tab and search something - for example "test"
(make sure that you have deleted items called "test")
click on option "show deleted items"
choose the items with multiple choice and delete them.
there is no option to delete items that deleted before so when this option has been chosen,
the delete icon not should be displayed.
![image](https://user-images.githubusercontent.com/40392773/52912541-5a7e2380-32bb-11e9-8ffe-16ecc266b889.png)

**Comment by AvrahamO** [comment]
Duplicate #1610 ?

**Comment by yaronmir** [comment]
@AvrahamO yes, closing this one
