### ISSUE TITLE
document : Multiple selection status has an option of waiting for approval

### ISSUE THREAD

**Issue by israelfrank** [linnovate/root#1622]
go to document 
open new document
fill the fields
click on multiple select
click on "Bulk status"
click on select status

result : There is an option of waiting  approval though it should not be

![image](https://user-images.githubusercontent.com/47353222/52941636-f5d1d000-3371-11e9-84cd-a4c35fcd56a9.png)

**Comment by AvrahamO** [comment]
Duplicate #1574

Was in previous version too.
