### ISSUE TITLE
date box shoudn't be able to contain a free text

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1637]
![image](https://user-images.githubusercontent.com/40392773/53693996-c2029b80-3db0-11e9-8fb5-19e15a17e68d.png)

**Comment by yaronmir** [comment]
@AvrahamO still happens in meetings
![image](https://user-images.githubusercontent.com/38312178/58174466-b2f00300-7ca6-11e9-9ec8-195bda4d9947.png)

**Comment by AvrahamO** [comment]
Forgot to fix for discussion too...
Fixed now
