### ISSUE TITLE
Settings - Change participant status in Office not updated in attributed Folder

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1642]
go to Settings
create new Office (for example: new office6 - meiran)
add participant
create new Folder (for example: new folder23 - meiran)
select the office you created (new office6 - meiran)
go to the office you create and change the participant status
go back to the folder you create 
the participant status not updated
the office: 
![image](https://user-images.githubusercontent.com/45143091/53695263-cf745180-3dc1-11e9-9a00-48d236c715a3.png)
the attributed folder:
![image](https://user-images.githubusercontent.com/45143091/53695281-fc286900-3dc1-11e9-89aa-797a15cca921.png)

**Comment by AvrahamO** [comment]
This issue was reported on #1560, and was closed without solving, because it is not an expected behavior to keep the permissions connected forever.
The idea of inheritance is only for the first time connecting a child entity with a parent.
Please see #1307.
