### ISSUE TITLE
document: tasks from office document

### ISSUE THREAD

**Issue by israelfrank** [linnovate/root#1643]
go to document 
open new document
click on tasks and click on Manage tasks
You'll get to the Tasks from Documents screen
open some new tasks
select a task and click the star on the left side of the screen
click on sort by star 

result: sorting does not work

in document click on Manage tasks
![image](https://user-images.githubusercontent.com/47353222/53695548-b66d9f80-3dc5-11e9-967a-2f64a8ad5ae3.png)

open some new tasks
select a task and click the star on the left side of the screen
![image](https://user-images.githubusercontent.com/47353222/53695635-b7eb9780-3dc6-11e9-9f9e-513536b09be5.png)

click on sort by star 
result: sorting does not work
![image](https://user-images.githubusercontent.com/47353222/53695659-013be700-3dc7-11e9-8cb9-34bf0a5fa277.png)

**Comment by manmorc** [comment]
@YehudaMorad is not working? on my test it works well
