### ISSUE TITLE
visual bug in sub projects+tasks

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1650]
create a new task/ project
create a new sub tas/ project in it 
select a due date that is in the past 
a white scrollable bar appears and the user can also scroll down until he wont see his sub entities anymore 
![image](https://user-images.githubusercontent.com/38312178/53890255-8544d780-4030-11e9-8e07-de7ebb51abe2.png)

**Comment by AvrahamO** [comment]
Fixed 6a2d6d69e9cfa74745adaec3eaaf5f5271975a8d
