### ISSUE TITLE
multiple choice mode, choosing yourself as an assignee lowers your permissions from edit to commenter

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1662]
create a few projects
enter multiple select mode
choose yourself as an assignee in multiple select
your editor permissions are now lowered to commenter

**Comment by israelfrank** [comment]
enter multiple select mode:
![image](https://user-images.githubusercontent.com/47353222/54878596-84d17c80-4e37-11e9-8319-e1d7f22bbe88.png)

choose yourself as an assignee in multiple select:
![image](https://user-images.githubusercontent.com/47353222/54878604-ae8aa380-4e37-11e9-9544-b37fe6f425ba.png)

your editor permissions are now lowered to commenter:
![image](https://user-images.githubusercontent.com/47353222/54878623-d11cbc80-4e37-11e9-8207-5f481b55b41f.png)
