### ISSUE TITLE
multiple select cant view existing tags

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1664]
create a few tasks
enter multiple select mode
go to add tags
click on the tag's text field
already existing tags dont show up

**Comment by israelfrank** [comment]
create a few tasks
enter multiple select mode
go to add tags:
![image](https://user-images.githubusercontent.com/47353222/54878763-d7ac3380-4e39-11e9-80da-f5204445628c.png)

click on the tag's text field
already existing tags dont show up:
![image](https://user-images.githubusercontent.com/47353222/54878776-f14d7b00-4e39-11e9-93f4-ef2b85a6fa5e.png)

**Comment by meiranhadad** [comment]
@AvrahamO this also happens in regular tag's creation as well

**Comment by AvrahamO** [comment]
OK, understand that you want to see some suggestions in the dropdown.

Now what is expected to see:
1. Tags from all searched items - no matter what kind of entity are they.
1. Tags form all searched items of the same entity.
1. Tags that appear in some of the **selected** items but not in all of them.

@chensabag @ohadetsion

**Comment by ohadetsion** [comment]
Option 3

**Comment by AvrahamO** [comment]
This 3rd option is now working for search results.
For entity list, all existing tags per the given entities are displayed - see #1722.
