### ISSUE TITLE
create new document from folder is added to folder list

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1665]
go to Settings -> Folders
create new folder 
go to Documents -> manage documents
create new document (from folder)
![image](https://user-images.githubusercontent.com/45143091/54925713-84101780-4f17-11e9-8d0c-f841789cef39.png)
go to Settings -> Folders
the new document appear at the list of all the folders
![image](https://user-images.githubusercontent.com/45143091/54925794-b3268900-4f17-11e9-86d3-256a6bfb869c.png)

**Comment by AvrahamO** [comment]
I couldn't reproduce this bug

**Comment by meiranhadad** [comment]
remark: only happens if you create a folder and immediately after it creates a document.

**Comment by AvrahamO** [comment]
Fixed by 129ae13ac776dcff5736d558873619a4dd7e42a2
