### ISSUE TITLE
search: add an assignee to the task

### ISSUE THREAD

**Issue by israelfrank** [linnovate/root#1666]
go to task
open new task
go to search 
Search for the task
add watcher  to the task or add a date

result : a screen of tasks from a project opens 

search for the task
add watcher  to the task or add a date
![image](https://user-images.githubusercontent.com/47353222/54931116-1ff25100-4f21-11e9-922d-f6f18b91d04a.png)

result : a screen of tasks from a project opens 
![image](https://user-images.githubusercontent.com/47353222/54927255-7b6d1080-4f1a-11e9-954e-531ff29a35e9.png)

This behavior is repeated in projects meetings folders and offices

in template document The search does not work

**Comment by AvrahamO** [comment]
Fixed in 1c9d857e77e5605032d182a06be066522dcfd5c0

**Comment by yaronmir** [comment]
@AvrahamO still happens
