### ISSUE TITLE
incorrectly date at Activities list 

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1668]
go to Settings -> Template Document
create new item
write something at the Activities window 
the date is displayed incorrectly
![image](https://user-images.githubusercontent.com/45143091/54980262-eddb0080-4fad-11e9-8be8-cda7f3197661.png)

**Comment by AvrahamO** [comment]
It's just the date format.

Was _MM/DD/YY_, now (since 99c48419e2595708a7b98bad590d234736b02308) everything was switched to _DD/MM/YY_
