### ISSUE TITLE
cant find deleted doc template 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1683]
create a new template document
name it 
delete it 
go to search 
press show deleted items
search for the deleted doc template
it shows it in the results found (right side) but not in the list itself
![image](https://user-images.githubusercontent.com/38312178/57019001-edc5c480-6c2d-11e9-89f2-8df150c55859.png)

**Comment by AvrahamO** [comment]
Fixed in d502de4ed3f6c0d782598defb1eb81326bd70e9d

**Comment by israelfrank** [comment]
@AvrahamO  It happens
