### ISSUE TITLE
Delete multiple choice - button not clickable

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1693]
go to Settings -> Folders
create new item 
go to Documents -> Manage Documents
create few items
choose some items and delete them 
the items are deleted only after refreshing the page or going to another tab and back to the deleted item's list
- Also happens in: Folders from Office, Tasks from Discussion, Tasks from Projects and Office from Tasks
![image](https://user-images.githubusercontent.com/45143091/58245702-10935680-7d5e-11e9-841d-4d02cf7f6023.png)

**Comment by israelfrank** [comment]
@AvrahamO still happend
