### ISSUE TITLE
after filtering by all/archived and clicking on the favorite filter, the filter changes to status:active 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1695]
create new items
go to filter by status : all/ archived
click on the favorite filter
the status changes to status : active

**exiting filter by favorite mode also changes the status to active**

before pressing favorite filter
![image](https://user-images.githubusercontent.com/38312178/58251062-79cd9680-7d6b-11e9-8855-6ae56b3b0ea9.png)

after pressing the favorite filter
![image](https://user-images.githubusercontent.com/38312178/58251310-00827380-7d6c-11e9-9a7a-f84d987f63c8.png)

**Comment by AvrahamO** [comment]
Happens only in folders/offices.

But...
Does this kind of entities have a feature of status - archived/active ?

Maybe we have to remove this filter for those entities.

@chensabag @ohadetsion please advise...

**Comment by AvrahamO** [comment]
Duplicate #1691
