### ISSUE TITLE
Updating a file number does not change when you change a folder

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1700]
go to document 
create 2 items
- at the first document select some folder and enter the File button
![image](https://user-images.githubusercontent.com/45143091/59193669-217dfd80-8b8f-11e9-8cba-90b7f26fa15b.png)
- at the second document select some other folder and enter the File button
go to the first document you create and change the folder to the same folder of the second document 
** the number of file does not change and that causes documents with the same file number **
- the first document :
![image](https://user-images.githubusercontent.com/45143091/59193899-e9c38580-8b8f-11e9-9250-6a142f8cffc7.png)
- the second document : 
![image](https://user-images.githubusercontent.com/45143091/59193937-0790ea80-8b90-11e9-8573-29b681b3ec05.png)

**Comment by ohadetsion** [comment]
If you remove the folder the file number should be unset @AvrahamO
