### ISSUE TITLE
multiple select no previous tags are shown

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1704]
create a new entity
add a new tag to it 
create another entity
enter multiple select mode
click on bulk tags
try to enter a tag from the tag's history list
no tags are shown when the new tag space is clicked 
![image](https://user-images.githubusercontent.com/38312178/59264266-67000080-8c4b-11e9-9d87-0a851cefb109.png)

**Comment by AvrahamO** [comment]
Fixed by 31f0ee305a91d67bdeaf87c785589c8ea8ff5e44
