### ISSUE TITLE
when pressing the arrow sort (left of created sort) the items list disappears 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1753]
create some entities
click on the arrow sort button
the list of items disappears 
before pressing :
![image](https://user-images.githubusercontent.com/38312178/61182492-a8b20b80-a63c-11e9-8c95-49ab4326254c.png)
after pressing : 
![image](https://user-images.githubusercontent.com/38312178/61182496-b8c9eb00-a63c-11e9-8ac8-c236d2788766.png)

this also happens in full screen mode

**Comment by israelfrank** [comment]
@AvrahamO

**Comment by AvrahamO** [comment]
I cannot reproduce it now.
I assume it was fixed during previous bug fixes.
