### ISSUE TITLE
document / item it is not deleted

### ISSUE THREAD

**Issue by dolevenergy** [linnovate/root#1772]
Documents - When you delete a specific document / item it is not deleted in the Details pane

**Comment by israelfrank** [comment]
@AvrahamO  
go to document open new document
search this document
delete the document 
 item it is not deleted in the Details pane

**Comment by yaronmir** [comment]
@AvrahamO this current commit, when you delete an entity it stays visible in both the entity list and the details pane :
![image](https://user-images.githubusercontent.com/38312178/62036724-00cf3d00-b1fb-11e9-9a69-42d39d3121f7.png)
