### ISSUE TITLE
filter bar in search doesnt work properly 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1781]
updated after doesnt work at all
filter by status, after filtering the entities' list by status, and clicking on one afterwards, resets the filtering

**Comment by AvrahamO** [comment]
*Updated after* is working now.
Regarding the status filter, when you click on an entity it just collapses the status filter, but it doesn't actually change it's value.

**Comment by israelfrank** [comment]
@AvrahamO the updated after still doesnt work.
