### ISSUE TITLE
Search > filtred by "SHOW RESULTS OF:"

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1813]
the filter "SHOW RESULTS OF:" isn't work.
for example: 
if I search for value "1" and there are several options and i choose to show results only from task.
it should show only entitys from tasks.
![image](https://user-images.githubusercontent.com/40392773/63223019-13b0ae00-c1b8-11e9-8163-25676461e8f9.png)

**Comment by AvrahamO** [comment]
Fixed by 34f583e8eae9970f2d658844ff621f3f5d1c3652
