### ISSUE TITLE
Search > Search options

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1816]
According to the characterization, the search function should work even i didnt worte the whole word. 
It is enough to write 3 letters from the word and the search results should show all the words that contain these 3 letters that I'm searched. 
![image](https://user-images.githubusercontent.com/40392773/63224691-9180b380-c1d0-11e9-8338-f8d054e9b39e.png)
![image](https://user-images.githubusercontent.com/40392773/63224703-b07f4580-c1d0-11e9-8936-2168801c9477.png)

**Comment by AvrahamO** [comment]
Duplicate #1581
