### ISSUE TITLE
assgining a user,setting a date to a sub project makes the screen disappear 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1828]
go to project 
create a project and a sub project from it 
enter the sub projects tab 
assign a user  to the sub project or set a due date for it
the screen disappears: 
![image](https://user-images.githubusercontent.com/38312178/64613821-c4892200-d3df-11e9-890d-d3600cee5360.png)

**Comment by israelfrank** [comment]
@AvrahamO  now its happend only in date

**Comment by israelfrank** [comment]
@AvrahamO  still happned
