### ISSUE TITLE
tasks from meetings inheritance 

### ISSUE THREAD

**Issue by israelfrank** [linnovate/root#1852]
go to meetings 
open meeting add watcher and give him permissions
go to tasks tab and open task from meetings
result : the mission did not receive inheritance from the discussion

**Comment by AvrahamO** [comment]
Same as #1853.
Fixed

**Comment by YehudaMorad** [comment]
לא עובד עדיין.

**Comment by YehudaMorad** [comment]
@AvrahamO לא עובד
