### ISSUE TITLE
meetings > task form meetings > inheritance

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1853]
task form meetings should To inherit spesific meeting 
which not happend.

**Comment by dolevenergy** [comment]
היי, יש לשים לב שאין צורך שמשתתפי הדיון יתווספו לכל משימה ומשימה,
מעבר לכך קיימת כפילות עם באג #1852 נא לבטל!!!

**Comment by AvrahamO** [comment]
Reverted
