### ISSUE TITLE
error at npm install

### ISSUE THREAD

**Issue by assafSabag** [linnovate/root#208]
![screenshot from 2016-03-28 12 47 29](https://cloud.githubusercontent.com/assets/12615452/14075611/40cc8bc0-f4e3-11e5-89cf-7d71687b9f40.png)

> bson-ext@0.1.6 install /home/linnovate3/Desktop/assaf/icu-fixes/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
> ./node_modules/node-pre-gyp/bin/node-pre-gyp.js install --fallback-to-build

module.js:327
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/linnovate3/Desktop/assaf/icu-fixes/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/linnovate3/Desktop/assaf/icu-fixes/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/linnovate3/Desktop/assaf/icu-fixes/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.2.0-34-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/linnovate3/Desktop/assaf/icu-fixes/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/node_modules/node-pre-gyp/bin/node-pre-gyp.js" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/linnovate3/Desktop/assaf/icu-fixes/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
node-pre-gyp ERR! node -v v4.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/linnovate3/Desktop/assaf/icu-fixes/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN optional dep failed, continuing bson-ext@0.1.6
 
> node-sass@3.4.2 install /home/linnovate3/Desktop/assaf/icu-fixes/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

**Comment by dvoras** [comment]
@assafSabag Is this bug is relevant?

**Comment by kaplanlior** [comment]
@dvoras I don't think it's relevant anymore.
