### ISSUE TITLE
Update DB to have groups

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#235]
In order to have groups, it needed to update the mongodb in 3 sachems: "tasks", "discussions", "projects".
The script to update is : " db.getCollection('projects').update({},{$set:{groups:[],comp:[]}},{multi:1}) "
for each of the 3 sachems.

But needed to update in the code for the future new users/develepers.

**Comment by rivkatzur** [comment]
@ohadetsion It is not relevant anymore since we moved circles to api
