### ISSUE TITLE
Responsive Implementation

### ISSUE THREAD

**Issue by moshesharon** [linnovate/root#254]
Root Implementation doesn't support responsive

**Comment by ohadetsion** [comment]
@moshesharon can you explain ?

**Comment by moshesharon** [comment]
responsive is handling the UI in different screen and different devices. for example you can't show the data the same way in pc / laptop/ android/ios . without dealing with  responsive you will have to do the work 3 or more times.  look here http://www.w3schools.com/html/html_responsive.asp
