### ISSUE TITLE
image profile not seemed good

### ISSUE THREAD

**Issue by sara-37002** [linnovate/root#268]
![9](https://cloud.githubusercontent.com/assets/19186872/17171847/1ab1b4f2-53fb-11e6-941d-012b6492ed70.png)

**Comment by sara-37002** [comment]
וכל התמונות בשרת ובקבצים
still -bug

**Comment by ohadetsion** [comment]
@dvoras  still have this bug ?

**Comment by ruthhlp** [comment]
all  images update /  upload from now it's ok
