### ISSUE TITLE
You can not see the friend's name

### ISSUE THREAD

**Issue by sara-37002** [linnovate/root#269]
![10](https://cloud.githubusercontent.com/assets/19186872/17171908/5a91dff2-53fb-11e6-8ce2-338fe316c714.png)

**Comment by sara-37002** [comment]
בפיירפוקס-עדיין-באג
בכרום תקין

**Comment by ohadetsion** [comment]
The bug still exists.

**Comment by rivkatzur** [comment]
update db:
var cursor = db.tasks.find({watchers:{$size:0}})
cursor.forEach(function(x){db.tasks.update({_id:x._id},{$push:{watchers:x.creator}})});

(tasks, projects & discussions)

**Comment by rivkatzur** [comment]
done on dev6
