### ISSUE TITLE
need to translate from english to hebrew

### ISSUE THREAD

**Issue by sara-37002** [linnovate/root#279]
![1](https://cloud.githubusercontent.com/assets/19186872/17203816/3a99091e-54aa-11e6-8419-2102668f8a08.png)
![2](https://cloud.githubusercontent.com/assets/19186872/17203876/add909ec-54aa-11e6-9696-bb726ceb7e86.png)
![3](https://cloud.githubusercontent.com/assets/19186872/17203879/b65f4504-54aa-11e6-8650-8ceea178c5f1.png)

**Comment by sara-37002** [comment]
![7](https://cloud.githubusercontent.com/assets/19186872/17203926/07b4125e-54ab-11e6-8f38-0ade77ae3d6e.png)

**Comment by rivkatzur** [comment]
done on dev

**Comment by sara-37002** [comment]
![1](https://cloud.githubusercontent.com/assets/19186872/17285150/8c54bdb2-57c9-11e6-8f82-bb014c59be6e.png)
![2](https://cloud.githubusercontent.com/assets/19186872/17285151/8c705c8e-57c9-11e6-8ac1-4de788b155bf.png)
