### ISSUE TITLE
need to location and align components

### ISSUE THREAD

**Issue by sara-37002** [linnovate/root#280]
![4](https://cloud.githubusercontent.com/assets/19186872/17203939/1675fe74-54ab-11e6-8a21-d41ea717fb42.png)
![5](https://cloud.githubusercontent.com/assets/19186872/17203956/35c05bb2-54ab-11e6-978e-a654b278b91c.png)
![6](https://cloud.githubusercontent.com/assets/19186872/17203967/4a4673b4-54ab-11e6-9594-63ffd88b80de.png)
![8](https://cloud.githubusercontent.com/assets/19186872/17203968/4a475860-54ab-11e6-9e9e-d07ae0c9c3f4.png)

**Comment by sarareisner** [comment]
done

**Comment by sara-37002** [comment]
![default](https://cloud.githubusercontent.com/assets/19186872/17285051/cb56599a-57c8-11e6-9f38-1fd26ceb8d82.png)
![2](https://cloud.githubusercontent.com/assets/19186872/17285052/cb7205c8-57c8-11e6-84f0-03bf4af46688.png)

**Comment by dvoras** [comment]
https://github.com/linnovate/root/commit/345ca92af7b8d80607e7fbbcf1508e239d8aef93
