### ISSUE TITLE
Unclear css

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#281]
The part of the date in the list, is cover
The cubes is not straight (In the same line)

![screenshot from 2016-07-28 07 29 41 fix by screen](https://cloud.githubusercontent.com/assets/17906421/17216685/530a8136-54ea-11e6-9d74-256d3c596b29.png)

**Comment by kaplanlior** [comment]
This also happens in English in certain screen sizes.

**Comment by sara-37002** [comment]
fix verified 
@dvoras
