### ISSUE TITLE
Can't see the user who did the update

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#282]
Can't see the user who did the update in "MyTasks"

![screenshot from 2016-07-28 07 29 41 no user show](https://cloud.githubusercontent.com/assets/17906421/17216816/d769b28a-54ea-11e6-95eb-a25af0c53553.png)

**Comment by dvoras** [comment]
Fixed https://github.com/linnovate/root/commit/d6367eab0f57f55383b7b91d913850ba3358422b
