### ISSUE TITLE
Can't see more then one watcher

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#284]
One watcher i can see normally but after i add different watcher, both of them disappear...

**Comment by rivkatzur** [comment]
@ohadetsion 
try update db:
var cursor = db.tasks.find({watchers:{$size:0}})
cursor.forEach(function(x){db.tasks.update({_id:x._id},{$push:{watchers:x.creator}})});

(tasks, projects & discussions)

**Comment by ohadetsion** [comment]
@rivkatzur It works thanks!
