### ISSUE TITLE
The UI stops working after creating the first project.

### ISSUE THREAD

**Issue by kaplanlior** [linnovate/root#302]
With a new user, after creating the first project, the system doesn't respond (incl. tasks link).

![pasted_image_at_2016_08_02_10_20_am_720](https://cloud.githubusercontent.com/assets/2017058/17320275/66fc0336-589b-11e6-9b9c-3e4cb4f9d834.png)
![pasted_image_at_2016_08_02_10_22_am_720](https://cloud.githubusercontent.com/assets/2017058/17320274/66f7ddba-589b-11e6-815f-a4379b5192b3.png)

**Comment by dvoras** [comment]
https://github.com/linnovate/root/commit/8b4c6a69c0de25d5372e341da1d91fbeb26b3ce7
