### ISSUE TITLE
Problem with tasks: "assign to" & "watcher" in two users

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#307]
With one user i assigned a task to different user, and also i made him watcher in different task.
The problem is that in "Mytasks" i can see only the task witch been assign to that user. Meanwhile, in "All tasks", i can see only the task that the user is watcher.
![screenshot from 2016-08-04 04 50 58](https://cloud.githubusercontent.com/assets/17906421/17401044/f3d0b66c-5a53-11e6-94cd-86a4badd6577.png)
![screenshot from 2016-08-04 04 51 41](https://cloud.githubusercontent.com/assets/17906421/17401047/f5d8402e-5a53-11e6-9c54-4f3a1e4b011d.png)

**Comment by dvoras** [comment]
@ohadetsion According to what Idan said, in "My Tasks" you can see only tasks that you are assigned and **not watcher**, in "all tasks" you can see all the taske you are watcher or assign or creator, and this is what I see. Can you specify what you see?

**Comment by ohadetsion** [comment]
OK, so in "all tasks" i cant see the task that i am watcher in it.

**Comment by dvoras** [comment]
@ohadetsion in what environment do you test? It's works ok in dev6- http://icu.dev6.linnovate.net/

**Comment by ohadetsion** [comment]
@dvoras My environment , But need to check it again
