### ISSUE TITLE
Important - Only appropriate user will see file

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#309]
**Important**
In the current situation, evrey user can see evrey file (if he has the url to the file for example: "http://localhost:3000/tasks/by-project/56e6c7f390fb9b0e70b1bca4/5773d169f46a12fa79268db7/activities").
IT NEED to be that only user who is watcher/creator/assign in the entity of the attachment(task/discussion/project) will be able to see the file.

**Comment by dvoras** [comment]
@ohadetsion Did you see entity that you are not the watcher/creator/assign? if not, so how you can see the document not inside the details of this entity?

**Comment by ohadetsion** [comment]
@dvoras I meant that if one user press on "view" in document details, and copy the link, and sent it to diffrent user that don't watcher/creator/assign, so this diffrent user **can** see this document.
But it's need to be that the user who don't watcher/creator/assign **can't** see this document.

**Comment by dvoras** [comment]
@ohadetsion O.K. so this options wasn't develop yet. you can add it to the next sprint if you want.

**Comment by ohadetsion** [comment]
@rivkatzur Can we close this issue?

**Comment by rivkatzur** [comment]
@ohadetsion  I did it, Can you test it on dev6 before we close the issue?
