### ISSUE TITLE
projects displayed just after refresh in the dropdown of select project

### ISSUE THREAD

**Issue by dvorad** [linnovate/root#314]
1. create new task
2. create new project
3. connect this task to the project

no projects in the list.
just after refreshing the site you can see the projects.

http://icu.dev6.linnovate.net/tasks/all/57a83d94789ea85d5eae8375/activities

![icu4](https://cloud.githubusercontent.com/assets/10514414/17474737/3e60ecc4-5d60-11e6-8db9-f7d06dabb304.png)

**Comment by ohadetsion** [comment]
@dvorad Sitll have this problem? i can't see it...
