### ISSUE TITLE
Empty box in tasks

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#326]
In the toolbar there is empty box (where there was the projects)

![image](https://cloud.githubusercontent.com/assets/17906421/17692956/72490df4-6351-11e6-9851-e9fce4cb2010.png)

**Comment by ruthhlp** [comment]
https://projects.invisionapp.com/share/5C85S16GF#/screens/178249899/comments/69883004

**Comment by ohadetsion** [comment]
@ruthhlp I understand, but there is still empty box where there were the project name

**Comment by moshesharon** [comment]
open a new bug.
