### ISSUE TITLE
Empty projects

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#327]
With new user enter to the system, opened some new empty projects, but i when i click on them, nothing happen...

![screenshot from 2016-08-16 01 51 07](https://cloud.githubusercontent.com/assets/17906421/17693679/fc6fad50-6354-11e6-99e1-37b4835d5bd2.png)

**Comment by rivkabenshalom** [comment]
https://github.com/linnovate/root/commit/6962d5e8c8cd9ad0bb10f3ccde4c872d5662ae47
