### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#329]
I have task, and i can see it in tasks -> All : 

![image](https://cloud.githubusercontent.com/assets/17906421/17727489/63ffa9f2-640e-11e6-9fac-0f036eb9681d.png)

but when i search it, i can't fint it! :

![image](https://cloud.githubusercontent.com/assets/17906421/17727495/74261262-640e-11e6-8c3b-75700959bcc1.png)

**Comment by ohadetsion** [comment]
It also happen in projects or discussion

**Comment by assafSabag** [comment]
examle

2016-08-17 10:09 GMT+03:00 ohadetsion <notifications@github.com>:
