### ISSUE TITLE
"Restricted access" doesn't work - Important  

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#349]
In dev6 work fine, while locally it doesn't work at all. In the past i had this problem but we manege to fix it, but once again i can't open it... there is an error in "F12" as you can see in the picture, related to file "modal-Compartmentalization.js" something with empty "data.sources.length" i think....

![image](https://cloud.githubusercontent.com/assets/17906421/18264555/d008a128-73c5-11e6-8b18-143063b4eccc.png)

**Comment by dvoras** [comment]
@ohadetsion Can you pull the updates from "circles" repository?

**Comment by ohadetsion** [comment]
@dvoras I used "git pull origin master", didn't helped....

**Comment by dvoras** [comment]
@ohadetsion Try register with a new user and check if the error still exists

**Comment by ohadetsion** [comment]
@dvoras Yes, with new i works... but why with old one i can't?

**Comment by dvoras** [comment]
@ohadetsion someting has changed in the circles, so your user's circles don't exist, please delete them from the MongoDB:
db.users.update({email:'YOUR_EMAIL"'},{$unset:{circles:1}})

**Comment by ohadetsion** [comment]
@dvoras Works!
