### ISSUE TITLE
Can't see file in browser - Important 

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#350]
After uploading file to the system, i click on view button, and it did open new tab in the browser, but an empty tab - so i can't see the view...
*The file is uploaded to the files-system and you can download it, so the problem is specific with the "view" function.

![image](https://cloud.githubusercontent.com/assets/17906421/18264759/0ac72d42-73c7-11e6-9d37-e6fba445d392.png)

**Comment by rivkatzur** [comment]
Now it's ok
