### ISSUE TITLE
Sub-tasks view problem

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#368]
In the sub tasks, the view of the assign not seem so good, especially in the list of the people...

![image](https://cloud.githubusercontent.com/assets/17906421/18518009/0606b0fc-7aa7-11e6-92a6-b9cd48ce88f1.png)

**Comment by rivkabenshalom** [comment]
@ohadetsion  i fixed it 
https://github.com/linnovate/root/commit/ea246b392a6ced954b86e41e078bf9b2243938a9
