### ISSUE TITLE
Can't know if the template has saved

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#378]
I tried to make template (within the 'sub-tasks'), and i tried to save it, but i will know (see) if my new template saved only after F5 (Refresh)

![image](https://cloud.githubusercontent.com/assets/17906421/19218797/ebf00bd6-8db7-11e6-802b-0eb0f37d468f.png)

**Comment by rivkabenshalom** [comment]
https://github.com/linnovate/root/commit/80dc3ee60a950068b6ec236ba0438f1dd5469e55
