### ISSUE TITLE
Template name not save properly

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#379]
The template name is the name of task above (the main task of sub-tasks) , and not the name i gave it..

![image](https://cloud.githubusercontent.com/assets/17906421/19218840/307ee56e-8db9-11e6-8f04-4fdb210ad65a.png)

**Comment by rivkabenshalom** [comment]
https://github.com/linnovate/root/commit/8607473b9f4ae914a53235477ec0e13fe4d988ca
