### ISSUE TITLE
make the default browse configurable

### ISSUE THREAD

**Issue by ozfela** [linnovate/root#384]
today if you just browse to 'http://localhost:3002' you go to the "login" screen.
instead, it should allow developer config which authentication he want to user.

for example: if the developer want all users will authenticate via google, he certainly wants to have a possibility to change the default browse (http://website.co.il) to "google" authentication.

**Comment by liorkesos** [comment]
That is planned to be handled by configuration and by the activeProvider setting.

**Comment by rivkatzur** [comment]
default stategy is local
To use another strategy you have to change activeProvider in config/env/all.js
And to set the strategy info in config/env/<env>.js
