### ISSUE TITLE
Usersnap Feedback - When adding a task when we press tab it should focus on the task area belo[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#403]
**Sender**: lior@linnovate.net
**Comment**: When adding a task when we press tab it should focus on the task area below to create the next task
[Open #8 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/8)
**Notes**:
 - (1) When adding a task when we press tab it should focus on the task area below to create the next task

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-19/11-15/26c8d4b5-0ad8-479a-bf03-293470f3f5f9.png'>![Usersnap Feedback - When adding a task when we press tab it should focus on the task area belo(...)](https://usersnappublic.s3.amazonaws.com/2017-01-19/11-15/7c50ddcc-99d9-4e93-9f0b-e1b34a3d6efe.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-19/11-15/26c8d4b5-0ad8-479a-bf03-293470f3f5f9.png'>Download original image</a>

**Browser**: Chrome 55 (OS X El Capitan)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/by-project/58809165e03d681100931132/activities](http://root.hrm.demo.linnovate.net/tasks/by-project/58809165e03d681100931132/activities)
**Screen size**: 1440 x 900 **Browser size**: 2778 x 1432

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
@dvorad It seems as it works, Can you check it again and if you still think there is a bug explain it  clearer
