### ISSUE TITLE
Usersnap Feedback - After opening a task to discussion the server failed

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#404]
**Sender**: dvorad@linnovate.net
**Comment**: After opening a task to discussion the server failed
[Open #9 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/9)

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-19/12-09/faa3c31f-9d21-4688-8aa3-a7af7cff9194.png'>![Usersnap Feedback - After opening a task to discussion the server failed](https://usersnappublic.s3.amazonaws.com/2017-01-19/12-09/149d75b3-8783-428e-9100-5ddff6d80194.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-19/12-09/faa3c31f-9d21-4688-8aa3-a7af7cff9194.png'>Download original image</a>

**Browser**: Chrome 51 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/by-discussion/58809d711cfd0813001ee897/58809d871cfd0813001ee89d/activities](http://root.hrm.demo.linnovate.net/tasks/by-discussion/58809d711cfd0813001ee897/58809d871cfd0813001ee89d/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 917

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
@moshesharon fixed on branch master. Not uploaded to server yet

**Comment by dvorad** [comment]
http://root.hrm.demo.linnovate.net/

**Comment by rivkatzur** [comment]
@dvorad fixed on http://root.hrm.demo.linnovate.net/
