### ISSUE TITLE
Usersnap Feedback - After change the discussion name, the name hasn't changed

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#406]
**Sender**: dvorad@linnovate.net
**Comment**: After change the discussion name, the name hasn't changed
[Open #11 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/11)

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-19/12-46/044469d3-34b0-4841-b081-fec56b1cf4c4.png'>![Usersnap Feedback - After change the discussion name, the name hasn't changed](https://usersnappublic.s3.amazonaws.com/2017-01-19/12-46/e113a0de-e3ed-44ca-ac30-5e749f41e0a6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-19/12-46/044469d3-34b0-4841-b081-fec56b1cf4c4.png'>Download original image</a>

**Browser**: Chrome 51 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/by-discussion/58809d711cfd0813001ee897/activities](http://root.hrm.demo.linnovate.net/tasks/by-discussion/58809d711cfd0813001ee897/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 917

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
@dvorad Can not reproduce
