### ISSUE TITLE
Usersnap Feedback - The attached document doesn't have been attached to the document TAB

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#407]
**Sender**: dvorad@linnovate.net
**Comment**: The attached document doesn't have been attached to the document TAB
[Open #12 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/12)

1.3.15-EN							
Action:click on the Document TAB
Actual Result: The document doesn't have been displayed on document TAB
Expected result: all the document of this task display

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-22/12-07/d191a110-d1f0-486f-a378-b12be388f50a.png'>![Usersnap Feedback - The attached document doesn't have been attached to the document TAB](https://usersnappublic.s3.amazonaws.com/2017-01-22/12-07/6af937bd-44ce-4bda-a686-9fec81163be8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-22/12-07/d191a110-d1f0-486f-a378-b12be388f50a.png'>Download original image</a>

**Browser**: Chrome 51 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/by-discussion/58809ed62a99a6130073832a/58848e755e7f031300508767/documents](http://root.hrm.demo.linnovate.net/tasks/by-discussion/58809ed62a99a6130073832a/58848e755e7f031300508767/documents)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
fixed
