### ISSUE TITLE
Usersnap Feedback - The last task a starred doesn't have been displayed on the list after sort[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#408]
**Sender**: dvorad@linnovate.net
**Comment**: The last task a starred doesn't have been displayed on the list after sorting by starred
[Open #13 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/13)

1.2.6-EN			
Action: sort by Star
Actual result: The last task a starred doesn't have been displayed on the list after sort	
Expected result: display all the tasks are starring

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-22/12-22/d6257723-5f5d-40a5-b434-894f4a90a050.png'>![Usersnap Feedback - The last task a starred doesn't have been displayed on the list after sort(...)](https://usersnappublic.s3.amazonaws.com/2017-01-22/12-22/3bb8fe82-1498-47f2-b71d-220284cf725e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-22/12-22/d6257723-5f5d-40a5-b434-894f4a90a050.png'>Download original image</a>

**Browser**: Chrome 51 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/all/5880bc7f6005d21300d843d3/activities](http://root.hrm.demo.linnovate.net/tasks/all/5880bc7f6005d21300d843d3/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
@dvorad The task is not starred, So it not in the list
