### ISSUE TITLE
Usersnap Feedback - Notifications didn't updated after select a member

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#411]
**Sender**: dvorad@linnovate.net
**Comment**: Notifications didn't updated after select a member
[Open #16 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/16)

1.3.17-EN
Action: open the notifications
Expected result: notifications opened and updated
Actual Result: notifications didn't updated

1.3.18-EN			
Action:close the notifications	
Expected result: notifications closed	

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-22/13-52/2e41be30-563f-4fc9-abf3-0627843ea0a8.png'>![Usersnap Feedback - Notifications didn't updated after select a member](https://usersnappublic.s3.amazonaws.com/2017-01-22/13-52/344a6937-1c51-4fc4-9880-2f0e87c53d4e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-22/13-52/2e41be30-563f-4fc9-abf3-0627843ea0a8.png'>Download original image</a>

**Browser**: Chrome 51 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/by-project/58808e7be03d68110093111e/5880ca4bf200101100e61397/activities](http://root.hrm.demo.linnovate.net/tasks/by-project/58808e7be03d68110093111e/5880ca4bf200101100e61397/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
@dvorad ![whatstheproblem](https://cloud.githubusercontent.com/assets/6241247/22329195/d92a8a0a-e3c8-11e6-81bd-d0b76e564c5a.png)
