### ISSUE TITLE
Usersnap Feedback - Unable to click on "זמן דיון"

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#412]
**Sender**: dvorad@linnovate.net
**Comment**: Unable to click on "זמן דיון"
[Open #17 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/17)

Id: 2.3.22-HE
Action: click on the button "זמן דיון"

Expected Result: 
1. "email sent to the member
2. The status became "זומן"
3. The button became "ארכיון"

Actual Result:
1. email wasn't sent
2. status remains "חדש"
3. button remains "זמן דיון"

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-23/11-01/47dddc03-591a-4465-b69d-d04273a1a6e9.png'>![Usersnap Feedback - Unable to click on "זמן דיון"](https://usersnappublic.s3.amazonaws.com/2017-01-23/11-01/826f41aa-b5d4-4b02-af0c-356d3c8ff9d7.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-23/11-01/47dddc03-591a-4465-b69d-d04273a1a6e9.png'>Download original image</a>

**Browser**: Chrome 51 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/by-discussion/58808e7fe03d681100931123/activities](http://root.hrm.demo.linnovate.net/tasks/by-discussion/58808e7fe03d681100931123/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
@dvorad @moshesharon @liorkesos 
need to config mailer.auth on server

**Comment by liorkesos** [comment]
Can you document how to do it in the wiki ?
Please enclose the link to it.
