### ISSUE TITLE
Usersnap Feedback - all users are watching on watcher while creation a new discussion and project

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#413]
**Sender**: dvorad@linnovate.net
**Comment**: A problem on watcher while creation a new project
[Open #18 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/18)

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-25/11-03/8e463e21-41b4-49f6-bced-16d52bd2e3e9.png'>![Usersnap Feedback - A problem on watcher while creation a new project](https://usersnappublic.s3.amazonaws.com/2017-01-25/11-03/bbdebb45-63c6-4808-b237-dd7f1e493329.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-25/11-03/8e463e21-41b4-49f6-bced-16d52bd2e3e9.png'>Download original image</a>

![image](https://cloud.githubusercontent.com/assets/10514414/22402957/cb1543c4-e611-11e6-827b-75dc3437f45e.png)

**Browser**: Chrome 51 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/by-project/588877ba0a4c971100da7fcb/activities](http://root.hrm.demo.linnovate.net/tasks/by-project/588877ba0a4c971100da7fcb/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dvorad** [comment]
@rivkatzur while I created a new project, the message is : "כל המשתמשים כבר צופים" and unable to choose a watcher

**Comment by rivkatzur** [comment]
@dvorad fixed on master
