### ISSUE TITLE
Usersnap Feedback - The letter wasn't been changed after logout and login

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#414]
**Sender**: dvorad@linnovate.net
**Comment**: The letter wasn't been changed after logout and login
[Open #19 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/19)

4.2.2-EN
action: click on login button	
expected result: go to the Tasks page and your first letter displyed in the icon
actual result: letter isn't right

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-26/13-11/38b610a0-aee3-4aea-9ff6-fd897498a1dc.png'>![Usersnap Feedback - The letter wasn't been changed after logout and login](https://usersnappublic.s3.amazonaws.com/2017-01-26/13-11/48e813d7-eac4-4fbe-b88d-2898e7046293.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-26/13-11/38b610a0-aee3-4aea-9ff6-fd897498a1dc.png'>Download original image</a>

**Browser**: Chrome 51 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/discussions/all/587dfb91770dea1100232d03/activities](http://root.hrm.demo.linnovate.net/discussions/all/587dfb91770dea1100232d03/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
@dvorad fixed om branch master
