### ISSUE TITLE
Usersnap Feedback - The uploaded file does not responding to the 4 documents features (watch, [...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#421]
**Sender**: guy@energyteam.co.il
**Comment**: The uploaded file does not responding to the 4 documents features (watch, download, recover, edit).
[Open #24 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/24)

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-13/16-32/77c798c0-7927-4e1e-babb-159882aa4ff2.png'>![Usersnap Feedback - The uploaded file does not responding to the 4 documents features (watch, (...)](https://usersnappublic.s3.amazonaws.com/2017-02-13/16-32/2492615a-f59d-4d49-ab17-9469d40f4c89.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-13/16-32/77c798c0-7927-4e1e-babb-159882aa4ff2.png'>Download original image</a>

**Browser**: Chrome 56 (Windows 7)
**Referer**: [http://icudev.eastus.cloudapp.azure.com:3002/tasks/by-project/58a186856e5298ede812670a/58a18a966e5298ede81267aa/activities](http://icudev.eastus.cloudapp.azure.com:3002/tasks/by-project/58a186856e5298ede812670a/58a18a966e5298ede81267aa/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 918

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ohadetsion** [comment]
Not for this tag: recover, edit
Need to look by @ozfela : watch, download

**Comment by ozfela** [comment]
[https://github.com/linnovate/root/commit/f7acf61c476eac2a166b499a7c6391a10b37d097](url)
