### ISSUE TITLE
Usersnap Feedback - In the first time you select the date for the mission\project its giving t[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#422]
**Sender**: guy@energyteam.co.il
**Comment**: In the first time you select the date for the mission\project its giving the day before (you choose 20 you'll get 19). The second time it gives the date you selected. Not consistent.
[Open #25 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/25)

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-13/16-46/f14a1518-a0c7-498b-aac6-db8ca24be710.png'>![Usersnap Feedback - In the first time you select the date for the mission\project its giving t(...)](https://usersnappublic.s3.amazonaws.com/2017-02-13/16-46/caa4de06-c0c7-431a-b692-30546eb43e68.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-13/16-46/f14a1518-a0c7-498b-aac6-db8ca24be710.png'>Download original image</a>

**Browser**: Chrome 56 (Windows 7)
**Referer**: [http://icudev.eastus.cloudapp.azure.com:3002/tasks/by-project/58a186856e5298ede812670a/58a1d4966e5298ede8126919/activities](http://icudev.eastus.cloudapp.azure.com:3002/tasks/by-project/58a186856e5298ede812670a/58a1d4966e5298ede8126919/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 918

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/f956e8cc9f6b9ba9ae3d80d8f3d3770f7fb387fa
