### ISSUE TITLE
Usersnap Feedback - There are no notifications after assigning missions to user (in version 1.[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#423]
**Sender**: guy@energyteam.co.il
**Comment**: There are no notifications after assigning missions to user (in version 1.0.3 there were,,,)
[Open #26 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/26)

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-13/17-07/5c052b9d-7d37-4e8c-a2cd-f4cf6b60b34c.png'>![Usersnap Feedback - There are no notifications after assigning missions to user (in version 1.(...)](https://usersnappublic.s3.amazonaws.com/2017-02-13/17-07/d20aed82-a6e0-456f-9c78-b82403f0ce9a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-13/17-07/5c052b9d-7d37-4e8c-a2cd-f4cf6b60b34c.png'>Download original image</a>

**Browser**: Chrome 56 (Windows 7)
**Referer**: [http://icudev.eastus.cloudapp.azure.com:3002/tasks/my/58a1d4966e5298ede8126919/activities](http://icudev.eastus.cloudapp.azure.com:3002/tasks/my/58a1d4966e5298ede8126919/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 918

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ohadetsion** [comment]
https://github.com/linnovate/root/commit/88f2fcd33d8b54afcd9ff59730dd2dff0d886922
