### ISSUE TITLE
Can't open Discussions from Projects by press 'Create new"

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#431]
![image](https://cloud.githubusercontent.com/assets/17906421/25311555/943fc7f6-280c-11e7-80fe-9563e04908d8.png)

When we are in project, By pressing new Discussion in needs to open new Discussion from this project.
At the present it only open fresh new Discussion, that doesn't connect to the project

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/81fa49eea03cd5afba592b1a9c2741e0cebdac09
