### ISSUE TITLE
Can't open Projects from Discussions by press 'Create new"

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#432]
![image](https://cloud.githubusercontent.com/assets/17906421/25311597/d72f487e-280d-11e7-9f8a-f821667787e8.png)

When we are in Discussion , By pressing new project in needs to open new project from this Discussion.
At the present it only open fresh new project, that doesn't connect to the Discussion

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/414e5414ace28270e2c5efdc4faed471d55c1676
