### ISSUE TITLE
sub-tasks: Date change to 2022

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#433]
![image](https://cloud.githubusercontent.com/assets/17906421/25311699/6820e958-2810-11e7-898d-f09781ac402a.png)

In Sub-Tasks, after change the date the go to diffrent web-page, and go back to the same page, the date of the sub-tasks changes to 2022

**Comment by ohadetsion** [comment]
[https://github.com/linnovate/root/commit/9ba851bce44cef330ec958add6ca1bf39830b960](url)

**Comment by ohadetsion** [comment]
Before i type the dates are fine in the sub-takes
![image](https://cloud.githubusercontent.com/assets/17906421/25325064/177d97fe-28d2-11e7-9fce-9ac8cab1bd6a.png)

After I type something (tag or headline) the dates changes:
![image](https://cloud.githubusercontent.com/assets/17906421/25325123/76f3480a-28d2-11e7-834a-a539b66c00f0.png)

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/0da740be45b28ea68a93ccf351bdd8f9c207b9ed
