### ISSUE TITLE
Data of sub-tasks template doesn't save

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#435]
Here i save the template:
![image](https://cloud.githubusercontent.com/assets/17906421/25311822/522c315e-2813-11e7-833f-26ec94db1056.png)

And the Data doesn't save:
![image](https://cloud.githubusercontent.com/assets/17906421/25311874/4801db06-2814-11e7-9d1e-d4b01bbf8a1e.png)

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/53d7ab96afacedece759b266a5e88cccf1d5509c

**Comment by ohadetsion** [comment]
The Date still not save in the template

**Comment by yaronmir** [comment]
@AvrahamO this issue happens again
