### ISSUE TITLE
Less button in Hebrew Doesn't work

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#438]
Less button in Hebrew Doesn't work, in tasks - > projects:

![image](https://cloud.githubusercontent.com/assets/17906421/25327880/7b441d9c-28de-11e7-9d67-58982556abb2.png)

**Comment by ohadetsion** [comment]
Also happens in discussions -> projects
![image](https://cloud.githubusercontent.com/assets/17906421/25327988/e204ce5a-28de-11e7-8b1c-d42b25a7a962.png)

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/b1631fd38fdaef2dec1a35f28a62cf56e2381b9a
