### ISSUE TITLE
Unauthorized Search - see entity name

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#441]
If user search and found entity that he doesn't authorized to see, so he will not see the details of this entity.
BUT, he still can see the name of the entity and know, for sure, that in fact there is entity with this name.

As you can see, on the right there is task that user "a" shod not see in search. but actually, as you can see on the left, in search user "a" found it.

![image](https://cloud.githubusercontent.com/assets/17906421/25337440/8bddca88-2904-11e7-9377-dd3bd2e4be4d.png)

**Comment by Baraks24** [comment]
fixed
