### ISSUE TITLE
Usersnap Feedback - clicking on "manage tasks" jumping to Updates TAB

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#442]
**Sender**: dvorad@linnovate.net
**Comment**: clicking on "manage tasks" jumping to Updates TAB
[Open #29 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/29)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/11-14/2bf17bc8-13d6-4a14-bdbe-921e9652a45a.png'>![Usersnap Feedback - clicking on "manage tasks" jumping to Updates TAB](https://usersnappublic.s3.amazonaws.com/2017-04-25/11-14/311c81f9-7e39-4e8b-9a44-f329864e473e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/11-14/2bf17bc8-13d6-4a14-bdbe-921e9652a45a.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/tasks](http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/tasks)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 691

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ozfela** [comment]
fixed
[https://github.com/linnovate/root/commit/517ffb456a6b959b2afe20ec7b9ca9b700c41860](url)
