### ISSUE TITLE
Usersnap Feedback - tag list doesn't appear after add tags

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#443]
**Sender**: dvorad@linnovate.net
**Comment**: tag list doesn't appear after add tags
[Open #30 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/30)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/11-16/02953908-4d3b-4e4f-9a81-ec2c41fde043.png'>![Usersnap Feedback - tag list doesn't appear after add tags](https://usersnappublic.s3.amazonaws.com/2017-04-25/11-16/2dced0d9-d387-480d-97de-7b54f4323280.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/11-16/02953908-4d3b-4e4f-9a81-ec2c41fde043.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/58fdbd2e88e80e6c5a1837e9/activities](http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/58fdbd2e88e80e6c5a1837e9/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/2f4aa7d2995c054648409a1fd3c03505924be23e
