### ISSUE TITLE
Usersnap Feedback - clicking on the lock do nothing

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#446]
**Sender**: dvorad@linnovate.net
**Comment**: clicking on the lock do nothing
[Open #33 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/33)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/13-04/e570cd1b-c169-4160-947b-d8b1b78828a5.png'>![Usersnap Feedback - clicking on the lock do nothing](https://usersnappublic.s3.amazonaws.com/2017-04-25/13-04/92668f33-7fb6-42d5-89b6-b33f10a86049.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/13-04/e570cd1b-c169-4160-947b-d8b1b78828a5.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://root.hrm.demo.linnovate.net/tasks/by-discussion/58ff2ccdccde8d1100ad310e/documents](http://root.hrm.demo.linnovate.net/tasks/by-discussion/58ff2ccdccde8d1100ad310e/documents)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ohadetsion** [comment]
It's OK for now...
