### ISSUE TITLE
Usersnap Feedback - ניתן להכניס משימות לתאריך שהיה ולא קופצת הודעה או חלון שגיאה

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#449]
**Sender**: guy@energyteam.co.il
**Comment**: ניתן להכניס משימות לתאריך שהיה ולא קופצת הודעה
או חלון שגיאה
[Open #36 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/36)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/14-04/48e0a5ce-0012-413b-8006-7102ff2be97a.png'>![Usersnap Feedback - ניתן להכניס משימות לתאריך שהיה ולא קופצת הודעה או חלון שגיאה](https://usersnappublic.s3.amazonaws.com/2017-04-25/14-04/41603e73-50c3-4582-9e07-2435cded3a8b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/14-04/48e0a5ce-0012-413b-8006-7102ff2be97a.png'>Download original image</a>

**Browser**: Chrome 57 (Windows 10)
**Referer**: [http://40.71.214.223:3002/tasks/my/58fef6588158132b097a2c87/activities](http://40.71.214.223:3002/tasks/my/58fef6588158132b097a2c87/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ozfela** [comment]
add notification when user chose old-date to task/sub-task/discussion
[https://github.com/linnovate/root/commit/9bfc26792259fd0016ee4a1baea5a903716c67f5](url)
