### ISSUE TITLE
Usersnap Feedback - לא ניתן לראות או להוסיף תתי משימות תחת הקטגוריה "משימות שלי" - כאשר נכנסים [...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#451]
**Sender**: guy@energyteam.co.il
**Comment**: לא ניתן לראות או להוסיף תתי משימות תחת הקטגוריה "משימות שלי" -
כאשר נכנסים לקטגוריה משימות שלי, בוחרים משימה ונכנסים
אליה , לא ניתן לראות את התתי משימות הקיימות באותה משימה. כמו כן לא ניתן להוסיף תתי משימות חדשות- לא ניתן .לכתוב
[Open #38 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/38)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/14-15/20732f25-88c9-467e-a4c7-6b46655549b3.png'>![Usersnap Feedback - לא ניתן לראות או להוסיף תתי משימות תחת הקטגוריה "משימות שלי" - כאשר נכנסים (...)](https://usersnappublic.s3.amazonaws.com/2017-04-25/14-15/6a5e5901-5fc7-4a40-867c-ce89d460d307.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/14-15/20732f25-88c9-467e-a4c7-6b46655549b3.png'>Download original image</a>

**Browser**: Chrome 57 (Windows 10)
**Referer**: [http://40.71.214.223:3002/tasks/my/58ff0a218158132b097a2dce/activities](http://40.71.214.223:3002/tasks/my/58ff0a218158132b097a2dce/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/95578c80859bb51c15fb85c41da069021a527b0d
@dvorad
