### ISSUE TITLE
Usersnap Feedback - לחצן הנוטיפיקיישנס לא עובד

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#452]
**Sender**: guy@energyteam.co.il
**Comment**: לחצן הנוטיפיקיישנס לא עובד
[Open #39 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/39)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/14-20/6b107f4c-5714-4d31-96cc-b07d22cfd768.png'>![Usersnap Feedback - לחצן הנוטיפיקיישנס לא עובד](https://usersnappublic.s3.amazonaws.com/2017-04-25/14-20/576341ee-7db8-4052-aa61-5b988e0a0456.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/14-20/6b107f4c-5714-4d31-96cc-b07d22cfd768.png'>Download original image</a>

**Browser**: Chrome 57 (Windows 10)
**Referer**: [http://40.71.214.223:3002/tasks/my/activities](http://40.71.214.223:3002/tasks/my/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by Baraks24** [comment]
Maybe because there were no notifications to show?

**Comment by ohadetsion** [comment]
https://github.com/linnovate/root/commit/88f2fcd33d8b54afcd9ff59730dd2dff0d886922
