### ISSUE TITLE
Usersnap Feedback - במקום שיופיע פעם אחת כל משתתף בדיון הוא מופיע פעמים רבות ברשימת המשתתפים.

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#454]
**Sender**: guy@energyteam.co.il
**Comment**: במקום שיופיע פעם אחת כל משתתף בדיון הוא מופיע פעמים רבות ברשימת המשתתפים.
[Open #41 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/41)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/14-56/9dfcc472-fa72-4334-ba9c-55b89dabbb11.png'>![Usersnap Feedback - במקום שיופיע פעם אחת כל משתתף בדיון הוא מופיע פעמים רבות ברשימת המשתתפים.](https://usersnappublic.s3.amazonaws.com/2017-04-25/14-56/461c198f-b168-4bba-8e41-d5a15eeaba0a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/14-56/9dfcc472-fa72-4334-ba9c-55b89dabbb11.png'>Download original image</a>

**Browser**: Chrome 57 (Windows 10)
**Referer**: [http://40.71.214.223:3002/tasks/by-discussion/58fef4f48158132b097a2c3a](http://40.71.214.223:3002/tasks/by-discussion/58fef4f48158132b097a2c3a)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dvorad** [comment]
לא קורה באתר באנגלית

**Comment by Baraks24** [comment]
Can you be more specific when this bug happens? (have you succeeded adding a watcher who already exists?)

**Comment by ohadetsion** [comment]
Happens after click on schule discussin:
![image](https://cloud.githubusercontent.com/assets/17906421/25480738/f8ab3d34-2afe-11e7-839f-71df35be3256.png)


![image](https://cloud.githubusercontent.com/assets/17906421/25480781/22684de2-2aff-11e7-8f89-49fb20427c5c.png)

**Comment by Baraks24** [comment]
fixed
