### ISSUE TITLE
Usersnap Feedback - project name doesn't appear in the user assigned account

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#455]
**Sender**: dvorad@linnovate.net
**Comment**: project name doesn't appear in the user assigned account
[Open #42 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/42)
**Notes**:
 - (1) http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/58fdbd2e88e80e6c5a1837e9/activities

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/15-22/a90fad58-e24a-482b-a059-c262bea9e640.png'>![Usersnap Feedback - project name doesn't appear in the user assigned account](https://usersnappublic.s3.amazonaws.com/2017-04-25/15-22/ebcabd2d-25a0-4919-b805-14d17a3885ea.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/15-22/a90fad58-e24a-482b-a059-c262bea9e640.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/58fdbd2e88e80e6c5a1837e9/activities](http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/58fdbd2e88e80e6c5a1837e9/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/9f280a232cdae88b90174b5e2b8ba3f854335500
@dvorad
