### ISSUE TITLE
Usersnap Feedback - belong to #455 - The user that created the project see the project name, b[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#456]
**Sender**: dvorad@linnovate.net
**Comment**: belong to #455 - The user that created the project see the project name, but the second user doesn't see it
[Open #43 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/43)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/15-41/f364561f-d3da-45cd-867d-a6bccfde3fec.png'>![Usersnap Feedback - belong to #455 - The user that created the project see the project name, b(...)](https://usersnappublic.s3.amazonaws.com/2017-04-25/15-41/558287ea-5de7-4639-8ee0-f2f51b0cddfb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-25/15-41/f364561f-d3da-45cd-867d-a6bccfde3fec.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/58fdbd2e88e80e6c5a1837e9/activities](http://localhost:3006/tasks/by-project/587c76a6748d79fb1d799aed/58fdbd2e88e80e6c5a1837e9/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by Baraks24** [comment]
fixed
