### ISSUE TITLE
Usersnap Feedback - לא מופיע שם הדיון/ פרויקט בו רוצים ליצור משימה- כאשר פותחים דיון/ פרויקט ו[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#458]
**Sender**: guy@energyteam.co.il
**Comment**: לא מופיע שם הדיון/ פרויקט בו רוצים ליצור משימה-
כאשר פותחים דיון/ פרויקט ולוחצים על "משימות"- "נהל משימות" על מנת ליצור משימה חדשה זה פותח את העמוד משימות מדיון/ משמימות מפרוייקט "" ולא כתוב את שם הדיון/ .הפרוייקט
[Open #45 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/45)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/08-36/4bdcd606-de27-46f5-b1fa-49feb4fa28fb.png'>![Usersnap Feedback - לא מופיע שם הדיון/ פרויקט בו רוצים ליצור משימה- כאשר פותחים דיון/ פרויקט ו(...)](https://usersnappublic.s3.amazonaws.com/2017-04-26/08-36/793d96bb-c41c-4bf6-9053-cfdc5454cafc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/08-36/4bdcd606-de27-46f5-b1fa-49feb4fa28fb.png'>Download original image</a>

**Browser**: Chrome 56 (Windows 7)
**Referer**: [http://devicu.eastus.cloudapp.azure.com:3002/tasks/by-discussion/59003fb9c9a79539561b073b/activities](http://devicu.eastus.cloudapp.azure.com:3002/tasks/by-discussion/59003fb9c9a79539561b073b/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by Baraks24** [comment]
fixed
