### ISSUE TITLE
Usersnap Feedback - הדיונים מופיעים בסייד בר מתחת לפרויקטים- אמור להראות את כל הדיונים מתחת לק[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#459]
**Sender**: guy@energyteam.co.il
**Comment**: הדיונים מופיעים בסייד בר מתחת לפרויקטים- אמור להראות את כל הדיונים מתחת לקטגוריה דיונים ולא רק מתחת לפרוייקטים
[Open #46 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/46)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/08-43/39402a8e-c179-454b-88c6-26139e658c5d.png'>![Usersnap Feedback - הדיונים מופיעים בסייד בר מתחת לפרויקטים- אמור להראות את כל הדיונים מתחת לק(...)](https://usersnappublic.s3.amazonaws.com/2017-04-26/08-43/064961c0-2492-40ad-a132-6c3dce6e12c8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/08-43/39402a8e-c179-454b-88c6-26139e658c5d.png'>Download original image</a>

**Browser**: Chrome 56 (Windows 7)
**Referer**: [http://devicu.eastus.cloudapp.azure.com:3002/discussions/by-project/58ff2a9bc9a79539561b068d](http://devicu.eastus.cloudapp.azure.com:3002/discussions/by-project/58ff2a9bc9a79539561b068d)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ohadetsion** [comment]
Bug write unclear

**Comment by oritpersik** [comment]
![image](https://user-images.githubusercontent.com/5158550/27515925-74ac083c-59b7-11e7-9d66-cb7f9e1ac4c3.png)
