### ISSUE TITLE
Usersnap Feedback - יצרתי תבנית חדשה באחת המשימות מפרויקט מסויים שמכילה 4 משימות, הוספתי את ה[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#460]
**Sender**: guy@energyteam.co.il
**Comment**:  יצרתי תבנית חדשה באחת המשימות מפרויקט מסויים שמכילה 4 משימות, הוספתי את המשימות שבתבני למשימות הפרויקט עד שהגעתי ל12 משימות ולאחר מכן המערכת החלה לקפוץ ולהשתבש .
[Open #47 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/47)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/09-18/b83aec88-a46c-4105-bbf1-9ec4efdb5f9b.png'>![Usersnap Feedback - יצרתי תבנית חדשה באחת המשימות מפרויקט מסויים שמכילה 4 משימות, הוספתי את ה(...)](https://usersnappublic.s3.amazonaws.com/2017-04-26/09-18/81ec07e7-c357-4c77-8657-14f1eb94d8c6.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/09-18/b83aec88-a46c-4105-bbf1-9ec4efdb5f9b.png'>Download original image</a>

**Browser**: Chrome 56 (Windows 7)
**Referer**: [http://40.71.214.223:3002/tasks/all/58ff0a218158132b097a2dce/activities](http://40.71.214.223:3002/tasks/all/58ff0a218158132b097a2dce/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ohadetsion** [comment]
https://github.com/linnovate/root/commit/34857eb2387defbf296649dfcd82741bbb305730
