### ISSUE TITLE
Usersnap Feedback - שם היוזר יוצא מהמסגרת בטען תבנית משימות

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#461]
**Sender**: dvorad@linnovate.net
**Comment**: שם היוזר יוצא מהמסגרת בטען תבנית משימות
[Open #48 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/48)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/09-44/76d1d4f7-3372-48fc-bad4-916f9c241996.png'>![Usersnap Feedback - שם היוזר יוצא מהמסגרת בטען תבנית משימות](https://usersnappublic.s3.amazonaws.com/2017-04-26/09-44/26e79d67-8843-459f-8e78-5d6e51c8b17f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/09-44/76d1d4f7-3372-48fc-bad4-916f9c241996.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/all/58fdbd2e88e80e6c5a1837e9/activities](http://localhost:3006/tasks/all/58fdbd2e88e80e6c5a1837e9/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ohadetsion** [comment]
https://github.com/linnovate/root/commit/93690957ac611b0b90849980fae413840a1d3e05
