### ISSUE TITLE
Usersnap Feedback - תצוגה משובשת לאחר שמירת תבנית חדשה עם הרבה תתי משימות יותר מ- 5

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#463]
**Sender**: dvorad@linnovate.net
**Comment**: תצוגה משובשת לאחר שמירת תבנית חדשה עם הרבה תתי משימות יותר מ- 5
[Open #50 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/50)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/09-46/2b8fe834-34b0-46cc-be70-b6ed18f1e5ea.png'>![Usersnap Feedback - תצוגה משובשת לאחר שמירת תבנית חדשה עם הרבה תתי משימות יותר מ- 5](https://usersnappublic.s3.amazonaws.com/2017-04-26/09-46/d97acf18-233a-4da9-a71f-614fc7feab80.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/09-46/2b8fe834-34b0-46cc-be70-b6ed18f1e5ea.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/all/58fdbd2e88e80e6c5a1837e9/activities](http://localhost:3006/tasks/all/58fdbd2e88e80e6c5a1837e9/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

http://localhost:3006/tasks/all/58fdbd2e88e80e6c5a1837e9/activities

**Comment by ohadetsion** [comment]
https://github.com/linnovate/root/commit/34857eb2387defbf296649dfcd82741bbb305730
