### ISSUE TITLE
Usersnap Feedback - לא מתבצע חיפוש עם מספרים בעוד שיש משימות שהשם שלהן הוא מספר

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#464]
**Sender**: guy@energyteam.co.il
**Comment**: לא מתבצע חיפוש עם מספרים בעוד שיש משימות שהשם שלהן הוא מספר
[Open #51 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/51)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/12-35/a42e53a7-eb89-4574-ac9d-f40eb03279eb.png'>![Usersnap Feedback - לא מתבצע חיפוש עם מספרים בעוד שיש משימות שהשם שלהן הוא מספר](https://usersnappublic.s3.amazonaws.com/2017-04-26/12-35/238bb4dc-9aa4-4096-a7a8-500fb74290d9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/12-35/a42e53a7-eb89-4574-ac9d-f40eb03279eb.png'>Download original image</a>

**Browser**: Chrome 56 (Windows 7)
**Referer**: [http://40.71.214.223:3002/search/12](http://40.71.214.223:3002/search/12)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by Baraks24** [comment]
I dont see the bug

**Comment by ohadetsion** [comment]
Can't see the bug

**Comment by YehuditGrinwald** [comment]
Works in Linux, windows 10 - chrome 59.0.3071.104.

**Comment by liorkesos** [comment]
We checked this against this environment (in hebrew)
http://root.hrm.demo.linnovate.net/
