### ISSUE TITLE
Usersnap Feedback - כאשר יוצרים משימה חדשה ומשתמשים באותיות באנגלית המערכת "משתגעת", חושבת, נת[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#465]
**Sender**: guy@energyteam.co.il
**Comment**: כאשר יוצרים משימה חדשה ומשתמשים באותיות באנגלית המערכת "משתגעת", חושבת, נתקעת, מחליפה אותיות
[Open #52 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/52)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/13-11/7ddfaca7-fa31-4442-95cb-397187b85930.png'>![Usersnap Feedback - כאשר יוצרים משימה חדשה ומשתמשים באותיות באנגלית המערכת "משתגעת", חושבת, נת(...)](https://usersnappublic.s3.amazonaws.com/2017-04-26/13-11/f0b19a5c-65af-4f98-a29e-fab174ebcd08.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-26/13-11/7ddfaca7-fa31-4442-95cb-397187b85930.png'>Download original image</a>

**Browser**: Chrome 56 (Windows 7)
**Referer**: [http://40.71.214.223:3002/tasks/by-project/58fefd7f8158132b097a2d42/59007f5676c66a8c3a3e67fd/activities](http://40.71.214.223:3002/tasks/by-project/58fefd7f8158132b097a2d42/59007f5676c66a8c3a3e67fd/activities)
**Screen size**: 1280 x 1024 **Browser size**: 1280 x 894

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by rivkatzur** [comment]
@GuyKaplan לא הצלחתי לשחזר, 
האם אפשר לפרט יותר?

**Comment by GuyKaplan** [comment]
היא פשוט לחצה על הפלוס הכתום לפתוח משימה חדשה, היא פשוט התחילה לכתוב עם קאפס לוק כמו בתמונה והמערכת התחילה לטעון את עצמה והסימון של הטעינה כל הזמן חשב. ראיתי את זה קורה מספר פעמים.

**Comment by YehuditGrinwald** [comment]
Works in Linux, windows 10 - chrome 59.0.3071.104.

**Comment by liorkesos** [comment]
I verified it works for me fine here (osx, chrome)
http://root.hrm.demo.linnovate.net/
