### ISSUE TITLE
Manage task in discussion doesn't work

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#466]
In press here on "Manage tasks" in discussion:
![image](https://cloud.githubusercontent.com/assets/17906421/25471058/16ea205a-2ada-11e7-8313-be6c4a360c6c.png)

It transfer to different page but it's infinity loading
![image](https://cloud.githubusercontent.com/assets/17906421/25471065/25881be4-2ada-11e7-9697-b5f5f8c2950c.png)

**Comment by Baraks24** [comment]
Happens only when there are no tasks in the project/discussion

**Comment by Baraks24** [comment]
fixed
