### ISSUE TITLE
Usersnap Feedback - אם בוחרים בתאריך את היום הנוכחי מופיעה הודעה תאריך יעד עבר, ההודעה צריכה ל[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#467]
**Sender**: dvorad@linnovate.net
**Comment**: אם בוחרים בתאריך את היום הנוכחי מופיעה הודעה תאריך יעד עבר, ההודעה צריכה להופיע רק על תאריכים שעברו
http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/58ff574529e5a178659dd749/activities
[Open #53 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/53)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-27/10-04/8a71e2dc-e248-427a-a4b0-5f38d43571de.png'>![Usersnap Feedback - אם בוחרים בתאריך את היום הנוכחי מופיעה הודעה תאריך יעד עבר, ההודעה צריכה ל(...)](https://usersnappublic.s3.amazonaws.com/2017-04-27/10-04/2ad5f150-12cb-4dfb-a8ce-a7f6d06802d9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-27/10-04/8a71e2dc-e248-427a-a4b0-5f38d43571de.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/58ff574529e5a178659dd749/activities](http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/58ff574529e5a178659dd749/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 722

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ohadetsion** [comment]
https://github.com/linnovate/root/commit/4532209f1070cca61758b176bd4d4577f72c60ec
