### ISSUE TITLE
Usersnap Feedback - מסמך וורד שהועלה במשימה לדיון לא מופיע בלשונית מסמכים של הדיון בעצמו http:[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#468]
**Sender**: dvorad@linnovate.net
**Comment**: מסמך וורד שהועלה במשימה לדיון לא מופיע בלשונית מסמכים של הדיון בעצמו
http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/documents
[Open #54 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/54)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-27/10-07/9fea30d4-4bbf-44de-b17a-31ba7400ad2c.png'>![Usersnap Feedback - מסמך וורד שהועלה במשימה לדיון לא מופיע בלשונית מסמכים של הדיון בעצמו http:(...)](https://usersnappublic.s3.amazonaws.com/2017-04-27/10-07/bbcea7c4-c70f-4678-a490-2008fedb428e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-27/10-07/9fea30d4-4bbf-44de-b17a-31ba7400ad2c.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/documents](http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/documents)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by YehuditGrinwald** [comment]
Don't see the bug.

**Comment by YehuditGrinwald** [comment]
Works in Linux, windows 10 - chrome 59.0.3071.104.
