### ISSUE TITLE
Usersnap Feedback - לחיצה על זמן דיון לא עובדת בעברית ואנגלית http://localhost:3006/tasks/by-disc[...]

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#469]
**Sender**: dvorad@linnovate.net
**Comment**: לחיצה על זמן דיון לא עובדת באתר בעברית ואנגלית
undefined "$rootScope.warning"

http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/activities
[Open #55 in Usersnap Dashboard](https://usersnap.com/a/#/hrm/p/hrm-43bafc5d/55)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-27/10-10/5423ef4b-29c7-45c5-8601-ce4c0160e006.png'>![Usersnap Feedback - לחיצה על זמן דיון לא עובדת באתר בעברית http://localhost:3006/tasks/by-disc(...)](https://usersnappublic.s3.amazonaws.com/2017-04-27/10-10/d58902b5-0c68-4f6f-9771-c156610f0ca2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-27/10-10/5423ef4b-29c7-45c5-8601-ce4c0160e006.png'>Download original image</a>

**Browser**: Chrome 57 (Linux)
**Referer**: [http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/activities](http://localhost:3006/tasks/by-discussion/587c76aa748d79fb1d799af2/activities)
**Screen size**: 1920 x 1080 **Browser size**: 1855 x 966

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ohadetsion** [comment]
Only happens in @dvorad local server.
