### ISSUE TITLE
Error when send URL to unauthorized

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#470]
Only happens when send URL "tasks by...":
![image](https://cloud.githubusercontent.com/assets/17906421/25474702/f7c2e37e-2ae8-11e7-9d51-8f88ca02d886.png)

And that what the unauthorized see:
![image](https://cloud.githubusercontent.com/assets/17906421/25474731/1f2b1864-2ae9-11e7-8461-c7962290b37a.png)

**Comment by Baraks24** [comment]
fixed
