### ISSUE TITLE
IMPORTANT - change socket port to node port

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#473]
IMPORTANT
Now the socket.io run on the different port (3003) as the node runs (3002) - as you can see in config/env/all.js.

But we need to change the port socket so it's run on same createServer (same port) as the node does.
In here the system runs different express for the socket.io. But it's need to be change:
root/packages/custom/mean-socket/server/routes/meanSocket.js

**Comment by liorkesos** [comment]
Ok, I remember this.
the socketio package in mean once worked with 2 ports and consolidated to working with 1 port
This is the commit that chaged the package...
https://github.com/linnovate/meanio-socket/commit/d906d8318c09c0673ab084d93f77f085118160f4
Rivka please examine and reimplement the changes (I assumed we started before this change was made in meanio-socket)

**Comment by rivkatzur** [comment]
https://github.com/linnovate/root/commit/c72c489bcf37b28c337a414d822646cc364f8bbf

**Comment by rivkatzur** [comment]
@ohadetsion I pushed https://github.com/linnovate/root/commit/c72c489bcf37b28c337a414d822646cc364f8bbf
