### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by oritpersik** [linnovate/root#474]
The service was down after this error:

current user
{"__v":0,"id":"lior@linnovate.net","name":"ליאור","email":"lior@linnovate.net","username":"ליאור קיסוס","_id":"594f64f7b7a63e11007359eb","provider":"local","roles":["authenticated"]}
/usr/src/app/packages/custom/icu/server/controllers/templates.js:184
              if (subtask.templateId.toString() === task._id.toString()) {
                         ^

TypeError: Cannot read property 'templateId' of undefined
    at EventEmitter.<anonymous> (/usr/src/app/packages/custom/icu/server/controllers/templates.js:184:26)

**Comment by ohadetsion** [comment]
Cant understand what you did before you got this
