### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#477]
Print possibility in lists.
It's need to print in every entity list. (All, MyTasks, Tasks from project and etc.)
The print button needs to design, and also how the printed page itself looks like.

The data that will be print:
In Tasks: name, (if in a project) project name, status, due date, name of assign.
              * If there is sub-tasks of this task, needs also to print and design according to it.
In Projects: name, status.
In Discussions: name, status, due date, name of assign, location, watchers.

In lists who been filtered, for example: "tasks from project" , On the printed page will be writen the data of the project (that above-mentioned) or other entity.

**Comment by oritpersik** [comment]
@ohadetsion resolved
