### ISSUE TITLE
Tasks Don't inheritance

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#478]
When we create project, from this project we create discussion, and from this discussion we create task.
So:  Project **->** Discussion **->** Task.
The task **don't** inheritance that it's from the project.

**Comment by sarareisner** [comment]
I didnt see the bug :
https://drive.google.com/open?id=0By-_J8BTh6HGQk94ZVp6YUwtZG8

**Comment by ohadetsion** [comment]
As you can see, you are in tasks from project "sfs".
The bug is when you in the make new tasks from the **discussion** "dsds" that it is from the project "sfs".
After you make the discussion, go to tasks from this discussion (from the sidebar), then uoy see it.

**Comment by oritpersik** [comment]
@ohadetsion resolved

**Comment by ohadetsion** [comment]
@sarareisner @oritpersik 
Works but the tasks open vrey slow and needed to refresh. Also have the error in F12 console:
POST http://--THE IP--:3002/api/tasks net::ERR_INCOMPLETE_CHUNKED_ENCODING           angular.js:10765

**Comment by oritpersik** [comment]
@ohadetsion We do not see this bug. can you record it please ?

**Comment by ohadetsion** [comment]
@oritpersik Talk to @liorkesos , he will explain you the bug

**Comment by ohadetsion** [comment]
It looks OK, but I have a bug when i want to create the task that inheritance:
![image](https://user-images.githubusercontent.com/17906421/30151131-e7e8df58-93b6-11e7-8ddd-2cce1c8f0b37.png)

The bug in the terminal:
![image](https://user-images.githubusercontent.com/17906421/30151192-2dfd2ecc-93b7-11e7-880a-36e21e1fa1a5.png)


After Refresh the task did create:
![image](https://user-images.githubusercontent.com/17906421/30151237-4f454bd2-93b7-11e7-8ca4-af27bd358a82.png)

**Comment by liorkesos** [comment]
@dvoras is this done? Please close if it is .

**Comment by dvoras** [comment]
@liorkesos I don't know what  is this task, and when I assigned to her
