### ISSUE TITLE
Bold name in search

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#488]
In search, the search term needed to be bold like in the Design:
![image](https://user-images.githubusercontent.com/17906421/30324935-77a4b5e6-97cb-11e7-8218-a35ddef5931a.png)

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/30631419-d3f55e3c-9dec-11e7-9bdf-cfeaa92474fd.png)
done on master hag sameiach!

**Comment by liorkesos** [comment]
@dvoras is this done? Please close if it is .
