### ISSUE TITLE
No auto notification in tab "updates"

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#489]
When user1 assign user2 in task (for example) in the tab "updates", automatic there is new update that user1 assign user2 to this task.
The problem is it's only happen when you assign.
In every entity, if the user change something from the entity-details top-bar, **it's must** represented in the tab  "updates".

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/30631542-4189479c-9ded-11e7-8d89-cf67fd47c0d2.png)
done for project and task.

**Comment by ohadetsion** [comment]
@nevos When i add watcher it's represented in the tab "updates", but when i remove watcher it didn't..

**Comment by liorkesos** [comment]
@dvoras is this done? Please close if it is .
