### ISSUE TITLE
Review logs in tab "updates"

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#507]
There is still some places  where the logs don't works perfectly, also needed to check in Hebrew that all translated correctly and it's visible good.

**Comment by dvoras** [comment]
@ohadetsion Can you specify which places it doesn't work?

**Comment by ohadetsion** [comment]
dvoras
I will try to send screenshots, but i can tell that right now there some problem in the new entities.
And please check in hebrow because it's little diffrent
