### ISSUE TITLE
Bug in search with officeDocuments

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#523]
The search works fine in the other entities.
![image](https://user-images.githubusercontent.com/17906421/34375047-3a155b2a-eaed-11e7-8119-442e630435c9.png)

But if i search officeDocument, Or search something that has same name in anther entity and in officeDocuments, the search finds all of them, but i can filter by entity, and also it wrote "(0)" in the entities that he actually found it:
 
![image](https://user-images.githubusercontent.com/17906421/34375141-a7a6679c-eaed-11e7-9fb9-5bf669a0a8f2.png)

Also happens only if the officeDocument is the only search result:
![image](https://user-images.githubusercontent.com/17906421/34375209-fbee14b2-eaed-11e7-9a2f-4499029ea4ba.png)

**Comment by liorkesos** [comment]
I think this was resolve.
Please close if it works for you.
