### ISSUE TITLE
Active/ Not active support

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#525]
- [x] Add active / non active filter on the side (beneath project/ people etc..)
- [x] Change translation on sort (currently סינונים in hebrew)

**Comment by nevos** [comment]
@liorkesos 
1. active / non active - relates to what? recycle? 
2. change translation of "סינונים" to? 
"מיונים"??

**Comment by nevos** [comment]
- Each status will have an active/not-active attribute.
- When we display lists - we will only show active attributes by default.
- We will have an icon, active by default  (similar to starred filter) that when in non-active state, will allow not active statuses to display.

**Comment by ohadetsion** [comment]
@nevos Notice that in All Projects, active/not-active attribute doesn't work:

![image](https://user-images.githubusercontent.com/17906421/35379610-5491d5e4-01bf-11e8-8ac9-a088efda17f9.png)

**Comment by nevos** [comment]
@ohadetsion see https://github.com/linnovate/root/blob/master/config/activeStatusSettings.js - config there
