### ISSUE TITLE
Right side filter design is not clear enough to users

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#526]
Even small changes could help users understand the filter in glance (icononifgraphics , subtle css fixes).
![image](https://user-images.githubusercontent.com/245027/34649706-db6790ec-f3bc-11e7-9566-0b3aceb55163.png)

**Comment by nevos** [comment]
<img width="794" alt="273945319" src="https://user-images.githubusercontent.com/1281931/35089357-5de1c97c-fc3f-11e7-84ba-658206bbb960.png">

**Comment by nevos** [comment]
@manmorc please change the following strings in submenu:

1. project - 
"tasks in project"
"משימות של פרוייקט"
2. meeting - 
"tasks from meeting"
"משימות מדיון"
3. assigned -
"tasks assigned to"
" משימות משוייכות ל"

@Dolevco - please confirm strings.
