### ISSUE TITLE
Add recycle bin

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#529]
Add a recyclebin type of state - so when we remove a task it goes there instead of removing.

**Comment by nevos** [comment]
does this make a task "archived", as per #524

**Comment by nevos** [comment]
After discussion with @liorkesos we decided that we will add a object called 'deleted'  on the model and toggle them accordingly
model could be
```
deleted:{
  'date':date,
  'state':boolean
}```

**Comment by nevos** [comment]
@liorkesos needed design for recycle bin under config setting

**Comment by nevos** [comment]
@arbel we need design for recycle/unrecycle buttons, as well as location from which to do these actions.
cc @liorkesos
