### ISSUE TITLE
Advanced search #2

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#530]
- [x] Design filter by time
- [x] Design filter by status (active/non active grouped)
- [x] Imlement filter by time functionality
- [x] Implement filter by statusfunctionality
- [ ] Fine tune to the design

**Comment by liorkesos** [comment]
![icu](https://user-images.githubusercontent.com/245027/34649903-4de76d2e-f3c0-11e7-8db4-53d79392529e.png)

**Comment by liorkesos** [comment]
We will need an icon of an attachement

**Comment by nevos** [comment]
@arbel @liorkesos  where is the design for this? please link

**Comment by nevos** [comment]
@liorkesos we need a functional definition + design of **filter by time** - how we filter by search time.
@liorkesos we need a functional definition + design of search **filter by status** - how we filter search by status.

**Comment by liorkesos** [comment]
We spoke about it in the meeting with Dolev..
time - filter by creation time
status - filter by active/unactive 
Idan said he'll supply the design in sunday
