### ISSUE TITLE
Integrate document viewer

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#534]
Integrate document viewer for attachment quickview
https://www.npmjs.com/package/viewer#quick-start

**Comment by nevos** [comment]
@liorkesos the api for boxviewer has been discontinued:
https://community.box.com/t5/Box-Product-News/Deprecation-Crocodoc-Box-View/ba-p/49941

**Comment by nevos** [comment]
summary of this:
1) see that download gets the correct base url / url to dl
2) try to find a good viewer / possibly browser native
3) position to view - if possible replace details view with doc view

**Comment by nevos** [comment]
1. Tried another plugin that didn't integrate well.
2. Download of files now works on different hosts.

**Comment by nevos** [comment]
integrated document viewer for search

**Comment by nevos** [comment]
comment: finetune requirements and design needed.
