### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by nevos** [linnovate/root#600]
we will have 3 type of notifications: 
1) Added as assignee
2) Added as watcher
3) - [ ] **new** document received (document sent to me / not viewed yet)

Each notification has 2 states: new, viewed
- [ ] different colors. + Design.

Top bar -
When clicked, opens notifications dropdown (as it is today).
- [ ] When closed - show **last** unread.
- [ ] When all read - show text “no new notifications”.
- [ ] Only when dropdown open - the notifications clicked will redirect. exists?
- [ ] Each notification clickable when dropdown open - when clicked goes to linking entity (task,document). exists?
- [ ] When notification clicked - set notification status as read, redirect. exists?
- [ ] When entity deleted, notification is deleted. 
- [ ] Notification icon - should show number of new notifications.
- [ ] Make sure that active notification is not overflowing the top tab. (when closed) 
- [ ] Each notification will display one line only (design) / hide overflow

**Comment by ohadetsion** [comment]
Outdated
