### ISSUE TITLE
Dosen't show folders from office

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#604]
In the sidebar, in the "Documents" section, after i select office, it dosen't show folders from office (from any office):
![image](https://user-images.githubusercontent.com/17906421/36525067-1b225894-17b1-11e8-939a-96de606e324e.png)

This is the console:
![image](https://user-images.githubusercontent.com/17906421/36525109-3fa125ec-17b1-11e8-8f87-02355641e1cd.png)

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/36528008-6c8a72ec-17bc-11e8-9126-8aa48f338a3b.png)
@ohadetsion need further explanations about what is the bug.

**Comment by nevos** [comment]
line #339 in packages/custom/icu/public/components/display-by/display-by.html
starts the list of folders under an office that are currently not displaying. 
They act as filter to the main pane.

![image](https://user-images.githubusercontent.com/1281931/36529769-fc61831a-17c1-11e8-9caf-154d9dea26ba.png)
