### ISSUE TITLE
Recycle - disable

### ISSUE THREAD

**Issue by nevos** [linnovate/root#615]
- [x] Client side - add ng-disabled
- [x] Add cursor for disabled fields + class
- [ ] Server side - update/submit check if deleted entity. - **not to do for now**

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/37600203-58024ed0-2b8f-11e8-9b71-5d79f5caeed2.png)
@manmorc FYI

**Comment by nevos** [comment]
@manmorc also the user profile field is disabled.

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/37600353-c4637cfc-2b8f-11e8-8c42-8646dc153536.png)

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/37716943-573706ea-2d28-11e8-890b-b9452c42b7ef.png)
problems in recycle disable

**Comment by nevos** [comment]
@manmorc  select tags is still active please fix.

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/37891881-8c15ae70-30de-11e8-9862-cb6a0359e401.png)
@manmorc - disable subs in recycled. disable select project when recycled.
-allow to switch tabs when recycled.

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/pull/681
