### ISSUE TITLE
Upgrade Mongo

### ISSUE THREAD

**Issue by nevos** [linnovate/root#620]
- [x] upgade mongo to LTS (v 363) 
https://www.mongodb.com/download-center#community
https://docs.mongodb.com/manual/release-notes/3.4/#changes-affecting-compatibility
https://docs.mongodb.com/manual/release-notes/3.6-compatibility/
- [x] upgrade mongoose (v? latest possible on mean version) 
http://mongoosejs.com/docs/compatibility.html
https://github.com/Automattic/mongoose/blob/master/History.md#500--2018-01-17
- [x] upgade npm (v? if necessary)
- [x] upgrade node (v? if necessary)

**Comment by liorkesos** [comment]
Works for me after I upgraded to 4.13.11
https://github.com/linnovate/root/commit/4b091a3d8d86bd970c5425db1717cd50953aa018

**Comment by liorkesos** [comment]
@ohadetsion please review at your side and close if it works for you...
