### ISSUE TITLE
Permission - apply rules

### ISSUE THREAD

**Issue by nevos** [linnovate/root#624]
- [x] Viewer  - has view access only.
- [x] Commenter - has view access. Add updates in updates box, including attaching files.
- [x] Editor -  full access, including changing permissions to watchers.
- [x] Assignee has additional button / status

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/37760925-d40ac0d8-2dc0-11e8-9aa4-c954dcda9e7f.png)
please see console permission errors on http://localhost:3002/tasks/my/activities

**Comment by manmorc** [comment]
permission error fixed in https://github.com/linnovate/root/pull/657

**Comment by manmorc** [comment]
4) which status assignee must have: editor or assignee?

**Comment by nevos** [comment]
@manmorc -the document area is disabled in client - for commenter

![image](https://user-images.githubusercontent.com/1281931/37873224-6f17bb42-3020-11e8-9953-087efd79d04b.png)

**Comment by nevos** [comment]
assignee will become commenter - you dont need to change anything based on who is an assignee, just based on the permission level.

**Comment by manmorc** [comment]
fixed in 624-4
