### ISSUE TITLE
Search Active Status Bogus

### ISSUE THREAD

**Issue by nevos** [linnovate/root#690]
Feature Search Active Status is bogus:

Display active/archived filter top part of section. <-- this works well. (still has issues - see comments)

Show more link - by default. <-- this works well.

Active clicked - shows all statuses below, 
with on/off colors to currently “on” filtered statuses. <-- works well on the ui side - **BUT** 
when clicking show more (nothing selected)
**1) doesnt filter the statuses correctly. 
2) doesnt show all the status of all the types (waiting-approval missing for example)**

Archived clicked - shows all statuses below, with on/off colors to currently “on” filtered statuses.
Click a specific status to filter the clicked status.
**1) doesnt filter the statuses correctly. 
2) doesnt show all the status of all the types (waiting-approval missing for example)**

When a specific **entity type** is selected - Show the statuses below the line per entity selected (for example, if project is selected, show only status related to project).  <-- works well on the ui side - **BUT**
**1) doesnt filter the status correctly. 
2) doesnt show all the status of all the types (waiting-approval missing for example)**

Statuses below the line are ordered alphabetically <-- not ordered correctly.

When status filter active - hide show less. <-- works well

**Comment by nevos** [comment]
when changing status from active to done, it will not display in middle pane, and still show as found in results number

![image](https://user-images.githubusercontent.com/1281931/38467850-8e32d18e-3b46-11e8-9da0-5ffc9d4816e8.png)

**Comment by nevos** [comment]
@manmorc by default - make all statuses **active and yellow** if show more is clicked first

**Comment by manmorc** [comment]
https://github.com/linnovate/root/pull/711
