### ISSUE TITLE
Search Sections Clear

### ISSUE THREAD

**Issue by nevos** [linnovate/root#691]
1) some clear buttons dont work well
2) if you go are redirected to another part of the app, or navigate  - and return to search - the sections need to be cleared automatically.

**Comment by nevos** [comment]
@manmorc http://localhost:3002/search/___?recycled=true - recycled does not clear.
make sure that clear works well for all filter types. (some filters are displayed only if you filter by certain entity types)

please test thoroughly.

**Comment by nevos** [comment]
@manmorc clear "Show results of:" - refreshes the entire page, change the behavior so that it behaves in the same manner as the other clear buttons.

**Comment by manmorc** [comment]
https://github.com/linnovate/root/pull/698

**Comment by nevos** [comment]
http://localhost:3002/search/**?type=task** doesnt clear automatically after routing to different sections (on main menu)

**Comment by nevos** [comment]
@manmorc other testing - &recycled=true still does not clear well.

**Comment by manmorc** [comment]
https://github.com/linnovate/root/pull/713
