### ISSUE TITLE
search number results is not the same as list

### ISSUE THREAD

**Issue by nevos** [linnovate/root#693]
the numbner of results found (results number in the details pane) is not the same as list of items presented (check sub project/ subtask and deleted items - might be the cause)

**Comment by manmorc** [comment]
not reproduced after cleaning elastic search, please do: 
1)check all databases of elastic search: **curl 'localhost:9200/_cat/indices?v'** 
2)DELETE http://127.0.0.1:9200/ (databases separated by commas)              or
DELETE http://127.0.0.1:9200/*           //delete all databases,
and then try to find entities

**Comment by nevos** [comment]
using release/2.0.3.1
deleted mongo and elastic
I added 3 tasks, projects and discussions, each with a name "1"

![image](https://user-images.githubusercontent.com/1281931/38171276-13ab3f16-359f-11e8-9d9c-8beea653dfdc.png)

they were correctly added (as the picutre above shows)
and indexed correctly in elastic:

![image](https://user-images.githubusercontent.com/1281931/38171281-458a9644-359f-11e8-8b6d-ef99d6c0261a.png)


search finds them (we see results in both the details pane and the submenu) 
BUT NOT IN LIST

![image](https://user-images.githubusercontent.com/1281931/38171269-e4db5d74-359e-11e8-91a6-f67fa13b1002.png)

**Comment by manmorc** [comment]
https://github.com/linnovate/root/pull/698 , fixed default filter value
