### ISSUE TITLE
Hyper-link not working.

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#729]
Create a new something.
Add a name to the header.
Mark all the header and click on *.
Add a link to the header.
Expected result: when click on the header will be transferred to the web in the link.
Actual result: nothing happend.

**Comment by nevos** [comment]
@AviramAshkenazi I wasnt able to reproduce, please explain better what you did with screenshots / words

**Comment by nevos** [comment]
@ohadetsion the issue relates to external links. should they work? your comment.

**Comment by ohadetsion** [comment]
They should, not critical at all
