### ISSUE TITLE
Documents: after naming a new document using the naming from the list option, and pressing enter, it doesn't update the name and the system jumps to the first document on the list

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#731]
@nevos @AviramAshkenazi after naming a new document using the naming from the list option, and pressing enter, it doesn't update the name and the system jumps to the first document on the list when it should just update the document's name to the new one.

**Comment by nevos** [comment]
this happens for when creating new docs only

**Comment by nevos** [comment]
releated to https://github.com/linnovate/root/issues/732

**Comment by nevos** [comment]
resolved in https://github.com/linnovate/root/commit/31062e1178f9d2937af9ffeb048b8e1bc8843790
