### ISSUE TITLE
Documents: after changing a users permissions, the system jumps to the first document on the list 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#732]
@nevos @AviramAshkenazi  after changing a users permissions, the system jumps to the first document on the list, when it should change the permission automatically and stay on the document.

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/pull/739

**Comment by nevos** [comment]
@manmorc it is reproducible after fix #739 -- this happens only in docs
