### ISSUE TITLE
Change the entity name with viewer permission

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#733]
Open a new task.
Fill the fields.
Add one friend as a member and set his permission as a viewer.
Sign in with the member to the app.
Get into the task.
Click on the all tasks line and choose the task you just created.
Change the name.
Expected result: can't change the name.
Actual result:the name get the changes.

P.S : this is only the example of this happening in the tasks tab, when it also happens on all the other entities as well.

**Comment by nevos** [comment]
@manmorc in the middle pane - there is an option to edit the title of tasks. disable this option for tasks in which the user is not editor

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/pull/735
