### ISSUE TITLE
document can't give a premonition to member 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#748]
@nevos @yaronmir
open a new document.
fill the fields.
add member to the document.
give to him premonition as a Editor or commenter.
Expected result: the friend will added to the document with the premonition.
Actual result: nothing happened and jump to the first document.

**Comment by nevos** [comment]
I cannot reproduce this, since when you add a user in a new doc - the list jumps to the first document
https://github.com/linnovate/root/issues/731
Also, the new document without the title holds the new user added
