### ISSUE TITLE
last-notification line not working

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#749]

**Comment by nevos** [comment]
not clear pleas provide further explanations/screenshot

**Comment by nevos** [comment]
@AviramAshkenazi I wasnt able to understand, please explain better what you did with screenshots / words

**Comment by AviramAshkenazi** [comment]
do some action (delete same task)
in notification line you should see a  message in last-notification line about that.
excepted result :
![image](https://user-images.githubusercontent.com/31100069/38796370-e71fd760-4163-11e8-8d5b-775c85cf2a61.png)
actual result:
![image](https://user-images.githubusercontent.com/31100069/38796431-1db9d9f6-4164-11e8-80e2-79d93dd1009f.png)
nothing happened.

**Comment by nevos** [comment]
@ohadetsion your comment
