### ISSUE TITLE
can't add tag after the first tag in any entitey.

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#751]
open a new entity.
fill the fields.
add a new tag to the entity.
can't add another one.(plus button is unavailable) .

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/38811908-7f711360-4193-11e8-8936-14d259965681.png)

**Comment by nevos** [comment]
@astein2018 @aronStein cant see this resolved in
http://localhost:3002/folders/all
http://localhost:3002/discussions/all
