### ISSUE TITLE
folder change statues

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#753]
open a new folder.
fill the fields.
click on the status.
choose office is transparent to the status line.
![image](https://user-images.githubusercontent.com/31100069/38798110-4879f298-4169-11e8-9b52-cec70295de16.png)

**Comment by AviramAshkenazi** [comment]
because this bug can't choose status:in progress.

**Comment by nevos** [comment]
@ohadetsion minor ui issue

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/38815432-99867a98-419c-11e8-8a80-1187595633f9.png)
