### ISSUE TITLE
visual bug printer buttons

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#756]
2 printer buttons in the tasks tab, one of them opens up a new ICU tab

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/38803326-86e43a3a-4177-11e8-8646-a62739dc1fe1.png)
links to http://localhost:3002/api/Excelfiles/notes/n1@gmail.comTasks.xlsx

@ohadetsion please comment

**Comment by nevos** [comment]
@ohadetsion FYI
