### ISSUE TITLE
visual bug: folder from office

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#757]
Open a new office.
fill the fields.
click on folders.
create a new folder.
not able to see the folder name of the of the office in main-pane.
![image](https://user-images.githubusercontent.com/31100069/38800597-63ddb748-4170-11e8-85fd-228b295d5f15.png)

**Comment by nevos** [comment]
minor ui

**Comment by nevos** [comment]
resolved in 7af8f147b1ad99c228ea819d00a61ddea37eac78

**Comment by AviramAshkenazi** [comment]
@nevos 
also should fix in the same way in document. there we have the same problem. 
/home/sapir/Desktop/Screenshot from 2018-04-16 16-59-05.png
