### ISSUE TITLE
pick office in templateDoc 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#758]
open a new templateDoc.
click on choose office.
can't see the names of the offices.
![image](https://user-images.githubusercontent.com/31100069/38802264-9f3114c6-4174-11e8-9c28-a597601e5103.png)

**Comment by AviramAshkenazi** [comment]
also in document.
![image](https://user-images.githubusercontent.com/31100069/38802852-2377e29a-4176-11e8-867e-e988e169e1e7.png)

**Comment by nevos** [comment]
happens in tikim

**Comment by nevos** [comment]
FYI seems refixed

**Comment by nevos** [comment]
also in document. not fixed

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/39759341-1da9fb52-52db-11e8-8291-4aceda69efe7.png)
