### ISSUE TITLE
backward compatibility tests for 203

### ISSUE THREAD

**Issue by nevos** [linnovate/root#773]
1) dump mongo, elastic.
2) get https://github.com/linnovate/root/releases/tag/2.0.2.3
3) create an entity of each type.
4) export mongo db (203 data)
5) get release/2031
6) check for any server/client problems, focus on permissions.

**Comment by manmorc** [comment]
1) in documents permissions array is empty, so all entities are blocked
2) in templateDocs permissions array is empty, so all entities are blocked (edited)
