### ISSUE TITLE
very long title

### ISSUE THREAD

**Issue by omerzamir** [linnovate/root#780]
when adding very long name(no matter in which entity -> only on creation not on update), text is pushed out of boundaries until nothing is shown in the textbox.

![screenshot from 2018-04-22 12-56-04](https://user-images.githubusercontent.com/20604924/39093755-5c6da70e-462d-11e8-9650-a274576f1123.png)
![screenshot from 2018-04-22 13-00-47](https://user-images.githubusercontent.com/20604924/39093756-5c8d0bd0-462d-11e8-8d07-0e816a782cba.png)

**Comment by nevos** [comment]
this behavior occurs before responsive fixes and related to known elipsis bug. 
The resolution is that we remove te elipsis altogether and have a html element fadeout

**Comment by nevos** [comment]
https://stackoverflow.com/questions/9793473/text-overflow-ellipsis-on-left-side

**Comment by nevos** [comment]
@manmorc currently dev doesnt show elipsis at the end of long title. 
please backport from master. I believe the relevant pr is this:
https://github.com/linnovate/root/pull/785

**Comment by nevos** [comment]
@manmorc backport status here please.
