### ISSUE TITLE
filter documents by folder

### ISSUE THREAD

**Issue by nevos** [linnovate/root#799]
- [x] 1. the ui element is cut. / hebrew / test chrome 44
- [ ]  2. the data in the dropdown is not updated with offices when entering the document page using menu.
- [ ] 3. the data BELOW the dropdown is not updated with folders when entering the document page using menu.
- [x]  4. after choosing different folder (filter) the list doesnt update.
- [x] 5. check for html tags as well

fix only 1 and 4, 5 for now.

**Comment by nevos** [comment]
FYI suspecting most of the update issues are from previous

**Comment by nevos** [comment]
check for html tags as well
![image](https://user-images.githubusercontent.com/1281931/39524242-f8ffb148-4e20-11e8-9b66-51e7719a0af5.png)

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by nevos** [comment]
@manmorc backport only the code we updated in 204

**Comment by nevos** [comment]
fix 2,3 in dev

**Comment by manmorc** [comment]
none-reproducible in dev & chrome 44
