### ISSUE TITLE
Submenu gray part cut

### ISSUE THREAD

**Issue by nevos** [linnovate/root#805]
The submenu gray part should not be cut, and should always display full page length as the menu.
it might also cuts functional parts in search submenu
SUB menu-האפור (שני מימין) נחתך, לא ניתן לראות את התיקים ואת הדברים אחרי ה"עוד"

**reproducible in chrome 44**
**
![image](https://user-images.githubusercontent.com/1281931/39521581-c5e677a0-4e17-11e8-9ec0-2e13b9852174.png)
**

should be like this:
![image](https://user-images.githubusercontent.com/1281931/39521672-2ea8b802-4e18-11e8-9386-c6f45c912bfd.png)

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
none-reproducible in develop and 44 chrome
