### ISSUE TITLE
deleted items(black version)

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#808]
None of the deleted entities i deleted showed up 
![searching for deleted itemes bug](https://user-images.githubusercontent.com/38312178/39528211-22c4b482-4e2c-11e8-8802-bbca0bfe5630.png)

**Comment by manmorc** [comment]
not reproducible in 66 chrome, and in 44 chrome

**Comment by nevos** [comment]
@yaronmir you will need to work on a fresh dataset, and reproduce there. if you can reproduce on a fresh dataset - imported from 202, let me know.
