### ISSUE TITLE
visual bugs in discussions, projects, documents 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#811]
projects
![projects visual bug](https://user-images.githubusercontent.com/38312178/39528424-ba02d0f4-4e2c-11e8-82b7-ef21ac030eb6.png)

documents:
![documents visual bug](https://user-images.githubusercontent.com/38312178/39528428-bd338f7a-4e2c-11e8-8fcf-81ad5650398e.png)

discussions:
![discussions visual bug](https://user-images.githubusercontent.com/38312178/39528471-df900968-4e2c-11e8-989a-55c0b7b7d3dd.png)

**Comment by manmorc** [comment]
already fixed
