### ISSUE TITLE
document tab bug in every entity except projects

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#812]
doesnt show the document was added both in the updates tab and in the documents tab
![document bug in every entity but projects](https://user-images.githubusercontent.com/38312178/39528510-f44352d4-4e2c-11e8-8902-50e4b340c7f2.png)

**Comment by nevos** [comment]
@manmorc check to see if when uploading documents it shows on the updates tab

**Comment by manmorc** [comment]
none-reproducible
