### ISSUE TITLE
truncated user names in hebrew

### ISSUE THREAD

**Issue by nevos** [linnovate/root#815]
Wherever selecting users (watchers, assignees), the list display truncates long user names in hebrew. and cannot see full name. the name doesnt start from the begining.

**Comment by nevos** [comment]
![img-20180503-wa0000](https://user-images.githubusercontent.com/1281931/39584782-f0bc429a-4efb-11e8-9767-230cfc0f5dc3.jpg)

**Comment by nevos** [comment]
see image above - 
1. box is truncated 
2. names truncated as a result.

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
none-reproducible in develop & 44 chrome
