### ISSUE TITLE
http://localhost:3002/tasks/my/activities

### ISSUE THREAD

**Issue by nevos** [linnovate/root#818]
click on the green button on home page details pane

http://localhost:3002/tasks/my/activities
the list shows also deleted items. please remove the deleted items from all the home page buttons.

![image](https://user-images.githubusercontent.com/1281931/39583960-f1565e2c-4ef9-11e8-84c9-0b0776906565.png)

**Comment by nevos** [comment]
@artium resolve for all boxes in develop

**Comment by manmorc** [comment]
@nevos all boxes???

**Comment by nevos** [comment]
@manmorc  dev backport status?

**Comment by manmorc** [comment]
copy of https://github.com/linnovate/root/issues/911
