### ISSUE TITLE
In every entity you can delete yourself from the entity template, and it saves the changes after refreshing the page

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#828]
create a new entity, then click on your icon at the partners tab, click on remove, after being removed you can still change things in the entity's template , and if you change an asignee after removing yourself, the entity is now under the new asignee's screen

**Comment by nevos** [comment]
1. if you are an editor, then you should not be able to remove yourself.
2. once you removed yourself - you cannot edit anything untill refresh.
3. change entity - after removed - **cannot be reproduced**.
4. design does not reference this issue, minor - ability to remove yourself as editor in UI. will not be resolved for this version.
