### ISSUE TITLE
Cant asign a sub project's assignee + visual bug in top row of projects

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#831]
after creating a sub project and filling out it's name, status, and deadline, you cant assign a user as it's asignee

![sub projects asignee](https://user-images.githubusercontent.com/38312178/39815176-e250202a-539f-11e8-9379-a4a385c39ffd.PNG)

P.S : There's also a visual bug with the project's entity top row of the screen(asignee, favorite...)

![visual bug projects](https://user-images.githubusercontent.com/38312178/39815237-05ac7b2c-53a0-11e8-969c-556fa6d6ea0f.PNG)

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
none-reproducible in dev & chrome 44
