### ISSUE TITLE
when trying to open a new projects using the plus menu when on the discussions tab it will open a projects from project screen

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#833]
click on discussion, then click on projects in the plus menu, it will open a projects from project screen

![image](https://user-images.githubusercontent.com/38312178/39861159-64f028f6-5448-11e8-84e2-7fc6955dae93.png)

**Comment by nevos** [comment]
@manmorc please test that this is fixed on master and report here

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
none-reproducible in develop and 44 chrome
