### ISSUE TITLE
tasks update field bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#852]
after changing the detailes of a task, besides creating a new one, updating using the update field and adding a document it shows an uncompleted message 

![update field bug in task s template](https://user-images.githubusercontent.com/38312178/40114230-c2600e5e-5914-11e8-9d23-b60146533137.png)

**Comment by nevos** [comment]
@manmorc try reproduce

**Comment by manmorc** [comment]
@yaronmir have you any console errors? none-reproducible
