### ISSUE TITLE
meeting, the schedule discussion button doesnt work 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#854]
after filling out every thing, the schedule disxussion button doesnt work

**Comment by abrahamos** [comment]
This button works only when `location`, `date` and `assignee` are set.

Please make sure again.

Though, this is bad that the user doesn't get any error message for these restrictions.

**Comment by nevos** [comment]
@yaronmir did you check @abrahamos  comment?

**Comment by abrahamos** [comment]
I'm closing this issue as it works as expected
