### ISSUE TITLE
visual bug discussions 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#855]
in the discussion template the date field and the location placeholder test are out of place

![image](https://user-images.githubusercontent.com/38312178/40115503-526d34aa-5919-11e8-96dd-fe1ffeb413f2.png)

**Comment by manmorc** [comment]
https://github.com/linnovate/root/pull/864

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
fixed in dev https://github.com/linnovate/root/commit/55fcee80e029f1d89f53c0ce221b00f718a4513f
tested in chrome 44
