### ISSUE TITLE
search, when searching for a task, it doesnt show up

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#859]
when searching for a task in both the search tab and in the tasks tab it doesnt show up in the search results 

![image](https://user-images.githubusercontent.com/38312178/40123333-abf129b8-592e-11e8-9446-9f96d282d00e.png)

**Comment by nevos** [comment]
not reproducible in modern chrome

**Comment by nevos** [comment]
scenario as follows:
1) in search box click search term. 
2) the search menu become active automatically.
3) then click main menu search again.
4) the search results disappear, while the search url remains.

Wanted behavior - 
1) if you search menu is active, then **nothing should happen** when clicking it again.
2) if you search menu is inactive, and you click the search menu - the url should redirect to "search/"

**Comment by manmorc** [comment]
scenario is not reproducible

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
fixed in develop https://github.com/linnovate/root/commit/a1b7531de3886ea3fe372e113287e6271f44abde
tested on chrome 44
