### ISSUE TITLE
Visual - Creating a new document doesn't show its folder

### ISSUE THREAD

**Issue by abrahamos** [linnovate/root#863]
Steps:
1. Documents -> some_folder
1. Create new document

![screenshot from 2018-05-17 17-56-44](https://user-images.githubusercontent.com/17452685/40185676-d3f670c6-59fb-11e8-8e49-e18885e3f279.png)

Only a refresh cause the folder to be shown

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
fixed in develop https://github.com/linnovate/root/commit/5bf8020a315f39b830fbc26c9b257cbc2c6b26ec
tested in chrome 44
