### ISSUE TITLE
visual bug meetings 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#865]
in the discussion template bar, the meeting date is above the location 
![meetings visual](https://user-images.githubusercontent.com/31100069/40347747-0903e1f2-5daa-11e8-80a4-174eb8463636.png)

**Comment by manmorc** [comment]
cope of https://github.com/linnovate/root/issues/855

**Comment by nevos** [comment]
@manmorc not fixed? backport to dev status?

**Comment by manmorc** [comment]
fixed in dev: https://github.com/linnovate/root/commit/24325f17e00e3fb939ab69b48a69fae42796076f
tested in chrome 44
