### ISSUE TITLE
printer

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#866]
when there are more than 15 entities, the printer review shows only the first 15
![printer](https://user-images.githubusercontent.com/31100069/40347786-25c2a396-5daa-11e8-8af8-71f8be6bf512.png)

**Comment by nevos** [comment]
try reproduce.

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
fixed in dev https://github.com/linnovate/root/commit/966ba6766b345dc57c0de1f8c35d2fc30039a0b3
tested in chrome 44
