### ISSUE TITLE
task naming main pane bug 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#868]
after creating a new task, naming it, and editing the name using the quotation marks, it enlarges the tasks name in the main pane
![qoutation marks bug tasks](https://user-images.githubusercontent.com/31100069/40347879-8971cb74-5daa-11e8-884d-a7e6c687ac4a.png)

**Comment by nevos** [comment]
@manmorc hide any and all htmls from lists (middle pane).

**Comment by nevos** [comment]
@manmorc backport to dev status?

**Comment by manmorc** [comment]
fixed in develop https://github.com/linnovate/root/commit/a286ef8eaa9ed2e72168020098a8fe6f3c7a31be
