### ISSUE TITLE
viewing a document after pressing view document 

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#869]
in every entity, except for offices, after uploading a document and pressing on attachment preview, and then on the view document button ( the magnifying glass), nothing happens 

![view document](https://user-images.githubusercontent.com/31100069/40348167-7bd2f1cc-5dab-11e8-8a13-9ce15da25f1c.png)

**Comment by nevos** [comment]
not reproducible in regulr chrome

**Comment by nevos** [comment]
not reproducible on chrome 44
