### ISSUE TITLE
dev branch - new user 

### ISSUE THREAD

**Issue by nevos** [linnovate/root#874]
on develop branch
when there are no tasks/projects... new dataset, trying to create the first task always gives client permission console, and you cannot edit the task title

**Comment by manmorc** [comment]
i have no console errors, creating any first task/project, @nevos can you clarify the scenario how to reproduce

**Comment by manmorc** [comment]
@nevos the only bug i see, after creating a new user, app jumps to '/tasks/', so there is no list to create entity in middle pane, but no console errors

**Comment by manmorc** [comment]
none-reproducible in dev & 44 chrome
