### ISSUE TITLE
document - signatures

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#876]
In a new document page after adding a new signature, the signature doesnt show up automatically, but only after refreshing the page.

**Comment by nevos** [comment]
when clicking on signitures it goes to sharepoint for approval. 
packages/custom/icu/server/controllers/documents.js: 'url':config.SPHelper.uri+"/api/signOnDocx",
and the sp uri is error.

@ohadetsion  -  
fix on revelevant environment.
