### ISSUE TITLE
Document name

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#889]
Enter name in all document page in the main-pane didn't save the changes.

**Comment by nevos** [comment]
@manmorc - check if can reproduce - renaming document in details pane, and that it doesnt save.

**Comment by manmorc** [comment]
bug occurs only with fast refreshing the page after immediately adding title

**Comment by nevos** [comment]
@manmorc for 205/dev - can we wait to present a list until there is a response from previous request?

**Comment by manmorc** [comment]
@nevos tell me please the whole behavior
