### ISSUE TITLE
dev details - project category 

### ISSUE THREAD

**Issue by nevos** [linnovate/root#901]
1) adding project in task
2) clicking x (remove produce console)

also 3) area disabled - subtasks

![image](https://user-images.githubusercontent.com/1281931/40490829-52112ed2-5f75-11e8-9878-d61455ca9970.png)

VM8620:4 TypeError: Cannot read property 'title' of undefined
    at Object.updateEntity (tasks.service.js:313)
...

**Comment by aronStein** [comment]
- [ ] adding project in task

- [ ] clicking x (remove produce console)

- [x]  area disabled - subtasks

**Comment by nevos** [comment]
![image](https://user-images.githubusercontent.com/1281931/40608530-6d081e10-6274-11e8-870b-03077038b744.png)

@aronStein 
- [ ] templating area disabled when no subtasks

**Comment by nevos** [comment]
not reproducible - resolved.
