### ISSUE TITLE
dev - tasks from project

### ISSUE THREAD

**Issue by nevos** [linnovate/root#913]
![image](https://user-images.githubusercontent.com/1281931/40587054-f116f20a-61d2-11e8-93ef-69e47b61f9d1.png)

clicking "manage tasks" in project "tasks" tab - url should be ->
http://localhost:3100/tasks/by-project/5b0abd8963857e00133216d3/5b0abea863857e00133216dc/activities

**Comment by aronStein** [comment]
done
