### ISSUE TITLE
dev - error in api/updates when trying to upload a doc (all entities)

### ISSUE THREAD

**Issue by nevos** [linnovate/root#914]
when uploading a doc, we get a server error (due to wrong payload?)
working payload:
{,…}
context
:
{action: "added", type: "document", description: "", issue: "project", issueName: "<p>p1</p>",…}
action
:
"added"
description
:
""
issue
:
"project"
issueName
:
"<p>p1</p>"
location
:
"http://localhost:3100/projects/all/5b0abd8963857e00133216d3/activities"
name
:
"מתמטיקה.doc"
type
:
"document"
data
:
{description: "", user: {}, issue: "project", issueId: "5b0abd8963857e00133216d3", type: "document"}
description
:
""
issue
:
"project"
issueId
:
"5b0abd8963857e00133216d3"
type
:
"document"
user
:
{}

--------------
--------------
**non working payload:**
context
:
{}
data
:
{description: "",…}
description
:
""
issue
:
"entityName"
issueId
:
"5b06c19369e5ca761959dfbc"
type
:
"document"
user
:
{_id: "5b06653a94bc1625d38d6dfd", uid: "70cf8d90-5f21-11e8-b863-8d2183183e0d", id: "n@gmail.com",…}

**Comment by aronStein** [comment]
done
