### ISSUE TITLE
creating template document in middle pane by typing 'Enter' create error

### ISSUE THREAD

**Issue by manmorc** [linnovate/root#915]
error: 'POST http://localhost:3002/api/officeTemplates/5b080ee258ed6a0d2b693816 500 (Internal Server Error)'

**Comment by nevos** [comment]
please refer to where you're seeing it dev/master

**Comment by nevos** [comment]
@manmorc is this relevant? what environment?

**Comment by manmorc** [comment]
@nevos master branch

**Comment by nevos** [comment]
resolved on dev
