### ISSUE TITLE
dev - empty list new entity in middle pane

### ISSUE THREAD

**Issue by nevos** [linnovate/root#917]
when i have an empty list, by choosing archived for example
the "create new item" doesnt produce a new line in 
main pane, only a new entity in details pane

![image](https://user-images.githubusercontent.com/1281931/40609308-ebcf6a08-6276-11e8-8dad-12fea06c28fd.png)

**Comment by nevos** [comment]
@arbel need to view this live to understand this on product behaviur level + required solution.

**Comment by arbel** [comment]
I don't have a live view for this, but there are two options:

1. don't allow the creation of a new entity from the archived filter
2. initiate the task with the status that matches the filter. like we do when you create a task in a project filter

**Comment by ohadetsion** [comment]
Outdated
