### ISSUE TITLE
dev - document send does not produce the correct popup

### ISSUE THREAD

**Issue by nevos** [linnovate/root#928]
![image](https://user-images.githubusercontent.com/1281931/40621360-1fe60f8a-62a5-11e8-9c38-c723204a3a58.png)

**Comment by manmorc** [comment]
typing 'Send' button create 'Send document' popup, @nevos it is not correct?
![screenshot from 2018-05-29 11-32-40](https://user-images.githubusercontent.com/25351641/40647353-57a8e4da-6334-11e8-82e6-58cc7d3c23e6.png)

**Comment by nevos** [comment]
see this is dev
