### ISSUE TITLE
Dropdown of folders in office Doesn't show all

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#934]
In tab documents, in the sidepane there is a list of folders of the chosen office, but after the 2.0.3 responsive adds, we can't see all of the list:
![image](https://user-images.githubusercontent.com/17906421/40670134-4be981bc-6371-11e8-82d4-80c1fa568856.png)

If we smaller the resolution of the page we can see them:
![image](https://user-images.githubusercontent.com/17906421/40670407-e2a9b9fa-6371-11e8-88b4-cec5f48fdc2e.png)

I think it should be small scroll there of the folders

**Comment by manmorc** [comment]
merged to dev
https://github.com/linnovate/root/pull/950
