### ISSUE TITLE
After add some watchers to entity, the button disappeared

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#935]
After add some watchers to entity, the button move to the right (in english version) until it disappeared "after" the screen

![image](https://user-images.githubusercontent.com/17906421/40671024-674ea64c-6373-11e8-85db-3148df88252c.png)

**Comment by nevos** [comment]
Following describes how to resolve:
1. make sure each watcher has outer div of 42px.
2. in a single watchers row space is 5 pixel exactly between watchers outer div.
3. space is 10 pixel exactly between rows.

Design: https://projects.invisionapp.com/share/Y93PZRYVP#/screens/300302328
(click on +20) to view popup
Instructions:
1. The (+) sign has a fixed location (perhaps use absolute), and never changes its position, and is not relevant to the popup.
2. when there are more than 11 watchers - the last watcher changes to (+X) - where X is the number of additional watchers.
(so for example when we have 11 watchers, and 1 watcher added, the last circle will become a (+2) popup button.)
3. popup watchers grid order? TBD

**Comment by manmorc** [comment]
added to master and develop branches
