### ISSUE TITLE
Search when add watcher - "Enter" button doesn't work

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#936]
When search in every entity for watcher:
![image](https://user-images.githubusercontent.com/17906421/40671227-faeb9716-6373-11e8-8eb1-09331bf243ae.png)

Press the "Enter button" and nothing happens:
![image](https://user-images.githubusercontent.com/17906421/40671383-675cbaba-6374-11e8-86ed-49fa166c9d6f.png)

**Comment by manmorc** [comment]
not reproducible in dev

**Comment by nevos** [comment]
fix verified on dev
