### ISSUE TITLE
View of attachment doesn't work

### ISSUE THREAD

**Issue by ohadetsion** [linnovate/root#945]
The view in any attachment doesn't work:
![image](https://user-images.githubusercontent.com/17906421/40771592-6e6df3de-64c6-11e8-989c-95ff9008efcf.png)

Also type "docx" doesn't work:
![image](https://user-images.githubusercontent.com/17906421/40771568-5c913acc-64c6-11e8-824a-a4b79bbe2ce4.png)

**Comment by nevos** [comment]
@ohadetsion This was tested to be working. make sure you have the port configured correctly. Any document that was uploaded without correct config will not work as the port is kept in the mongo as part of path.

**Comment by nevos** [comment]
@ohadetsion hi what is the status? can we close?

**Comment by nevos** [comment]
inactive - marking closed.
