### ISSUE TITLE
dev - schedule discussion button doens work

### ISSUE THREAD

**Issue by nevos** [linnovate/root#948]
![image](https://user-images.githubusercontent.com/1281931/40912777-41226be8-67fb-11e8-95a9-f3afd780598a.png)

**Comment by nevos** [comment]
@manmorc  reopened

**Comment by manmorc** [comment]
tested, it works fine, 
to schedule you need to enter start date and activate 'all day', or enter start & end data and start & end time,
and enter assignee & location as well
