### ISSUE TITLE
Project selectbox changes

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#965]
- [x] 1. When you remove a project -  remove projects from the selectbox
- [ ]  2. Select box should show project heiracrhy @arbel 
<img width="863" alt="icu" src="https://user-images.githubusercontent.com/245027/41224873-233992de-6d76-11e8-9cc5-fc362ee91b99.png">

**Comment by nevos** [comment]
@arbel  - where do the color need to reflect in lists?

**Comment by nevos** [comment]
please fix  1. When you remove a project - remove projects from the selectbox

**Comment by manmorc** [comment]
@nevos 1 done

**Comment by nevos** [comment]
@manmorc test for dev/205 and close if necessary

**Comment by nevos** [comment]
referenced in #1156
