### ISSUE TITLE
dev ux fixes

### ISSUE THREAD

**Issue by nevos** [linnovate/root#974]
https://projects.invisionapp.com/d/main#/projects/prototypes/14537351

only fixfor 204 what is relevant and was handled in #703 

+ please let me know what other comments are irrelevant to the previious ux fixes

**Comment by manmorc** [comment]
i didn't found issues from https://projects.invisionapp.com/share/S2GMKU5DPKU#/screens/288542057

**Comment by nevos** [comment]
@arbel please review only fixes contained in 
https://projects.invisionapp.com/share/S2GMKU5DPKU#/screens/288542057 
and buggy, and comment here or close this issue.
reference - http://root.204.projects.linnovate.net/

**Comment by ohadetsion** [comment]
Outdated
