### ISSUE TITLE
my tasks visual title bug

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#988]
@nevos after clicking on tasks -> my tasks the title of the main pane is :

![image](https://user-images.githubusercontent.com/38312178/41525468-c12da80e-72e9-11e8-9f3e-f83727fb9a8b.png)

**Comment by nevos** [comment]
should be "המשימות שלי"
and not  "משימות מmy"

**Comment by manmorc** [comment]
משימות משלי

**Comment by nevos** [comment]
it's now "משימות משלי"
which is comprized of "משימות מ"
and "שלי"
in this case it only needs a single string "משימות שלי"
