### ISSUE TITLE
searching bug 

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#991]
@nevos 

when typing in the name of an entity , the show results on the right shows that something was found, but on the main pane it doesnt show any result, in the details part of the screen it shows an invalid message: 

![image](https://user-images.githubusercontent.com/38312178/41526087-bc53a764-72eb-11e8-92af-81cb49a91cf5.png)

**Comment by nevos** [comment]
@yaronmir please re-test, and confirm this or close if irrelevant
