### ISSUE TITLE
visual bug discussions status tab

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#996]
in discussions, after creating a new discussion, and changing it's status to cancelled, a button of cancel discussion appears.in addition a "waiting for confirmation" button (non clickable) is located beneath the status area

![image](https://user-images.githubusercontent.com/38312178/41529765-da3a9746-72f6-11e8-8a56-3439e6488d64.png)

**Comment by manmorc** [comment]
after creating discussion and changing it status to 'canceled', button 'waiting for confirmation' doesn't appear, @yaronmir can you test it in branch release/2.0.4

**Comment by manmorc** [comment]
@nevos tell me please a necessary behavior, i see only button 'cancele discussion'

**Comment by nevos** [comment]
@manmorc "waiting for confirmation" should appear only for the assignee. I believe this works as it was defined, and as in 203.
cancel - works as in 203.

I think in both cases when the discussion is cancelled, these buttons should disappear.
I moved this to 205. please do not handle for now.

**Comment by nevos** [comment]
the cancel button has another meaning - it sends cancellation email for a scheduled discussion.
@yaronmir Closing.
if you want - create another issue with clear description and screenshots of what you did and what you expect.
